#ifndef _ODIN_W2_MBEDTLS_CONFIG_H_
#define _ODIN_W2_MBEDTLS_CONFIG_H_

#define MBEDTLS_ARC4_C
#define MBEDTLS_DES_C
#define MBEDTLS_MD4_C
#define MBEDTLS_MD5_C
#define MBEDTLS_SHA1_C

#endif /* _ODIN_W2_MBEDTLS_CONFIG_H_ */
