#ifndef SERCOM_PINOUT_H_INCLUDED
#define SERCOM_PINOUT_H_INCLUDED

#include <compiler.h>

#if SAMR21E
/* SERCOM0 */
#define SERCOM0_PAD0_DEFAULT      PINMUX_PA08C_SERCOM0_PAD0
#define SERCOM0_PAD1_DEFAULT      PINMUX_PA09C_SERCOM0_PAD1
#define SERCOM0_PAD2_DEFAULT      PINMUX_PA06D_SERCOM0_PAD2
#define SERCOM0_PAD3_DEFAULT      PINMUX_PA07D_SERCOM0_PAD3

/* SERCOM1 */
#define SERCOM1_PAD0_DEFAULT      PINMUX_PA16C_SERCOM1_PAD0
#define SERCOM1_PAD1_DEFAULT      PINMUX_PA17C_SERCOM1_PAD1
#define SERCOM1_PAD2_DEFAULT      PINMUX_PA18C_SERCOM1_PAD2
#define SERCOM1_PAD3_DEFAULT      PINMUX_PA19C_SERCOM1_PAD3

/* SERCOM2 */
#define SERCOM2_PAD0_DEFAULT      PINMUX_PA08D_SERCOM2_PAD0
#define SERCOM2_PAD1_DEFAULT      PINMUX_PA09D_SERCOM2_PAD1
#define SERCOM2_PAD2_DEFAULT      PINMUX_PA14C_SERCOM2_PAD2
#define SERCOM2_PAD3_DEFAULT      PINMUX_PA15C_SERCOM2_PAD3

/* SERCOM3 */
#define SERCOM3_PAD0_DEFAULT      PINMUX_PA27F_SERCOM3_PAD0
#define SERCOM3_PAD1_DEFAULT      PINMUX_PA28F_SERCOM3_PAD1
#define SERCOM3_PAD2_DEFAULT      PINMUX_PA24C_SERCOM3_PAD2
#define SERCOM3_PAD3_DEFAULT      PINMUX_PA25C_SERCOM3_PAD3

/* SERCOM4 */
#define SERCOM4_PAD0_DEFAULT      PINMUX_PC19F_SERCOM4_PAD0
#define SERCOM4_PAD1_DEFAULT      PINMUX_PB31F_SERCOM4_PAD1
#define SERCOM4_PAD2_DEFAULT      PINMUX_PB30F_SERCOM4_PAD2
#define SERCOM4_PAD3_DEFAULT      PINMUX_PC18F_SERCOM4_PAD3

/* SERCOM5 */
#define SERCOM5_PAD0_DEFAULT      PINMUX_PB30D_SERCOM5_PAD0
#define SERCOM5_PAD1_DEFAULT      PINMUX_PB31D_SERCOM5_PAD1
#define SERCOM5_PAD2_DEFAULT      PINMUX_PA24D_SERCOM5_PAD2
#define SERCOM5_PAD3_DEFAULT      PINMUX_PA25D_SERCOM5_PAD3

#elif SAMR21G
/* SERCOM0 */
#define SERCOM0_PAD0_DEFAULT      PINMUX_PA04D_SERCOM0_PAD0
#define SERCOM0_PAD1_DEFAULT      PINMUX_PA05D_SERCOM0_PAD1
#define SERCOM0_PAD2_DEFAULT      PINMUX_PA06D_SERCOM0_PAD2
#define SERCOM0_PAD3_DEFAULT      PINMUX_PA07D_SERCOM0_PAD3

/* SERCOM1 */
#define SERCOM1_PAD0_DEFAULT      PINMUX_PA00D_SERCOM1_PAD0
#define SERCOM1_PAD1_DEFAULT      PINMUX_PA01D_SERCOM1_PAD1
#define SERCOM1_PAD2_DEFAULT      PINMUX_PA30D_SERCOM1_PAD2
#define SERCOM1_PAD3_DEFAULT      PINMUX_PA31D_SERCOM1_PAD3

/* SERCOM2 */
#define SERCOM2_PAD0_DEFAULT      PINMUX_PA12C_SERCOM2_PAD0
#define SERCOM2_PAD1_DEFAULT      PINMUX_PA13C_SERCOM2_PAD1
#define SERCOM2_PAD2_DEFAULT      PINMUX_PA14C_SERCOM2_PAD2
#define SERCOM2_PAD3_DEFAULT      PINMUX_PA15C_SERCOM2_PAD3

/* SERCOM3 */
#define SERCOM3_PAD0_DEFAULT      PINMUX_PA16D_SERCOM3_PAD0
#define SERCOM3_PAD1_DEFAULT      PINMUX_PA17D_SERCOM3_PAD1
#define SERCOM3_PAD2_DEFAULT      PINMUX_PA18D_SERCOM3_PAD2
#define SERCOM3_PAD3_DEFAULT      PINMUX_PA19D_SERCOM3_PAD3

/* SERCOM4 */
#define SERCOM4_PAD0_DEFAULT      PINMUX_PC19F_SERCOM4_PAD0
#define SERCOM4_PAD1_DEFAULT      PINMUX_PB31F_SERCOM4_PAD1
#define SERCOM4_PAD2_DEFAULT      PINMUX_PB30F_SERCOM4_PAD2
#define SERCOM4_PAD3_DEFAULT      PINMUX_PC18F_SERCOM4_PAD3

/* SERCOM5 */
#define SERCOM5_PAD0_DEFAULT      PINMUX_PA22D_SERCOM5_PAD0
#define SERCOM5_PAD1_DEFAULT      PINMUX_PA23D_SERCOM5_PAD1
#define SERCOM5_PAD2_DEFAULT      PINMUX_PA24D_SERCOM5_PAD2
#define SERCOM5_PAD3_DEFAULT      PINMUX_PA25D_SERCOM5_PAD3

#elif (SAMD10) || (SAMD11)
/* SERCOM0 */
#define SERCOM0_PAD0_DEFAULT      PINMUX_PA04D_SERCOM0_PAD0
#define SERCOM0_PAD1_DEFAULT      PINMUX_PA05D_SERCOM0_PAD1
#define SERCOM0_PAD2_DEFAULT      PINMUX_PA06D_SERCOM0_PAD2
#define SERCOM0_PAD3_DEFAULT      PINMUX_PA07D_SERCOM0_PAD3

/* SERCOM1 */
#define SERCOM1_PAD0_DEFAULT      PINMUX_PA22C_SERCOM1_PAD0
#define SERCOM1_PAD1_DEFAULT      PINMUX_PA23C_SERCOM1_PAD1
#define SERCOM1_PAD2_DEFAULT      PINMUX_PA30D_SERCOM1_PAD2
#define SERCOM1_PAD3_DEFAULT      PINMUX_PA31D_SERCOM1_PAD3

/* SERCOM2 */
#define SERCOM2_PAD0_DEFAULT      PINMUX_PA22D_SERCOM2_PAD0
#define SERCOM2_PAD1_DEFAULT      PINMUX_PA23D_SERCOM2_PAD1
#define SERCOM2_PAD2_DEFAULT      PINMUX_PA16D_SERCOM2_PAD2
#define SERCOM2_PAD3_DEFAULT      PINMUX_PA25D_SERCOM2_PAD3

#else
/* SERCOM0 */
#define SERCOM0_PAD0_DEFAULT      PINMUX_PA04D_SERCOM0_PAD0
#define SERCOM0_PAD1_DEFAULT      PINMUX_PA05D_SERCOM0_PAD1
#define SERCOM0_PAD2_DEFAULT      PINMUX_PA06D_SERCOM0_PAD2
#define SERCOM0_PAD3_DEFAULT      PINMUX_PA07D_SERCOM0_PAD3

/* SERCOM1 */
#define SERCOM1_PAD0_DEFAULT      PINMUX_PA00D_SERCOM1_PAD0
#define SERCOM1_PAD1_DEFAULT      PINMUX_PA01D_SERCOM1_PAD1
#define SERCOM1_PAD2_DEFAULT      PINMUX_PA30D_SERCOM1_PAD2
#define SERCOM1_PAD3_DEFAULT      PINMUX_PA31D_SERCOM1_PAD3

/* SERCOM2 */
#define SERCOM2_PAD0_DEFAULT      PINMUX_PA08D_SERCOM2_PAD0
#define SERCOM2_PAD1_DEFAULT      PINMUX_PA09D_SERCOM2_PAD1
#define SERCOM2_PAD2_DEFAULT      PINMUX_PA10D_SERCOM2_PAD2
#define SERCOM2_PAD3_DEFAULT      PINMUX_PA11D_SERCOM2_PAD3

/* SERCOM3 */
#define SERCOM3_PAD0_DEFAULT      PINMUX_PA16D_SERCOM3_PAD0
#define SERCOM3_PAD1_DEFAULT      PINMUX_PA17D_SERCOM3_PAD1
#define SERCOM3_PAD2_DEFAULT      PINMUX_PA18D_SERCOM3_PAD2
#define SERCOM3_PAD3_DEFAULT      PINMUX_PA19D_SERCOM3_PAD3

/* SERCOM4 */
#define SERCOM4_PAD0_DEFAULT      PINMUX_PA12D_SERCOM4_PAD0
#define SERCOM4_PAD1_DEFAULT      PINMUX_PA13D_SERCOM4_PAD1
#define SERCOM4_PAD2_DEFAULT      PINMUX_PA14D_SERCOM4_PAD2
#define SERCOM4_PAD3_DEFAULT      PINMUX_PA15D_SERCOM4_PAD3

/* SERCOM5 */
#define SERCOM5_PAD0_DEFAULT      PINMUX_PA22D_SERCOM5_PAD0
#define SERCOM5_PAD1_DEFAULT      PINMUX_PA23D_SERCOM5_PAD1
#define SERCOM5_PAD2_DEFAULT      PINMUX_PA24D_SERCOM5_PAD2
#define SERCOM5_PAD3_DEFAULT      PINMUX_PA25D_SERCOM5_PAD3
#endif

#endif /* SERCOM_PINOUT_H_INCLUDED */
