include ../makefile_defines.txt

COMPONENT_NAME = sn_coap_builder_unit
SRC_FILES = \
        ../../../../source/libCoap/src/sn_coap_builder.c

TEST_SRC_FILES = \
        main.cpp \
        libCoap_builder_test.cpp \
        ../stubs/sn_coap_header_check_stub.c \
        ../stubs/sn_coap_parser_stub.c \

include ../MakefileWorker.mk



