#!/bin/bash
echo
echo Build Coap-service unit tests
echo

# Remember to add new test folder to Makefile
make clean
make all

echo
echo Create results
echo
mkdir results
find ./ -name '*.xml' | xargs cp -t ./results/

echo
echo Create coverage document
echo
mkdir coverages
cd coverages

lcov -q -d ../. -c -o app.info
lcov -q -r app.info "/test*" -o app.info
lcov -q -r app.info "/usr*" -o app.info
lcov -q -r app.info "/libService*" -o app.info
lcov -q -r app.info "/yotta_modules*" -o app.info
genhtml -q --no-branch-coverage app.info
cd ..
echo
echo
echo
echo Have a nice bug hunt!
echo
echo
echo
