; 
; Copyright (C) u-blox
; All rights reserved.
; This source file is the sole property of u-blox. Reproduction or utilization
; of this source in whole or part is forbidden without the written consent of
; u-blox.
; 
; FILE: stm_cr.hs

STM_CR_STIMR EQU 0x000
STM_CR_STIMR_FIELDS EQU 32
STM_CR_DMASTARTR EQU 0xC04
STM_CR_DMASTOPR EQU 0xC08
STM_CR_DMASTATR EQU 0xC0C
STM_CR_DMACTLR EQU 0xC10
STM_CR_DMAIDR EQU 0xCFC
STM_CR_HEER EQU 0xD00
STM_CR_HETER EQU 0xD20
STM_CR_HEMCR EQU 0xD64
STM_CR_HEMASTR EQU 0xDF4
STM_CR_HEFEAT1R EQU 0xDF8
STM_CR_HEIDR EQU 0xDFC
STM_CR_SPER EQU 0xE00
STM_CR_SPTER EQU 0xE20
STM_CR_SPSCR EQU 0xE60
STM_CR_SPMSCR EQU 0xE64
STM_CR_SPOVERRIDER EQU 0xE68
STM_CR_SPMOVERRIDER EQU 0xE6C
STM_CR_SPTRIGCSR EQU 0xE70
STM_CR_TCSR EQU 0xE80
STM_CR_TSSTIMR EQU 0xE84
STM_CR_TSFREQR EQU 0xE8C
STM_CR_SYNCR EQU 0xE90
STM_CR_AUXCR EQU 0xE94
STM_CR_FEAT1R EQU 0xEA0
STM_CR_FEAT2R EQU 0xEA4
STM_CR_FEAT3R EQU 0xEA8
STM_CR_ITTRIGGER EQU 0xEE8
STM_CR_ITATBDATA0 EQU 0xEEC
STM_CR_ITATBCTR2 EQU 0xEF0
STM_CR_ITATBID EQU 0xEF4
STM_CR_ITATBCTR0 EQU 0xEF8
STM_CR_ITCTRL EQU 0xF00
STM_CR_CLAIMSET EQU 0xFA0
STM_CR_CLAIMCLR EQU 0xFA4
STM_CR_LAR EQU 0xFB0
STM_CR_LSR EQU 0xFB4
STM_CR_AUTHSTATUS EQU 0xFB8
STM_CR_DEVID EQU 0xFC8
STM_CR_DEVTYPE EQU 0xFCC
STM_CR_PERIPHERALID4 EQU 0xFD0
STM_CR_PERIPHERALID5 EQU 0xFD4
STM_CR_PERIPHERALID6 EQU 0xFD8
STM_CR_PERIPHERALID7 EQU 0xFDC
STM_CR_PERIPHERALID0 EQU 0xFE0
STM_CR_PERIPHERALID1 EQU 0xFE4
STM_CR_PERIPHERALID2 EQU 0xFE8
STM_CR_PERIPHERALID3 EQU 0xFEC
STM_CR_COMPONENTID0 EQU 0xFF0
STM_CR_COMPONENTID1 EQU 0xFF4
STM_CR_COMPONENTID2 EQU 0xFF8
STM_CR_COMPONENTID3 EQU 0xFFC
; EOF: stm_cr.hs
   END
