/*
 * Copyright (c) 2018-2019, Arm Limited. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */

/*******************************************************************************
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * THIS FILE IS AN AUTO-GENERATED FILE - DO NOT MODIFY IT.
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * Template Version 1.0
 * Generated by tools/psa/generate_partition_code.py Version {{script_ver}}
 ******************************************************************************/

#ifndef __TFM_PARTITION_LIST_INC__
#define __TFM_PARTITION_LIST_INC__

/*************************** Service Partitions *******************************/
{% for partition in service_partitions %}
/* -----------------------------------------------------------------------------
 * {{partition.name|upper}}
 * -------------------------------------------------------------------------- */
PARTITION_DECLARE({{partition.name|upper}}, 0
    | SPM_PART_FLAG_IPC
    , "{{partition.type}}", {{partition.id}}, {{partition.priority_tfm}}, {{partition.stack_size}});
PARTITION_ADD_INIT_FUNC({{partition.name|upper}}, {{partition.entry_point}});

{% endfor %}
/*************************** Test Partitions **********************************/
#ifdef USE_PSA_TEST_PARTITIONS

{% for partition in test_partitions %}
#ifdef USE_{{partition.name|upper}}
/* -----------------------------------------------------------------------------
 * {{partition.name|upper}}
 * -------------------------------------------------------------------------- */
PARTITION_DECLARE({{partition.name|upper}}, 0
    | SPM_PART_FLAG_IPC
    , "{{partition.type}}", {{partition.id}}, {{partition.priority_tfm}}, {{partition.stack_size}});
PARTITION_ADD_INIT_FUNC({{partition.name|upper}}, {{partition.entry_point}});
#endif // USE_{{partition.name|upper}}

{% endfor %}
#endif // USE_PSA_TEST_PARTITIONS

#endif // __TFM_PARTITION_LIST_INC__
{# End of file #}
