; 
; Copyright (C) u-blox
; All rights reserved.
; This source file is the sole property of u-blox. Reproduction or utilization
; of this source in whole or part is forbidden without the written consent of
; u-blox.
; 
; FILE: ar1de_mwu.hs

AR1DE_MWU_NR_REGIONS EQU 4
AR1DE_MWU_MWR_SR EQU 0x000
AR1DE_MWU_MWR_ER EQU 0x004
AR1DE_MWU_MWR_CF EQU 0x008
AR1DE_MWU_MWR_FILL EQU 0x00C
AR1DE_MWU_MWR_FILL_FIELDS EQU 1
AR1DE_MWU_INTMCTRL EQU 0xF00
AR1DE_MWU_CLAIMSET EQU 0xFA0
AR1DE_MWU_CLAIMCLR EQU 0xFA4
AR1DE_MWU_LOCKACCESS EQU 0xFB0
AR1DE_MWU_LOCKSTATUS EQU 0xFB4
AR1DE_MWU_AUTHSTATUS EQU 0xFB8
AR1DE_MWU_DEVCONF EQU 0xFC8
AR1DE_MWU_DEVTYPE EQU 0xFCC
AR1DE_MWU_PERIPHERALID4 EQU 0xFD0
AR1DE_MWU_PERIPHERALID5 EQU 0xFD4
AR1DE_MWU_PERIPHERALID6 EQU 0xFD8
AR1DE_MWU_PERIPHERALID7 EQU 0xFDC
AR1DE_MWU_PERIPHERALID0 EQU 0xFE0
AR1DE_MWU_PERIPHERALID1 EQU 0xFE4
AR1DE_MWU_PERIPHERALID2 EQU 0xFE8
AR1DE_MWU_PERIPHERALID3 EQU 0xFEC
AR1DE_MWU_COMPONENTID0 EQU 0xFF0
AR1DE_MWU_COMPONENTID1 EQU 0xFF4
AR1DE_MWU_COMPONENTID2 EQU 0xFF8
AR1DE_MWU_COMPONENTID3 EQU 0xFFC
; EOF: ar1de_mwu.hs
   END
