; 
; Copyright (C) u-blox
; All rights reserved.
; This source file is the sole property of u-blox. Reproduction or utilization
; of this source in whole or part is forbidden without the written consent of
; u-blox.
; 
; FILE: aux_dig_top.hs

AUX_DIG_TOP_HAL_VERSION EQU 13
AUX_DIG_TOP_PADC_GAIN_CTL EQU 0x000
AUX_DIG_TOP_DCOC_CTL EQU 0x004
AUX_DIG_TOP_DCOC_CORR EQU 0x008
AUX_DIG_TOP_DCOC_EST EQU 0x00C
AUX_DIG_TOP_ADC_IMB_CTRL EQU 0x010
AUX_DIG_TOP_FILTS_CTRL_1 EQU 0x014
AUX_DIG_TOP_AUX_STATUS EQU 0x018
AUX_DIG_TOP_DCOC_CTL_NB EQU 0x01C
AUX_DIG_TOP_DCOC_CORR_NB EQU 0x020
AUX_DIG_TOP_DCOC_EST_NB EQU 0x024
AUX_DIG_TOP_AUX_PWR_CTRL EQU 0x028
AUX_DIG_TOP_AUX_PWR EQU 0x02C
AUX_DIG_TOP_AUX_ADC_SAMPLE EQU 0x030
AUX_DIG_TOP_AUX_DFE_CTRL EQU 0x034
AUX_DIG_TOP_ADC_TMODE EQU 0x038
AUX_DIG_TOP_AUX_DFE_RESET EQU 0x03C
AUX_DIG_TOP_ADCI1 EQU 0x040
AUX_DIG_TOP_ADCI2 EQU 0x044
AUX_DIG_TOP_ADC_CONV EQU 0x048
AUX_DIG_TOP_ADC_CAL_FLAG_EN EQU 0x04C
; EOF: aux_dig_top.hs
   END
