; 
; Copyright (C) u-blox
; All rights reserved.
; This source file is the sole property of u-blox. Reproduction or utilization
; of this source in whole or part is forbidden without the written consent of
; u-blox.
; 
; FILE: cortex_m3_itm.hs

CORTEX_M3_ITM_ITM_STIM EQU 0x000
CORTEX_M3_ITM_ITM_STIM_FIELDS EQU 32
CORTEX_M3_ITM_ITM_TER EQU 0xE00
CORTEX_M3_ITM_ITM_TPR EQU 0xE40
CORTEX_M3_ITM_ITM_TCR EQU 0xE80
CORTEX_M3_ITM_ITM_IWR EQU 0xEF8
CORTEX_M3_ITM_ITM_IMCR EQU 0xF00
CORTEX_M3_ITM_ITM_LAR EQU 0xFB0
CORTEX_M3_ITM_ITM_LSR EQU 0xFB4
CORTEX_M3_ITM_PID4 EQU 0xFD0
CORTEX_M3_ITM_PID5 EQU 0xFD4
CORTEX_M3_ITM_PID6 EQU 0xFD8
CORTEX_M3_ITM_PID7 EQU 0xFDC
CORTEX_M3_ITM_PID0 EQU 0xFE0
CORTEX_M3_ITM_PID1 EQU 0xFE4
CORTEX_M3_ITM_PID2 EQU 0xFE8
CORTEX_M3_ITM_PID3 EQU 0xFEC
CORTEX_M3_ITM_CID0 EQU 0xFF0
CORTEX_M3_ITM_CID1 EQU 0xFF4
CORTEX_M3_ITM_CID2 EQU 0xFF8
CORTEX_M3_ITM_CID3 EQU 0xFFC
; EOF: cortex_m3_itm.hs
   END
