; 
; Copyright (C) u-blox
; All rights reserved.
; This source file is the sole property of u-blox. Reproduction or utilization
; of this source in whole or part is forbidden without the written consent of
; u-blox.
; 
; FILE: cti.hs

CTI_CTICONTROL EQU 0x000
CTI_CTIINTACK EQU 0x010
CTI_CTIAPPSET EQU 0x014
CTI_CTIAPPCLEAR EQU 0x018
CTI_CTIAPPPULSE EQU 0x01C
CTI_CTIINEN EQU 0x020
CTI_CTIINEN_FIELDS EQU 8
CTI_CTIOUTEN EQU 0x0A0
CTI_CTIOUTEN_FIELDS EQU 8
CTI_CTITRIGINSTATUS EQU 0x130
CTI_CTITRIGOUTSTATUS EQU 0x134
CTI_CTICHINSTATUS EQU 0x138
CTI_CTICHOUTSTATUS EQU 0x13C
CTI_CTIGATE EQU 0x140
CTI_ASICCTL EQU 0x144
CTI_ITCHINACK EQU 0xEDC
CTI_ITTRIGINACK EQU 0xEE0
CTI_ITCHOUT EQU 0xEE4
CTI_ITTRIGOUT EQU 0xEE8
CTI_ITCHOUTACK EQU 0xEEC
CTI_ITTRIGOUTACK EQU 0xEF0
CTI_ITCHIN EQU 0xEF4
CTI_ITTRIGIN EQU 0xEF8
CTI_ITCTRL EQU 0xF00
CTI_CLAIMSET EQU 0xFA0
CTI_CLAIMCLR EQU 0xFA4
CTI_LOCKACCESS EQU 0xFB0
CTI_LOCKSTATUS EQU 0xFB4
CTI_AUTHSTATUS EQU 0xFB8
CTI_DEVID EQU 0xFC8
CTI_DEVTYPE EQU 0xFCC
CTI_PERIPHERALID4 EQU 0xFD0
CTI_PERIPHERALID0 EQU 0xFE0
CTI_PERIPHERALID1 EQU 0xFE4
CTI_PERIPHERALID2 EQU 0xFE8
CTI_PERIPHERALID3 EQU 0xFEC
CTI_COMPONENTID0 EQU 0xFF0
CTI_COMPONENTID1 EQU 0xFF4
CTI_COMPONENTID2 EQU 0xFF8
CTI_COMPONENTID3 EQU 0xFFC
; EOF: cti.hs
   END
