; 
; Copyright (C) u-blox
; All rights reserved.
; This source file is the sole property of u-blox. Reproduction or utilization
; of this source in whole or part is forbidden without the written consent of
; u-blox.
; 
; FILE: cxatbreplicator.hs

CXATBREPLICATOR_IDFILTER0 EQU 0x000
CXATBREPLICATOR_IDFILTER1 EQU 0x004
CXATBREPLICATOR_ITATBCTR1 EQU 0xEF8
CXATBREPLICATOR_ITATBCTR0 EQU 0xEFC
CXATBREPLICATOR_ITCTRL EQU 0xF00
CXATBREPLICATOR_CLAIMSET EQU 0xFA0
CXATBREPLICATOR_CLAIMCLR EQU 0xFA4
CXATBREPLICATOR_LOCKACCESS EQU 0xFB0
CXATBREPLICATOR_LOCKSTATUS EQU 0xFB4
CXATBREPLICATOR_AUTHSTATUS EQU 0xFB8
CXATBREPLICATOR_DEVID EQU 0xFC8
CXATBREPLICATOR_DEVTYPE EQU 0xFCC
CXATBREPLICATOR_PERIPHERALID4 EQU 0xFD0
CXATBREPLICATOR_PERIPHERALID0 EQU 0xFE0
CXATBREPLICATOR_PERIPHERALID1 EQU 0xFE4
CXATBREPLICATOR_PERIPHERALID2 EQU 0xFE8
CXATBREPLICATOR_PERIPHERALID3 EQU 0xFEC
CXATBREPLICATOR_COMPONENTID0 EQU 0xFF0
CXATBREPLICATOR_COMPONENTID1 EQU 0xFF4
CXATBREPLICATOR_COMPONENTID2 EQU 0xFF8
CXATBREPLICATOR_COMPONENTID3 EQU 0xFFC
; EOF: cxatbreplicator.hs
   END
