; 
; Copyright (C) u-blox
; All rights reserved.
; This source file is the sole property of u-blox. Reproduction or utilization
; of this source in whole or part is forbidden without the written consent of
; u-blox.
; 
; FILE: cxatbfunnel.hs

CXATBFUNNEL_CSTFCTRL EQU 0x000
CXATBFUNNEL_CSTFPRIO EQU 0x004
CXATBFUNNEL_ITATBDATA0 EQU 0xEEC
CXATBFUNNEL_ITATBCTR2 EQU 0xEF0
CXATBFUNNEL_ITATBCTR1 EQU 0xEF4
CXATBFUNNEL_ITATBCTR0 EQU 0xEF8
CXATBFUNNEL_ITMCTRL EQU 0xF00
CXATBFUNNEL_CLAIMSET EQU 0xFA0
CXATBFUNNEL_CLAIMCLR EQU 0xFA4
CXATBFUNNEL_LOCKACCESS EQU 0xFB0
CXATBFUNNEL_LOCKSTATUS EQU 0xFB4
CXATBFUNNEL_AUTHSTATUS EQU 0xFB8
CXATBFUNNEL_DEVID EQU 0xFC8
CXATBFUNNEL_DEVTYPE EQU 0xFCC
CXATBFUNNEL_PERIPHERALID4 EQU 0xFD0
CXATBFUNNEL_PERIPHERALID5 EQU 0xFD4
CXATBFUNNEL_PERIPHERALID6 EQU 0xFD8
CXATBFUNNEL_PERIPHERALID7 EQU 0xFDC
CXATBFUNNEL_PERIPHERALID0 EQU 0xFE0
CXATBFUNNEL_PERIPHERALID1 EQU 0xFE4
CXATBFUNNEL_PERIPHERALID2 EQU 0xFE8
CXATBFUNNEL_PERIPHERALID3 EQU 0xFEC
CXATBFUNNEL_COMPONENTID0 EQU 0xFF0
CXATBFUNNEL_COMPONENTID1 EQU 0xFF4
CXATBFUNNEL_COMPONENTID2 EQU 0xFF8
CXATBFUNNEL_COMPONENTID3 EQU 0xFFC
; EOF: cxatbfunnel.hs
   END
