; 
; Copyright (C) u-blox
; All rights reserved.
; This source file is the sole property of u-blox. Reproduction or utilization
; of this source in whole or part is forbidden without the written consent of
; u-blox.
; 
; FILE: cxtsgen.hs

CXTSGEN_CNTCR EQU 0x000
CXTSGEN_CNTSR EQU 0x004
CXTSGEN_CNTCVLW EQU 0x008
CXTSGEN_CNTCVUP EQU 0x00C
CXTSGEN_CNTFID0 EQU 0x020
CXTSGEN_PERIPHERALID4 EQU 0xFD0
CXTSGEN_PERIPHERALID0 EQU 0xFE0
CXTSGEN_PERIPHERALID1 EQU 0xFE4
CXTSGEN_PERIPHERALID2 EQU 0xFE8
CXTSGEN_PERIPHERALID3 EQU 0xFEC
CXTSGEN_COMPONENTID0 EQU 0xFF0
CXTSGEN_COMPONENTID1 EQU 0xFF4
CXTSGEN_COMPONENTID2 EQU 0xFF8
CXTSGEN_COMPONENTID3 EQU 0xFFC
; EOF: cxtsgen.hs
   END
