; 
; Copyright (C) u-blox
; All rights reserved.
; This source file is the sole property of u-blox. Reproduction or utilization
; of this source in whole or part is forbidden without the written consent of
; u-blox.
; 
; FILE: display_top.hs

DISPLAY_TOP_HAL_VERSION EQU 1
DISPLAY_TOP_FIFOWRCS0A0 EQU 0x000
DISPLAY_TOP_FIFOWRCS0A1 EQU 0x004
DISPLAY_TOP_FIFOWRCS1A0 EQU 0x008
DISPLAY_TOP_FIFOWRCS1A1 EQU 0x00C
DISPLAY_TOP_DISPLAYCFG EQU 0x010
DISPLAY_TOP_READCFG EQU 0x014
DISPLAY_TOP_READDATAVALID EQU 0x018
DISPLAY_TOP_READDATAREG EQU 0x01C
DISPLAY_TOP_SERIALENGINECFG EQU 0x020
DISPLAY_TOP_STARTDMAWR EQU 0x024
DISPLAY_TOP_DMACFG EQU 0x028
DISPLAY_TOP_NUMBEROFPACKETS EQU 0x02C
DISPLAY_TOP_TIMINGCONTROLREG1 EQU 0x030
DISPLAY_TOP_TIMINGCONTROLREG2 EQU 0x034
DISPLAY_TOP_POLARITYREG EQU 0x038
DISPLAY_TOP_DISPLAYSTATUSREG EQU 0x03C
; EOF: display_top.hs
   END
