; 
; Copyright (C) u-blox
; All rights reserved.
; This source file is the sole property of u-blox. Reproduction or utilization
; of this source in whole or part is forbidden without the written consent of
; u-blox.
; 
; FILE: dl_bpe.hs

DL_BPE_PENDING_API_LADDR EQU 0x000
DL_BPE_PENDING_API_HC_ADDR EQU 0x004
DL_BPE_PENDING_API_DADDR EQU 0x008
DL_BPE_PENDING_API_RESULT_ADDR_RESULT0 EQU 0x000
DL_BPE_PENDING_API_RESULT_ADDR_RESULT1 EQU 0x004
DL_BPE_PENDING_API_RES_ADDR EQU 0x00C
DL_BPE_PENDING_API_PARSET0 EQU 0x010
DL_BPE_PENDING_API_PARSET1 EQU 0x014
DL_BPE_PENDING_API_PARSET2 EQU 0x018
DL_BPE_PENDING_API_HC_CONTEXT EQU 0x01C
DL_BPE_PENDING_DESCRIPTOR_ADDRESS EQU 0x000
DL_BPE_RUNNING_DESCRIPTOR_ADDRESS EQU 0x100
DL_BPE_CMD EQU 0x200
DL_BPE_STAT EQU 0x204
DL_BPE_FLTCLEAR EQU 0x300
DL_BPE_FLTSTATUS EQU 0x304
DL_BPE_FLTRAWSTATUS EQU 0x308
DL_BPE_FLTMASKCLR EQU 0x30C
DL_BPE_FLTMASKSET EQU 0x310
DL_BPE_FLTMASKSTATUS EQU 0x314
DL_BPE_PERIPHERALID4 EQU 0xFD0
DL_BPE_PERIPHERALID5 EQU 0xFD4
DL_BPE_PERIPHERALID6 EQU 0xFD8
DL_BPE_PERIPHERALID7 EQU 0xFDC
DL_BPE_PERIPHERALID0 EQU 0xFE0
DL_BPE_PERIPHERALID1 EQU 0xFE4
DL_BPE_PERIPHERALID2 EQU 0xFE8
DL_BPE_PERIPHERALID3 EQU 0xFEC
DL_BPE_COMPONENTID0 EQU 0xFF0
DL_BPE_COMPONENTID1 EQU 0xFF4
DL_BPE_COMPONENTID2 EQU 0xFF8
DL_BPE_COMPONENTID3 EQU 0xFFC
; EOF: dl_bpe.hs
   END
