; 
; Copyright (C) u-blox
; All rights reserved.
; This source file is the sole property of u-blox. Reproduction or utilization
; of this source in whole or part is forbidden without the written consent of
; u-blox.
; 
; FILE: etr_limiter.hs

ETR_LIMITER_CTRL EQU 0x000
ETR_LIMITER_READ_POINTER EQU 0x004
ETR_LIMITER_WRITE_POINTER EQU 0x008
ETR_LIMITER_BUFFERDEPTH_LOG2 EQU 0x00C
ETR_LIMITER_THRESHOLD_LOG2 EQU 0x010
ETR_LIMITER_THRESHOLD_COUNTER EQU 0x014
ETR_LIMITER_EVENTCLR EQU 0x300
ETR_LIMITER_EVENTSTAT EQU 0x304
ETR_LIMITER_EVENTRAW EQU 0x308
ETR_LIMITER_EVENTENABLESET EQU 0x30C
ETR_LIMITER_EVENTENABLECLR EQU 0x310
ETR_LIMITER_PERIPHERALID4 EQU 0xFD0
ETR_LIMITER_PERIPHERALID5 EQU 0xFD4
ETR_LIMITER_PERIPHERALID6 EQU 0xFD8
ETR_LIMITER_PERIPHERALID7 EQU 0xFDC
ETR_LIMITER_PERIPHERALID0 EQU 0xFE0
ETR_LIMITER_PERIPHERALID1 EQU 0xFE4
ETR_LIMITER_PERIPHERALID2 EQU 0xFE8
ETR_LIMITER_PERIPHERALID3 EQU 0xFEC
ETR_LIMITER_COMPONENTID0 EQU 0xFF0
ETR_LIMITER_COMPONENTID1 EQU 0xFF4
ETR_LIMITER_COMPONENTID2 EQU 0xFF8
ETR_LIMITER_COMPONENTID3 EQU 0xFFC
; EOF: etr_limiter.hs
   END
