#ifndef INCLUDED_HAL_MEMORY_DEFS
#define INCLUDED_HAL_MEMORY_DEFS
/*
 * Copyright (C) u-blox 
 * All rights reserved. 
 * This source file is the sole property of u-blox. Reproduction or utilization 
 * of this source in whole or part is forbidden without the written consent of 
 * u-blox.
 *
 */

#ifndef APP_DTCM_SIZE
#define APP_DTCM_SIZE 65536
#endif

#ifndef APP_ITCM_SIZE
#define APP_ITCM_SIZE 65536
#endif

#ifndef BOOT_ROM_SIZE
#define BOOT_ROM_SIZE 65536
#endif

#ifndef APP_PERIPH_RAM_SIZE
#define APP_PERIPH_RAM_SIZE 32768
#endif

#ifndef PSRAM_EXT_RAM_SIZE
#define PSRAM_EXT_RAM_SIZE 16777216
#endif

#ifndef OSPI_EXT_RAM_SIZE
#define OSPI_EXT_RAM_SIZE 134217728
#endif

#ifndef MDM_DTCM_SIZE
#define MDM_DTCM_SIZE 65536
#endif

#ifndef MDM_ITCM_SIZE
#define MDM_ITCM_SIZE 65536
#endif

#ifndef PHY_TCM_SIZE
#define PHY_TCM_SIZE 131072
#endif

#ifndef ARDES_NRDE_1_DMEM_SIZE
#define ARDES_NRDE_1_DMEM_SIZE 524288
#endif

#ifndef AR1DE_I256_D64_DTCM_SIZE
#define AR1DE_I256_D64_DTCM_SIZE 65536
#endif

#ifndef AR1DE_I256_D64_ITCM_SIZE
#define AR1DE_I256_D64_ITCM_SIZE 262144
#endif

#ifndef RF_TCM_SIZE
#define RF_TCM_SIZE 65536
#endif

#ifndef RF_SYSRAM_BANKS
#define RF_SYSRAM_BANKS 2
#endif

#ifndef RF_SYSRAM_SIZE
#define RF_SYSRAM_SIZE 32768
#endif

#ifndef RF_RX_SCR
#define RF_RX_SCR 16384
#endif

#ifndef RF_TX_SCR
#define RF_TX_SCR 16384
#endif

#define APP_SS_MEM_APP_CPU_TCM_DTCM_BASE 0x20000000
#define APP_SS_MEM_APP_CPU_TCM_DTCM_SIZE APP_DTCM_SIZE

#define APP_SS_MEM_APP_CPU_TCM_DTCM_ALIAS_BASE 0x38000000
#define APP_SS_MEM_APP_CPU_TCM_DTCM_ALIAS_SIZE APP_DTCM_SIZE

#define APP_SS_MEM_APP_CPU_TCM_ITCM_BASE 0x0
#define APP_SS_MEM_APP_CPU_TCM_ITCM_SIZE APP_ITCM_SIZE

#define APP_SS_MEM_APP_CPU_TCM_ITCM_ALIAS_BASE 0x37000000
#define APP_SS_MEM_APP_CPU_TCM_ITCM_ALIAS_SIZE APP_ITCM_SIZE

#define APP_SS_MEM_BOOT_ROM_BOOT_ROM_BASE 0x10000000
#define APP_SS_MEM_BOOT_ROM_BOOT_ROM_SIZE BOOT_ROM_SIZE

#define APP_SS_MEM_APP_PERIPH_RAM_PERIPH_RAM_BASE 0x36000000
#define APP_SS_MEM_APP_PERIPH_RAM_PERIPH_RAM_SIZE APP_PERIPH_RAM_SIZE

#define APP_SS_MEM_PSRAM_EXT_MEM_PERIPH_RAM_BASE 0x60000000
#define APP_SS_MEM_PSRAM_EXT_MEM_PERIPH_RAM_SIZE PSRAM_EXT_RAM_SIZE

#define APP_SS_MEM_OSPI_EXT_MEM_PERIPH_RAM_BASE 0x70000000
#define APP_SS_MEM_OSPI_EXT_MEM_PERIPH_RAM_SIZE OSPI_EXT_RAM_SIZE

#define BB_MODEM_SS_MEM_MDM_CPU_DTCM_BASE 0x20000000
#define BB_MODEM_SS_MEM_MDM_CPU_DTCM_SIZE MDM_DTCM_SIZE

#define BB_MODEM_SS_MEM_MDM_CPU_DTCM_ALIAS_BASE 0x24100000
#define BB_MODEM_SS_MEM_MDM_CPU_DTCM_ALIAS_SIZE MDM_DTCM_SIZE

#define BB_MODEM_SS_MEM_MDM_CPU_ITCM_BASE 0x0
#define BB_MODEM_SS_MEM_MDM_CPU_ITCM_SIZE MDM_ITCM_SIZE

#define BB_MODEM_SS_MEM_MDM_CPU_ITCM_ALIAS_BASE 0x24000000
#define BB_MODEM_SS_MEM_MDM_CPU_ITCM_ALIAS_SIZE MDM_ITCM_SIZE

#define BB_MODEM_SS_MEM_PHY_CPU_TCM_BASE 0x0
#define BB_MODEM_SS_MEM_PHY_CPU_TCM_SIZE PHY_TCM_SIZE

#define BB_MODEM_SS_MEM_PHY_CPU_TCM_ALIAS_BASE 0x22000000
#define BB_MODEM_SS_MEM_PHY_CPU_TCM_ALIAS_SIZE PHY_TCM_SIZE

#define BB_MODEM_SS_MEM_VSP0_DMEM_BASE 0x25000000
#define BB_MODEM_SS_MEM_VSP0_DMEM_SIZE ARDES_NRDE_1_DMEM_SIZE

#define BB_MODEM_SS_MEM_VSP0_DE0_DTCM_BASE 0x25400000
#define BB_MODEM_SS_MEM_VSP0_DE0_DTCM_SIZE AR1DE_I256_D64_DTCM_SIZE

#define BB_MODEM_SS_MEM_VSP0_DE0_ITCM_BASE 0x25500000
#define BB_MODEM_SS_MEM_VSP0_DE0_ITCM_SIZE AR1DE_I256_D64_ITCM_SIZE

#define RF_DIG_SS_MEM_RF_CPU_TCM_BASE 0x0
#define RF_DIG_SS_MEM_RF_CPU_TCM_SIZE RF_TCM_SIZE

#define RF_DIG_SS_MEM_RF_SYSRAM_BASE 0x20000000
#define RF_DIG_SS_MEM_RF_SYSRAM_SIZE RF_SYSRAM_SIZE

#define RF_DIG_SS_MEM_RF_SYSRAM_ALIAS_BASE 0x30000000
#define RF_DIG_SS_MEM_RF_SYSRAM_ALIAS_SIZE RF_SYSRAM_SIZE

#define RF_DIG_SS_MEM_RF_CPU_TCM_ALIAS_BASE 0x31000000
#define RF_DIG_SS_MEM_RF_CPU_TCM_ALIAS_SIZE RF_TCM_SIZE

#define RF_DIG_SS_MEM_RF_RX_SCR_BASE 0x32000000
#define RF_DIG_SS_MEM_RF_RX_SCR_SIZE RF_RX_SCR

#define RF_DIG_SS_MEM_RF_TX_SCR_BASE 0x33000000
#define RF_DIG_SS_MEM_RF_TX_SCR_SIZE RF_TX_SCR

/* EOF hal_memory_defs.h */
#endif
