#ifndef INCLUDED_HWSEQUENCER_DBG
#define INCLUDED_HWSEQUENCER_DBG
/*
 * Copyright (C) u-blox 
 * All rights reserved. 
 * This source file is the sole property of u-blox. Reproduction or utilization 
 * of this source in whole or part is forbidden without the written consent of 
 * u-blox.
 *
 */

#include <stdint.h>

#define HWSEQUENCER_DBG_SEQDBGPERIPHID4 0x07
#define HWSEQUENCER_DBG_SEQDBGPERIPHID5 0x00
#define HWSEQUENCER_DBG_SEQDBGPERIPHID6 0x00
#define HWSEQUENCER_DBG_SEQDBGPERIPHID7 0x00
#define HWSEQUENCER_DBG_SEQDBGPERIPHID0 0x61
#define HWSEQUENCER_DBG_SEQDBGPERIPHID1 0xDA
#define HWSEQUENCER_DBG_SEQDBGPERIPHID2 0x08
#define HWSEQUENCER_DBG_SEQDBGPERIPHID3 0x00
#define HWSEQUENCER_DBG_SEQDBGCOMPID0 0x0D
#define HWSEQUENCER_DBG_SEQDBGCOMPID1 0x90
#define HWSEQUENCER_DBG_SEQDBGCOMPID2 0x05
#define HWSEQUENCER_DBG_SEQDBGCOMPID3 0xB1

/** Hardware Sequencer DBG
*/
struct hwsequencer_dbg_s {
   /** debug status register at address offset 0x000, read-only */
   uint32_t seqdbgstatus;
   /** Sequence Pointer at address offset 0x004, read-only */
   uint32_t seqdbgseqptr;
   /** Sequence ID at address offset 0x008, read-only */
   uint32_t seqdbgseqid;
   /** Break Status at address offset 0x00C, read-write */
   uint32_t seqdbgbrkstate;
   /** Breakpoint Status at address offset 0x010, read-only */
   uint32_t seqdbgbkptstate;
   /** Breakpoint Enable Set at address offset 0x014, read-write */
   uint32_t seqdbgbkptenset;
   /** Breakpoint Enable Clear at address offset 0x018, read-write */
   uint32_t seqdbgbkptenclr;
   /** Reserved space */
   uint8_t fill0[228];
   /** Breakpoint 0 at address offset 0x100, read-write */
   uint32_t seqdbgbkpt0;
   /** Breakpoint 1 at address offset 0x104, read-write */
   uint32_t seqdbgbkpt1;
   /** Reserved space */
   uint8_t fill1[248];
   /** Trace Enable Set at address offset 0x200, read-write */
   uint32_t seqdbgtrcenset;
   /** Trace Enable Clear at address offset 0x204, read-write */
   uint32_t seqdbgtrcenclr;
   /** STM Base Address Register at address offset 0x208, read-write */
   uint32_t seqdbgstmbase;
   /** Pointer ogfset for sequence instruction trace at address offset 0x20C, read-write */
   uint32_t seqdbgptrtrcoff;
   /** Pointer offset for sequence identification trace at address offset 0x210, read-write */
   uint32_t seqdbgidtrcoff;
   /** Pointer offset for barrier trace at address offset 0x214, read-write */
   uint32_t seqdbgbartrcoff;
   /** Reserved space */
   uint8_t fill2[232];
   /** Fault raw status at address offset 0x300, read-only */
   uint32_t seqdbgfltraw;
   /** Fault status (raws status masked with the enable register) at address offset 0x304, read-only */
   uint32_t seqdbgfltstat;
   /** Fault clear at address offset 0x308, write-only */
   uint32_t seqdbgfltclr;
   /** Fault Enable Set at address offset 0x30C, read-write */
   uint32_t seqdbgfltenset;
   /** Fault Enable Clear at address offset 0x310, read-write */
   uint32_t seqdbgfltenclr;
   /** Reserved space */
   uint8_t fill3[3228];
   /** Lock Access Register at address offset 0xFB0, write-only */
   uint32_t seqdbglar;
   /** Lock Status Register at address offset 0xFB4, read-only */
   uint32_t seqdbglsr;
   /** Authentication Status Register at address offset 0xFB8, read-only */
   uint32_t seqdbgauthstatus;
   /** Reserved space */
   uint8_t fill4[12];
   /** Device Configuration Register at address offset 0xFC8, read-only */
   uint32_t seqdbgdevid;
   /** Device Type at address offset 0xFCC, read-only */
   uint32_t seqdbgdevtype;
   /** Peripheral ID4 Register at address offset 0xFD0, read-only constant 0x00000007 */
   uint32_t seqdbgperiphid4;
   /** Peripheral ID5 Register at address offset 0xFD4, read-only constant 0x00000000 */
   uint32_t seqdbgperiphid5;
   /** Peripheral ID6 Register at address offset 0xFD8, read-only constant 0x00000000 */
   uint32_t seqdbgperiphid6;
   /** Peripheral ID7 Register at address offset 0xFDC, read-only constant 0x00000000 */
   uint32_t seqdbgperiphid7;
   /** Peripheral ID0 Register at address offset 0xFE0, read-only constant 0x00000061 */
   uint32_t seqdbgperiphid0;
   /** Peripheral ID1 Register at address offset 0xFE4, read-only constant 0x000000DA */
   uint32_t seqdbgperiphid1;
   /** Peripheral ID2 Register at address offset 0xFE8, read-only constant 0x00000008 */
   uint32_t seqdbgperiphid2;
   /** Peripheral ID3 Register at address offset 0xFEC, read-only constant 0x00000000 */
   uint32_t seqdbgperiphid3;
   /** Primecell ID register 0 at address offset 0xFF0, read-only constant 0x0000000D */
   uint32_t seqdbgcompid0;
   /** Primecell ID register 1 at address offset 0xFF4, read-only constant 0x00000090 */
   uint32_t seqdbgcompid1;
   /** Primecell ID register 2 at address offset 0xFF8, read-only constant 0x00000005 */
   uint32_t seqdbgcompid2;
   /** Primecell ID register 3 at address offset 0xFFC, read-only constant 0x000000B1 */
   uint32_t seqdbgcompid3;
};

/** bit field defines for hwsequencer_dbg_s#seqdbgstatus */
#define HWSEQUENCER_DBG_SEQDBGSTATUS_TASK_END_FIFO_NOT_EMPTY_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGSTATUS_TASK_END_FIFO_NOT_EMPTY_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGSTATUS_TASK_END_FIFO_PENDING_OFFSET 1
#define HWSEQUENCER_DBG_SEQDBGSTATUS_TASK_END_FIFO_PENDING_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGSTATUS_READY_FIFO_NOT_EMPTY_OFFSET 2
#define HWSEQUENCER_DBG_SEQDBGSTATUS_READY_FIFO_NOT_EMPTY_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGSTATUS_READY_FIFO_FULL_OFFSET 3
#define HWSEQUENCER_DBG_SEQDBGSTATUS_READY_FIFO_FULL_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGSTATUS_PREFETCH_NOT_EMPTY_OFFSET 4
#define HWSEQUENCER_DBG_SEQDBGSTATUS_PREFETCH_NOT_EMPTY_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGSTATUS_PREFETCH_FULL_OFFSET 5
#define HWSEQUENCER_DBG_SEQDBGSTATUS_PREFETCH_FULL_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGSTATUS_PREFETCH_AXI_OFFSET 6
#define HWSEQUENCER_DBG_SEQDBGSTATUS_PREFETCH_AXI_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGSTATUS_FETCH_AXI_OFFSET 7
#define HWSEQUENCER_DBG_SEQDBGSTATUS_FETCH_AXI_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGSTATUS_SEQINSTR_FIFO_NOT_EMPTY_OFFSET 8
#define HWSEQUENCER_DBG_SEQDBGSTATUS_SEQINSTR_FIFO_NOT_EMPTY_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGSTATUS_SEQINSTR_FIFO_FULL_OFFSET 9
#define HWSEQUENCER_DBG_SEQDBGSTATUS_SEQINSTR_FIFO_FULL_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGSTATUS_WRITEBUFFER_NOT_EMPTY_OFFSET 10
#define HWSEQUENCER_DBG_SEQDBGSTATUS_WRITEBUFFER_NOT_EMPTY_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGSTATUS_WRITEBUFFER_FULL_OFFSET 11
#define HWSEQUENCER_DBG_SEQDBGSTATUS_WRITEBUFFER_FULL_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGSTATUS_WRITEBUFFER_AXI_OFFSET 12
#define HWSEQUENCER_DBG_SEQDBGSTATUS_WRITEBUFFER_AXI_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGSTATUS_BARRIER_FIFO_EMPTY_OFFSET 13
#define HWSEQUENCER_DBG_SEQDBGSTATUS_BARRIER_FIFO_EMPTY_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGSTATUS_BARRIER_FIFO_FULL_OFFSET 14
#define HWSEQUENCER_DBG_SEQDBGSTATUS_BARRIER_FIFO_FULL_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGSTATUS_BARRIER_CACHE_DIRTY_OFFSET 15
#define HWSEQUENCER_DBG_SEQDBGSTATUS_BARRIER_CACHE_DIRTY_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGSTATUS_BARRIER_CACHE_AXI_OFFSET 16
#define HWSEQUENCER_DBG_SEQDBGSTATUS_BARRIER_CACHE_AXI_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGSTATUS_BRANCH_FIFIO_NOT_EMPTY_OFFSET 17
#define HWSEQUENCER_DBG_SEQDBGSTATUS_BRANCH_FIFIO_NOT_EMPTY_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGSTATUS_BRANCH_FIFO_FULL_OFFSET 18
#define HWSEQUENCER_DBG_SEQDBGSTATUS_BRANCH_FIFO_FULL_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGSTATUS_BRANCH_UNIT_BUSY_OFFSET 19
#define HWSEQUENCER_DBG_SEQDBGSTATUS_BRANCH_UNIT_BUSY_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGSTATUS_BREAKPOINT_OFFSET 20
#define HWSEQUENCER_DBG_SEQDBGSTATUS_BREAKPOINT_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGSTATUS_BREAKXCPT_OFFSET 21
#define HWSEQUENCER_DBG_SEQDBGSTATUS_BREAKXCPT_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGSTATUS_BREAKCTI_OFFSET 22
#define HWSEQUENCER_DBG_SEQDBGSTATUS_BREAKCTI_SIZE 1

/** bit field defines for hwsequencer_dbg_s#seqdbgseqptr */
#define HWSEQUENCER_DBG_SEQDBGSEQPTR_SEQUENCE_POINTER_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGSEQPTR_SEQUENCE_POINTER_SIZE 16
#define HWSEQUENCER_DBG_SEQDBGSEQPTR_VALID_OFFSET 16
#define HWSEQUENCER_DBG_SEQDBGSEQPTR_VALID_SIZE 1

/** bit field defines for hwsequencer_dbg_s#seqdbgseqid */
#define HWSEQUENCER_DBG_SEQDBGSEQID_SEQUENCE_ID_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGSEQID_SEQUENCE_ID_SIZE 16
#define HWSEQUENCER_DBG_SEQDBGSEQID_VALID_OFFSET 16
#define HWSEQUENCER_DBG_SEQDBGSEQID_VALID_SIZE 1

/** bit field defines for hwsequencer_dbg_s#seqdbgbrkstate */
#define HWSEQUENCER_DBG_SEQDBGBRKSTATE_STOP_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGBRKSTATE_STOP_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGBRKSTATE_STEP_OFFSET 1
#define HWSEQUENCER_DBG_SEQDBGBRKSTATE_STEP_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGBRKSTATE_BKPT_OFFSET 2
#define HWSEQUENCER_DBG_SEQDBGBRKSTATE_BKPT_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGBRKSTATE_CTI_OFFSET 3
#define HWSEQUENCER_DBG_SEQDBGBRKSTATE_CTI_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGBRKSTATE_XCPT_OFFSET 4
#define HWSEQUENCER_DBG_SEQDBGBRKSTATE_XCPT_SIZE 1

/** bit field defines for hwsequencer_dbg_s#seqdbgbkptstate */
#define HWSEQUENCER_DBG_SEQDBGBKPTSTATE_ENABLE_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGBKPTSTATE_ENABLE_SIZE 2

/** bit field defines for hwsequencer_dbg_s#seqdbgbkptenset */
#define HWSEQUENCER_DBG_SEQDBGBKPTENSET_ENABLE_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGBKPTENSET_ENABLE_SIZE 2

/** bit field defines for hwsequencer_dbg_s#seqdbgbkptenclr */
#define HWSEQUENCER_DBG_SEQDBGBKPTENCLR_ENABLE_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGBKPTENCLR_ENABLE_SIZE 2

/** bit field defines for hwsequencer_dbg_s#seqdbgbkpt0 */
#define HWSEQUENCER_DBG_SEQDBGBKPT0_BREAKPOINT_VALUE_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGBKPT0_BREAKPOINT_VALUE_SIZE 16
#define HWSEQUENCER_DBG_SEQDBGBKPT0_ID_OFFSET 16
#define HWSEQUENCER_DBG_SEQDBGBKPT0_ID_SIZE 1

/** bit field defines for hwsequencer_dbg_s#seqdbgbkpt1 */
#define HWSEQUENCER_DBG_SEQDBGBKPT1_BREAKPOINT_VALUE_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGBKPT1_BREAKPOINT_VALUE_SIZE 16
#define HWSEQUENCER_DBG_SEQDBGBKPT1_ID_OFFSET 16
#define HWSEQUENCER_DBG_SEQDBGBKPT1_ID_SIZE 1

/** bit field defines for hwsequencer_dbg_s#seqdbgtrcenset */
#define HWSEQUENCER_DBG_SEQDBGTRCENSET_SEQUENCE_POINTER_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGTRCENSET_SEQUENCE_POINTER_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGTRCENSET_SEQUENCE_ID_OFFSET 1
#define HWSEQUENCER_DBG_SEQDBGTRCENSET_SEQUENCE_ID_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGTRCENSET_BARRIER_OFFSET 2
#define HWSEQUENCER_DBG_SEQDBGTRCENSET_BARRIER_SIZE 1

/** bit field defines for hwsequencer_dbg_s#seqdbgtrcenclr */
#define HWSEQUENCER_DBG_SEQDBGTRCENCLR_SEQUENCE_POINTER_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGTRCENCLR_SEQUENCE_POINTER_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGTRCENCLR_SEQUENCE_ID_OFFSET 1
#define HWSEQUENCER_DBG_SEQDBGTRCENCLR_SEQUENCE_ID_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGTRCENCLR_BARRIER_OFFSET 2
#define HWSEQUENCER_DBG_SEQDBGTRCENCLR_BARRIER_SIZE 1

/** bit field defines for hwsequencer_dbg_s#seqdbgstmbase */
#define HWSEQUENCER_DBG_SEQDBGSTMBASE_STM_BASE_OFFSET 24
#define HWSEQUENCER_DBG_SEQDBGSTMBASE_STM_BASE_SIZE 8

/** bit field defines for hwsequencer_dbg_s#seqdbgptrtrcoff */
#define HWSEQUENCER_DBG_SEQDBGPTRTRCOFF_OFFSET_OFFSET 2
#define HWSEQUENCER_DBG_SEQDBGPTRTRCOFF_OFFSET_SIZE 22

/** bit field defines for hwsequencer_dbg_s#seqdbgidtrcoff */
#define HWSEQUENCER_DBG_SEQDBGIDTRCOFF_OFFSET_OFFSET 2
#define HWSEQUENCER_DBG_SEQDBGIDTRCOFF_OFFSET_SIZE 22

/** bit field defines for hwsequencer_dbg_s#seqdbgbartrcoff */
#define HWSEQUENCER_DBG_SEQDBGBARTRCOFF_OFFSET_OFFSET 2
#define HWSEQUENCER_DBG_SEQDBGBARTRCOFF_OFFSET_SIZE 22

/** bit field defines for hwsequencer_dbg_s#seqdbgfltraw */
#define HWSEQUENCER_DBG_SEQDBGFLTRAW_BARRIER_AXI_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGFLTRAW_BARRIER_AXI_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTRAW_INSTR_AXI_OFFSET 1
#define HWSEQUENCER_DBG_SEQDBGFLTRAW_INSTR_AXI_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTRAW_DEV_AXI_OFFSET 2
#define HWSEQUENCER_DBG_SEQDBGFLTRAW_DEV_AXI_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTRAW_BRANCH_AXI_OFFSET 3
#define HWSEQUENCER_DBG_SEQDBGFLTRAW_BRANCH_AXI_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTRAW_CTRL_ENGFIFO_FULL_OFFSET 4
#define HWSEQUENCER_DBG_SEQDBGFLTRAW_CTRL_ENGFIFO_FULL_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTRAW_SEQ_ENGFIFO_FULL_OFFSET 5
#define HWSEQUENCER_DBG_SEQDBGFLTRAW_SEQ_ENGFIFO_FULL_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTRAW_ENGFIFO_EMPTY_OFFSET 6
#define HWSEQUENCER_DBG_SEQDBGFLTRAW_ENGFIFO_EMPTY_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTRAW_CTRL_BARRIER_WRITE_OFFSET 7
#define HWSEQUENCER_DBG_SEQDBGFLTRAW_CTRL_BARRIER_WRITE_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTRAW_SEQ_BARRIER_WRITE_OFFSET 8
#define HWSEQUENCER_DBG_SEQDBGFLTRAW_SEQ_BARRIER_WRITE_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTRAW_CTRL_BARRIER_IDX_OFFSET 9
#define HWSEQUENCER_DBG_SEQDBGFLTRAW_CTRL_BARRIER_IDX_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTRAW_SEQ_BARRIER_IDX_OFFSET 10
#define HWSEQUENCER_DBG_SEQDBGFLTRAW_SEQ_BARRIER_IDX_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTRAW_INSTRUCTION_OFFSET 11
#define HWSEQUENCER_DBG_SEQDBGFLTRAW_INSTRUCTION_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTRAW_DEADLOCK_OFFSET 12
#define HWSEQUENCER_DBG_SEQDBGFLTRAW_DEADLOCK_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTRAW_TRACE_AXI_OFFSET 13
#define HWSEQUENCER_DBG_SEQDBGFLTRAW_TRACE_AXI_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTRAW_JOBFIFO_OVERFLOW_OFFSET 14
#define HWSEQUENCER_DBG_SEQDBGFLTRAW_JOBFIFO_OVERFLOW_SIZE 1

/** bit field defines for hwsequencer_dbg_s#seqdbgfltstat */
#define HWSEQUENCER_DBG_SEQDBGFLTSTAT_BARRIER_AXI_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGFLTSTAT_BARRIER_AXI_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTSTAT_INSTR_AXI_OFFSET 1
#define HWSEQUENCER_DBG_SEQDBGFLTSTAT_INSTR_AXI_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTSTAT_DEV_AXI_OFFSET 2
#define HWSEQUENCER_DBG_SEQDBGFLTSTAT_DEV_AXI_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTSTAT_BRANCH_AXI_OFFSET 3
#define HWSEQUENCER_DBG_SEQDBGFLTSTAT_BRANCH_AXI_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTSTAT_CTRL_ENGFIFO_FULL_OFFSET 4
#define HWSEQUENCER_DBG_SEQDBGFLTSTAT_CTRL_ENGFIFO_FULL_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTSTAT_SEQ_ENGFIFO_FULL_OFFSET 5
#define HWSEQUENCER_DBG_SEQDBGFLTSTAT_SEQ_ENGFIFO_FULL_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTSTAT_ENGFIFO_EMPTY_OFFSET 6
#define HWSEQUENCER_DBG_SEQDBGFLTSTAT_ENGFIFO_EMPTY_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTSTAT_CTRL_BARRIER_WRITE_OFFSET 7
#define HWSEQUENCER_DBG_SEQDBGFLTSTAT_CTRL_BARRIER_WRITE_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTSTAT_SEQ_BARRIER_WRITE_OFFSET 8
#define HWSEQUENCER_DBG_SEQDBGFLTSTAT_SEQ_BARRIER_WRITE_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTSTAT_CTRL_BARRIER_IDX_OFFSET 9
#define HWSEQUENCER_DBG_SEQDBGFLTSTAT_CTRL_BARRIER_IDX_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTSTAT_SEQ_BARRIER_IDX_OFFSET 10
#define HWSEQUENCER_DBG_SEQDBGFLTSTAT_SEQ_BARRIER_IDX_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTSTAT_INSTRUCTION_OFFSET 11
#define HWSEQUENCER_DBG_SEQDBGFLTSTAT_INSTRUCTION_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTSTAT_DEADLOCK_OFFSET 12
#define HWSEQUENCER_DBG_SEQDBGFLTSTAT_DEADLOCK_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTSTAT_TRACE_AXI_OFFSET 13
#define HWSEQUENCER_DBG_SEQDBGFLTSTAT_TRACE_AXI_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTSTAT_JOBFIFO_OVERFLOW_OFFSET 14
#define HWSEQUENCER_DBG_SEQDBGFLTSTAT_JOBFIFO_OVERFLOW_SIZE 1

/** bit field defines for hwsequencer_dbg_s#seqdbgfltclr */
#define HWSEQUENCER_DBG_SEQDBGFLTCLR_BARRIER_AXI_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGFLTCLR_BARRIER_AXI_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTCLR_INSTR_AXI_OFFSET 1
#define HWSEQUENCER_DBG_SEQDBGFLTCLR_INSTR_AXI_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTCLR_DEV_AXI_OFFSET 2
#define HWSEQUENCER_DBG_SEQDBGFLTCLR_DEV_AXI_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTCLR_BRANCH_AXI_OFFSET 3
#define HWSEQUENCER_DBG_SEQDBGFLTCLR_BRANCH_AXI_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTCLR_CTRL_ENGFIFO_FULL_OFFSET 4
#define HWSEQUENCER_DBG_SEQDBGFLTCLR_CTRL_ENGFIFO_FULL_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTCLR_SEQ_ENGFIFO_FULL_OFFSET 5
#define HWSEQUENCER_DBG_SEQDBGFLTCLR_SEQ_ENGFIFO_FULL_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTCLR_ENGFIFO_EMPTY_OFFSET 6
#define HWSEQUENCER_DBG_SEQDBGFLTCLR_ENGFIFO_EMPTY_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTCLR_CTRL_BARRIER_WRITE_OFFSET 7
#define HWSEQUENCER_DBG_SEQDBGFLTCLR_CTRL_BARRIER_WRITE_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTCLR_SEQ_BARRIER_WRITE_OFFSET 8
#define HWSEQUENCER_DBG_SEQDBGFLTCLR_SEQ_BARRIER_WRITE_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTCLR_CTRL_BARRIER_IDX_OFFSET 9
#define HWSEQUENCER_DBG_SEQDBGFLTCLR_CTRL_BARRIER_IDX_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTCLR_SEQ_BARRIER_IDX_OFFSET 10
#define HWSEQUENCER_DBG_SEQDBGFLTCLR_SEQ_BARRIER_IDX_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTCLR_INSTRUCTION_OFFSET 11
#define HWSEQUENCER_DBG_SEQDBGFLTCLR_INSTRUCTION_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTCLR_DEADLOCK_OFFSET 12
#define HWSEQUENCER_DBG_SEQDBGFLTCLR_DEADLOCK_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTCLR_TRACE_AXI_OFFSET 13
#define HWSEQUENCER_DBG_SEQDBGFLTCLR_TRACE_AXI_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTCLR_JOBFIFO_OVERFLOW_OFFSET 14
#define HWSEQUENCER_DBG_SEQDBGFLTCLR_JOBFIFO_OVERFLOW_SIZE 1

/** bit field defines for hwsequencer_dbg_s#seqdbgfltenset */
#define HWSEQUENCER_DBG_SEQDBGFLTENSET_BARRIER_AXI_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGFLTENSET_BARRIER_AXI_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTENSET_INSTR_AXI_OFFSET 1
#define HWSEQUENCER_DBG_SEQDBGFLTENSET_INSTR_AXI_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTENSET_DEV_AXI_OFFSET 2
#define HWSEQUENCER_DBG_SEQDBGFLTENSET_DEV_AXI_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTENSET_BRANCH_AXI_OFFSET 3
#define HWSEQUENCER_DBG_SEQDBGFLTENSET_BRANCH_AXI_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTENSET_CTRL_ENGFIFO_FULL_OFFSET 4
#define HWSEQUENCER_DBG_SEQDBGFLTENSET_CTRL_ENGFIFO_FULL_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTENSET_SEQ_ENGFIFO_FULL_OFFSET 5
#define HWSEQUENCER_DBG_SEQDBGFLTENSET_SEQ_ENGFIFO_FULL_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTENSET_ENGFIFO_EMPTY_OFFSET 6
#define HWSEQUENCER_DBG_SEQDBGFLTENSET_ENGFIFO_EMPTY_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTENSET_CTRL_BARRIER_WRITE_OFFSET 7
#define HWSEQUENCER_DBG_SEQDBGFLTENSET_CTRL_BARRIER_WRITE_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTENSET_SEQ_BARRIER_WRITE_OFFSET 8
#define HWSEQUENCER_DBG_SEQDBGFLTENSET_SEQ_BARRIER_WRITE_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTENSET_CTRL_BARRIER_IDX_OFFSET 9
#define HWSEQUENCER_DBG_SEQDBGFLTENSET_CTRL_BARRIER_IDX_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTENSET_SEQ_BARRIER_IDX_OFFSET 10
#define HWSEQUENCER_DBG_SEQDBGFLTENSET_SEQ_BARRIER_IDX_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTENSET_INSTRUCTION_OFFSET 11
#define HWSEQUENCER_DBG_SEQDBGFLTENSET_INSTRUCTION_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTENSET_DEADLOCK_OFFSET 12
#define HWSEQUENCER_DBG_SEQDBGFLTENSET_DEADLOCK_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTENSET_TRACE_AXI_OFFSET 13
#define HWSEQUENCER_DBG_SEQDBGFLTENSET_TRACE_AXI_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTENSET_JOBFIFO_OVERFLOW_OFFSET 14
#define HWSEQUENCER_DBG_SEQDBGFLTENSET_JOBFIFO_OVERFLOW_SIZE 1

/** bit field defines for hwsequencer_dbg_s#seqdbgfltenclr */
#define HWSEQUENCER_DBG_SEQDBGFLTENCLR_BARRIER_AXI_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGFLTENCLR_BARRIER_AXI_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTENCLR_INSTR_AXI_OFFSET 1
#define HWSEQUENCER_DBG_SEQDBGFLTENCLR_INSTR_AXI_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTENCLR_DEV_AXI_OFFSET 2
#define HWSEQUENCER_DBG_SEQDBGFLTENCLR_DEV_AXI_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTENCLR_BRANCH_AXI_OFFSET 3
#define HWSEQUENCER_DBG_SEQDBGFLTENCLR_BRANCH_AXI_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTENCLR_CTRL_ENGFIFO_FULL_OFFSET 4
#define HWSEQUENCER_DBG_SEQDBGFLTENCLR_CTRL_ENGFIFO_FULL_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTENCLR_SEQ_ENGFIFO_FULL_OFFSET 5
#define HWSEQUENCER_DBG_SEQDBGFLTENCLR_SEQ_ENGFIFO_FULL_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTENCLR_ENGFIFO_EMPTY_OFFSET 6
#define HWSEQUENCER_DBG_SEQDBGFLTENCLR_ENGFIFO_EMPTY_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTENCLR_CTRL_BARRIER_WRITE_OFFSET 7
#define HWSEQUENCER_DBG_SEQDBGFLTENCLR_CTRL_BARRIER_WRITE_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTENCLR_SEQ_BARRIER_WRITE_OFFSET 8
#define HWSEQUENCER_DBG_SEQDBGFLTENCLR_SEQ_BARRIER_WRITE_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTENCLR_CTRL_BARRIER_IDX_OFFSET 9
#define HWSEQUENCER_DBG_SEQDBGFLTENCLR_CTRL_BARRIER_IDX_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTENCLR_SEQ_BARRIER_IDX_OFFSET 10
#define HWSEQUENCER_DBG_SEQDBGFLTENCLR_SEQ_BARRIER_IDX_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTENCLR_INSTRUCTION_OFFSET 11
#define HWSEQUENCER_DBG_SEQDBGFLTENCLR_INSTRUCTION_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTENCLR_DEADLOCK_OFFSET 12
#define HWSEQUENCER_DBG_SEQDBGFLTENCLR_DEADLOCK_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTENCLR_TRACE_AXI_OFFSET 13
#define HWSEQUENCER_DBG_SEQDBGFLTENCLR_TRACE_AXI_SIZE 1
#define HWSEQUENCER_DBG_SEQDBGFLTENCLR_JOBFIFO_OVERFLOW_OFFSET 14
#define HWSEQUENCER_DBG_SEQDBGFLTENCLR_JOBFIFO_OVERFLOW_SIZE 1

/** bit field defines for hwsequencer_dbg_s#seqdbglar */
#define HWSEQUENCER_DBG_SEQDBGLAR_SEQDBGLAR_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGLAR_SEQDBGLAR_SIZE 32

/** bit field defines for hwsequencer_dbg_s#seqdbglsr */
#define HWSEQUENCER_DBG_SEQDBGLSR_SEQDBGLSR_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGLSR_SEQDBGLSR_SIZE 32

/** bit field defines for hwsequencer_dbg_s#seqdbgauthstatus */
#define HWSEQUENCER_DBG_SEQDBGAUTHSTATUS_SEQDBGAUTHSTATUS_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGAUTHSTATUS_SEQDBGAUTHSTATUS_SIZE 32

/** bit field defines for hwsequencer_dbg_s#seqdbgdevid */
#define HWSEQUENCER_DBG_SEQDBGDEVID_SEQDBGDEVID_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGDEVID_SEQDBGDEVID_SIZE 32

/** bit field defines for hwsequencer_dbg_s#seqdbgdevtype */
#define HWSEQUENCER_DBG_SEQDBGDEVTYPE_SEQDBGDEVTYPE_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGDEVTYPE_SEQDBGDEVTYPE_SIZE 32

/** bit field defines for hwsequencer_dbg_s#seqdbgperiphid4 */
#define HWSEQUENCER_DBG_SEQDBGPERIPHID4_SEQDBGPERIPHID4_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGPERIPHID4_SEQDBGPERIPHID4_SIZE 8

/** bit field defines for hwsequencer_dbg_s#seqdbgperiphid5 */
#define HWSEQUENCER_DBG_SEQDBGPERIPHID5_SEQDBGPERIPHID5_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGPERIPHID5_SEQDBGPERIPHID5_SIZE 8

/** bit field defines for hwsequencer_dbg_s#seqdbgperiphid6 */
#define HWSEQUENCER_DBG_SEQDBGPERIPHID6_SEQDBGPERIPHID6_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGPERIPHID6_SEQDBGPERIPHID6_SIZE 8

/** bit field defines for hwsequencer_dbg_s#seqdbgperiphid7 */
#define HWSEQUENCER_DBG_SEQDBGPERIPHID7_SEQDBGPERIPHID7_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGPERIPHID7_SEQDBGPERIPHID7_SIZE 8

/** bit field defines for hwsequencer_dbg_s#seqdbgperiphid0 */
#define HWSEQUENCER_DBG_SEQDBGPERIPHID0_SEQDBGPERIPHID0_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGPERIPHID0_SEQDBGPERIPHID0_SIZE 8

/** bit field defines for hwsequencer_dbg_s#seqdbgperiphid1 */
#define HWSEQUENCER_DBG_SEQDBGPERIPHID1_SEQDBGPERIPHID1_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGPERIPHID1_SEQDBGPERIPHID1_SIZE 8

/** bit field defines for hwsequencer_dbg_s#seqdbgperiphid2 */
#define HWSEQUENCER_DBG_SEQDBGPERIPHID2_SEQDBGPERIPHID2_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGPERIPHID2_SEQDBGPERIPHID2_SIZE 8

/** bit field defines for hwsequencer_dbg_s#seqdbgperiphid3 */
#define HWSEQUENCER_DBG_SEQDBGPERIPHID3_SEQDBGPERIPHID3_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGPERIPHID3_SEQDBGPERIPHID3_SIZE 8

/** bit field defines for hwsequencer_dbg_s#seqdbgcompid0 */
#define HWSEQUENCER_DBG_SEQDBGCOMPID0_SEQDBGCOMPID0_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGCOMPID0_SEQDBGCOMPID0_SIZE 8

/** bit field defines for hwsequencer_dbg_s#seqdbgcompid1 */
#define HWSEQUENCER_DBG_SEQDBGCOMPID1_SEQDBGCOMPID1_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGCOMPID1_SEQDBGCOMPID1_SIZE 8

/** bit field defines for hwsequencer_dbg_s#seqdbgcompid2 */
#define HWSEQUENCER_DBG_SEQDBGCOMPID2_SEQDBGCOMPID2_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGCOMPID2_SEQDBGCOMPID2_SIZE 8

/** bit field defines for hwsequencer_dbg_s#seqdbgcompid3 */
#define HWSEQUENCER_DBG_SEQDBGCOMPID3_SEQDBGCOMPID3_OFFSET 0
#define HWSEQUENCER_DBG_SEQDBGCOMPID3_SEQDBGCOMPID3_SIZE 8

/* EOF hwsequencer_dbg.h */
#endif
