; 
; Copyright (C) u-blox
; All rights reserved.
; This source file is the sole property of u-blox. Reproduction or utilization
; of this source in whole or part is forbidden without the written consent of
; u-blox.
; 
; FILE: hwsequencer.hs

HWS_NR_ENGINES EQU 4
HWSEQUENCER_FLAGSTAT EQU 0x000
HWSEQUENCER_FLAGCLR EQU 0x004
HWSEQUENCER_BARINIT EQU 0x010
HWSEQUENCER_BARSET EQU 0x014
HWSEQUENCER_BARDEC EQU 0x018
HWSEQUENCER_BARREADREQ EQU 0x020
HWSEQUENCER_BARCNT EQU 0x024
HWSEQUENCER_BARSEQPTR EQU 0x028
HWSEQUENCER_FLAGMASK_CLEAR EQU 0x030
HWSEQUENCER_FLAGMASK_SET EQU 0x034
HWSEQUENCER_FLAGMASK_STATUS EQU 0x038
HWSEQUENCER_TEFPUSH EQU 0x040
HWSEQUENCER_EXEC EQU 0x044
HWSEQUENCER_JOBEVSTAT EQU 0x050
HWSEQUENCER_JOBEVCLR EQU 0x054
HWSEQUENCER_JOBEVMASK_CLEAR EQU 0x058
HWSEQUENCER_JOBEVMASK_SET EQU 0x05C
HWSEQUENCER_JOBEVMASK_STAT EQU 0x060
HWSEQUENCER_JOBQUEUE0_PUSH EQU 0x080
HWSEQUENCER_JOBQUEUE1_PUSH EQU 0x084
HWSEQUENCER_JOBQUEUE0_STATUS EQU 0x0A0
HWSEQUENCER_JOBQUEUE1_STATUS EQU 0x0A4
HWSEQUENCER_JOBQUEUE0_CONFIG EQU 0x0C0
HWSEQUENCER_JOBQUEUE1_CONFIG EQU 0x0C4
HWSEQUENCER_JOBQUEUE_IRQ_RAW EQU 0x0E0
HWSEQUENCER_JOBQUEUE_IRQ_STATUS EQU 0x0E4
HWSEQUENCER_JOBQUEUE_IRQ_ENABLE_SET EQU 0x0EC
HWSEQUENCER_JOBQUEUE_IRQ_ENABLE_CLEAR EQU 0x0F0
HWSEQUENCER_JOBQUEUE_IRQ_ENABLE_STATUS EQU 0x0F4
HWSEQUENCER_CMD EQU 0x100
HWSEQUENCER_STATUS EQU 0x104
HWSEQUENCER_TEFRST EQU 0x108
HWSEQUENCER_TEFREADREQ EQU 0x10C
HWSEQUENCER_TEFVAL EQU 0x110
HWSEQUENCER_ENGENASET EQU 0x120
HWSEQUENCER_ENGENACLR EQU 0x124
HWSEQUENCER_ENGENASTAT EQU 0x128
HWSEQUENCER_ENGSUSPSET EQU 0x130
HWSEQUENCER_ENGSUSPCLR EQU 0x134
HWSEQUENCER_ENGSUSPSTAT EQU 0x138
HWSEQUENCER_SEQINSTRBASE EQU 0x200
HWSEQUENCER_BARRIERBASE EQU 0x204
HWSEQUENCER_LBP EQU 0x208
HWSEQUENCER_MEMBASE EQU 0x20C
HWSEQUENCER_MEMBASE_FIELDS EQU HWS_NR_ENGINES
HWSEQUENCER_FLTCLEAR EQU 0x300
HWSEQUENCER_FLTSTATUS EQU 0x304
HWSEQUENCER_FLTRAWSTATUS EQU 0x308
HWSEQUENCER_FLTMASKCLR EQU 0x30C
HWSEQUENCER_FLTMASKSET EQU 0x310
HWSEQUENCER_FLTMASKSTATUS EQU 0x314
HWSEQUENCER_FLTSIGBARRIER EQU 0x318
HWSEQUENCER_FLTSIGENG EQU 0x31C
HWSEQUENCER_FLTSIGADDR EQU 0x320
HWSEQUENCER_FLTSEQPTR EQU 0x324
HWSEQUENCER_CONFIG EQU 0xE00
HWSEQUENCER_PERIPHERALID4 EQU 0xFD0
HWSEQUENCER_PERIPHERALID5 EQU 0xFD4
HWSEQUENCER_PERIPHERALID6 EQU 0xFD8
HWSEQUENCER_PERIPHERALID7 EQU 0xFDC
HWSEQUENCER_PERIPHERALID0 EQU 0xFE0
HWSEQUENCER_PERIPHERALID1 EQU 0xFE4
HWSEQUENCER_PERIPHERALID2 EQU 0xFE8
HWSEQUENCER_PERIPHERALID3 EQU 0xFEC
HWSEQUENCER_COMPONENTID0 EQU 0xFF0
HWSEQUENCER_COMPONENTID1 EQU 0xFF4
HWSEQUENCER_COMPONENTID2 EQU 0xFF8
HWSEQUENCER_COMPONENTID3 EQU 0xFFC
HWSEQUENCER_BAR_INIT_ARRAY EQU 0x4000
HWSEQUENCER_BAR_INIT_ARRAY_FIELDS EQU 4096
HWSEQUENCER_BAR_SET_ARRAY EQU 0x8000
HWSEQUENCER_BAR_SET_ARRAY_FIELDS EQU 4096
HWSEQUENCER_BAR_DEC_ARRAY EQU 0xC000
HWSEQUENCER_BAR_DEC_ARRAY_FIELDS EQU 4096
; EOF: hwsequencer.hs
   END
