; 
; Copyright (C) u-blox
; All rights reserved.
; This source file is the sole property of u-blox. Reproduction or utilization
; of this source in whole or part is forbidden without the written consent of
; u-blox.
; 
; FILE: hwsequencer_dbg.hs

HWSEQUENCER_DBG_SEQDBGSTATUS EQU 0x000
HWSEQUENCER_DBG_SEQDBGSEQPTR EQU 0x004
HWSEQUENCER_DBG_SEQDBGSEQID EQU 0x008
HWSEQUENCER_DBG_SEQDBGBRKSTATE EQU 0x00C
HWSEQUENCER_DBG_SEQDBGBKPTSTATE EQU 0x010
HWSEQUENCER_DBG_SEQDBGBKPTENSET EQU 0x014
HWSEQUENCER_DBG_SEQDBGBKPTENCLR EQU 0x018
HWSEQUENCER_DBG_SEQDBGBKPT0 EQU 0x100
HWSEQUENCER_DBG_SEQDBGBKPT1 EQU 0x104
HWSEQUENCER_DBG_SEQDBGTRCENSET EQU 0x200
HWSEQUENCER_DBG_SEQDBGTRCENCLR EQU 0x204
HWSEQUENCER_DBG_SEQDBGSTMBASE EQU 0x208
HWSEQUENCER_DBG_SEQDBGPTRTRCOFF EQU 0x20C
HWSEQUENCER_DBG_SEQDBGIDTRCOFF EQU 0x210
HWSEQUENCER_DBG_SEQDBGBARTRCOFF EQU 0x214
HWSEQUENCER_DBG_SEQDBGFLTRAW EQU 0x300
HWSEQUENCER_DBG_SEQDBGFLTSTAT EQU 0x304
HWSEQUENCER_DBG_SEQDBGFLTCLR EQU 0x308
HWSEQUENCER_DBG_SEQDBGFLTENSET EQU 0x30C
HWSEQUENCER_DBG_SEQDBGFLTENCLR EQU 0x310
HWSEQUENCER_DBG_SEQDBGLAR EQU 0xFB0
HWSEQUENCER_DBG_SEQDBGLSR EQU 0xFB4
HWSEQUENCER_DBG_SEQDBGAUTHSTATUS EQU 0xFB8
HWSEQUENCER_DBG_SEQDBGDEVID EQU 0xFC8
HWSEQUENCER_DBG_SEQDBGDEVTYPE EQU 0xFCC
HWSEQUENCER_DBG_SEQDBGPERIPHID4 EQU 0xFD0
HWSEQUENCER_DBG_SEQDBGPERIPHID5 EQU 0xFD4
HWSEQUENCER_DBG_SEQDBGPERIPHID6 EQU 0xFD8
HWSEQUENCER_DBG_SEQDBGPERIPHID7 EQU 0xFDC
HWSEQUENCER_DBG_SEQDBGPERIPHID0 EQU 0xFE0
HWSEQUENCER_DBG_SEQDBGPERIPHID1 EQU 0xFE4
HWSEQUENCER_DBG_SEQDBGPERIPHID2 EQU 0xFE8
HWSEQUENCER_DBG_SEQDBGPERIPHID3 EQU 0xFEC
HWSEQUENCER_DBG_SEQDBGCOMPID0 EQU 0xFF0
HWSEQUENCER_DBG_SEQDBGCOMPID1 EQU 0xFF4
HWSEQUENCER_DBG_SEQDBGCOMPID2 EQU 0xFF8
HWSEQUENCER_DBG_SEQDBGCOMPID3 EQU 0xFFC
; EOF: hwsequencer_dbg.hs
   END
