; 
; Copyright (C) u-blox
; All rights reserved.
; This source file is the sole property of u-blox. Reproduction or utilization
; of this source in whole or part is forbidden without the written consent of
; u-blox.
; 
; FILE: ipc_mbx.hs

IPC_MBX_MBX_TX_SET EQU 0x000
IPC_MBX_MBX_TX_CLR EQU 0x004
IPC_MBX_MBX_TX_MSG EQU 0x008
IPC_MBX_MBX_TX_CFG EQU 0x00C
IPC_MBX_MBX_RX_SET EQU 0x010
IPC_MBX_MBX_RX_CLR EQU 0x014
IPC_MBX_MBX_RX_MSG EQU 0x018
IPC_MBX_MBX_RX_CFG EQU 0x01C
IPC_MBX_PERIPHERALID4 EQU 0xFD0
IPC_MBX_PERIPHERALID5 EQU 0xFD4
IPC_MBX_PERIPHERALID6 EQU 0xFD8
IPC_MBX_PERIPHERALID7 EQU 0xFDC
IPC_MBX_PERIPHERALID0 EQU 0xFE0
IPC_MBX_PERIPHERALID1 EQU 0xFE4
IPC_MBX_PERIPHERALID2 EQU 0xFE8
IPC_MBX_PERIPHERALID3 EQU 0xFEC
IPC_MBX_COMPONENTID0 EQU 0xFF0
IPC_MBX_COMPONENTID1 EQU 0xFF4
IPC_MBX_COMPONENTID2 EQU 0xFF8
IPC_MBX_COMPONENTID3 EQU 0xFFC
; EOF: ipc_mbx.hs
   END
