; 
; Copyright (C) u-blox
; All rights reserved.
; This source file is the sole property of u-blox. Reproduction or utilization
; of this source in whole or part is forbidden without the written consent of
; u-blox.
; 
; FILE: km_fbuf.hs

KM_FBUF_HAL_VERSION EQU 3
KM_FBUF_WRCTRL EQU 0x000
KM_FBUF_STATUS EQU 0x004
KM_FBUF_PWRACC EQU 0x008
KM_FBUF_DCACC EQU 0x00C
KM_FBUF_MATCH EQU 0x010
KM_FBUF_CLIERRCTRL EQU 0x014
KM_FBUF_EVENTSTATUS EQU 0x018
KM_FBUF_INTMASK EQU 0x01C
KM_FBUF_INTSTATUS EQU 0x020
KM_FBUF_CLIERRINFO EQU 0x024
KM_FBUF_HWOBS EQU 0x028
KM_FBUF_PERIPHERALID6 EQU 0xFD0
KM_FBUF_PERIPHERALID7 EQU 0xFD4
KM_FBUF_PERIPHERALID0 EQU 0xFD8
KM_FBUF_PERIPHERALID1 EQU 0xFDC
KM_FBUF_PERIPHERALID2 EQU 0xFE0
KM_FBUF_PERIPHERALID3 EQU 0xFE4
KM_FBUF_COMPONENTID0 EQU 0xFE8
KM_FBUF_COMPONENTID1 EQU 0xFEC
KM_FBUF_COMPONENTID2 EQU 0xFF0
KM_FBUF_COMPONENTID3 EQU 0xFF4
; EOF: km_fbuf.hs
   END
