; 
; Copyright (C) u-blox
; All rights reserved.
; This source file is the sole property of u-blox. Reproduction or utilization
; of this source in whole or part is forbidden without the written consent of
; u-blox.
; 
; FILE: km_gnss_apps_tim.hs

KM_GNSS_APPS_TIM_HAL_VERSION EQU 1
KM_GNSS_APPS_TIM_CTRLS EQU 0x000
KM_GNSS_APPS_TIM_CTRLC EQU 0x004
KM_GNSS_APPS_TIM_CTRL EQU 0x008
KM_GNSS_APPS_TIM_RTC EQU 0x00C
KM_GNSS_APPS_TIM_RTCPRELOADMSB EQU 0x010
KM_GNSS_APPS_TIM_RTCPRELOADLSB EQU 0x014
KM_GNSS_APPS_TIM_TRIG EQU 0x018
KM_GNSS_APPS_TIM_TRIGCTRL EQU 0x01C
KM_GNSS_APPS_TIM_GPOCTRL EQU 0x020
KM_GNSS_APPS_TIM_IRQMASK EQU 0x024
KM_GNSS_APPS_TIM_IRQSTATUS EQU 0x028
KM_GNSS_APPS_TIM_APPTRIG EQU 0x02C
KM_GNSS_APPS_TIM_RTCVALUEREQ EQU 0x030
KM_GNSS_APPS_TIM_RTCMSB EQU 0x034
KM_GNSS_APPS_TIM_RTCLSB EQU 0x038
KM_GNSS_APPS_TIM_TIMECOMP EQU 0x03C
KM_GNSS_APPS_TIM_TIMECOMPMSB EQU 0x040
KM_GNSS_APPS_TIM_TIMECOMPLSB EQU 0x044
KM_GNSS_APPS_TIM_TIMECOMPMASKMSB EQU 0x048
KM_GNSS_APPS_TIM_TIMECOMPMASKLSB EQU 0x04C
KM_GNSS_APPS_TIM_EDGECOUNT EQU 0x050
; EOF: km_gnss_apps_tim.hs
   END
