#ifndef INCLUDED_KM_SSS
#define INCLUDED_KM_SSS
/*
 * Copyright (C) u-blox 
 * All rights reserved. 
 * This source file is the sole property of u-blox. Reproduction or utilization 
 * of this source in whole or part is forbidden without the written consent of 
 * u-blox.
 *
 */

#include <stdint.h>

/** km_sss HAL Spreadsheet version number */
#define KM_SSS_HAL_VERSION 1

/** This is the SSS register module
*/
struct km_sss_s {
   /** Top-level SSS Control at address offset 0x000, read-write */
   uint32_t commandctrl;
   /** SSS Control Status at address offset 0x004, read-only */
   uint32_t commandstatus1;
   /** SSS Control Status (contd.) at address offset 0x008, read-only */
   uint32_t commandstatus2;
   /** SSS Control Status (contd.) at address offset 0x00C, read-only */
   uint32_t commandstatus3;
   /** SSS Command Parameters at address offset 0x010, read-write */
   uint32_t commandparams1_0;
   /** SSS Command Parameters (contd.) at address offset 0x014, read-write */
   uint32_t commandparams2_0;
   /** SSS Command Parameters at address offset 0x018, read-write */
   uint32_t commandparams1_1;
   /** SSS Command Parameters (contd.) at address offset 0x01C, read-write */
   uint32_t commandparams2_1;
   /** SSS Command Parameters at address offset 0x020, read-write */
   uint32_t commandparams1_2;
   /** SSS Command Parameters (contd.) at address offset 0x024, read-write */
   uint32_t commandparams2_2;
   /** SSS Command Parameters at address offset 0x028, read-write */
   uint32_t commandparams1_3;
   /** SSS Command Parameters (contd.) at address offset 0x02C, read-write */
   uint32_t commandparams2_3;
   /** SSS Command Parameters at address offset 0x030, read-write */
   uint32_t commandparams1_4;
   /** SSS Command Parameters (contd.) at address offset 0x034, read-write */
   uint32_t commandparams2_4;
   /** SSS Command Parameters at address offset 0x038, read-write */
   uint32_t commandparams1_5;
   /** SSS Command Parameters (contd.) at address offset 0x03C, read-write */
   uint32_t commandparams2_5;
   /** SSS Command Parameters at address offset 0x040, read-write */
   uint32_t commandparams1_6;
   /** SSS Command Parameters (contd.) at address offset 0x044, read-write */
   uint32_t commandparams2_6;
   /** SSS Command Parameters at address offset 0x048, read-write */
   uint32_t commandparams1_7;
   /** SSS Command Parameters (contd.) at address offset 0x04C, read-write */
   uint32_t commandparams2_7;
   /** SSS Context Configuration at address offset 0x050, read-write */
   uint32_t contextconfig_0;
   /** SSS Context Configuration (contd.) at address offset 0x054, read-write */
   uint32_t contextconfig1_0;
   /** SSS Context Configuration at address offset 0x058, read-write */
   uint32_t contextconfig_1;
   /** SSS Context Configuration (contd.) at address offset 0x05C, read-write */
   uint32_t contextconfig1_1;
   /** SSS Context Configuration at address offset 0x060, read-write */
   uint32_t contextconfig_2;
   /** SSS Context Configuration (contd.) at address offset 0x064, read-write */
   uint32_t contextconfig1_2;
   /** SSS Context Configuration at address offset 0x068, read-write */
   uint32_t contextconfig_3;
   /** SSS Context Configuration (contd.) at address offset 0x06C, read-write */
   uint32_t contextconfig1_3;
   /** SSS Context Configuration at address offset 0x070, read-write */
   uint32_t contextconfig_4;
   /** SSS Context Configuration (contd.) at address offset 0x074, read-write */
   uint32_t contextconfig1_4;
   /** SSS Context Configuration at address offset 0x078, read-write */
   uint32_t contextconfig_5;
   /** SSS Context Configuration (contd.) at address offset 0x07C, read-write */
   uint32_t contextconfig1_5;
   /** SSS Context Configuration at address offset 0x080, read-write */
   uint32_t contextconfig_6;
   /** SSS Context Configuration (contd.) at address offset 0x084, read-write */
   uint32_t contextconfig1_6;
   /** SSS Context Configuration at address offset 0x088, read-write */
   uint32_t contextconfig_7;
   /** SSS Context Configuration (contd.) at address offset 0x08C, read-write */
   uint32_t contextconfig1_7;
   /** SSS Context Configuration at address offset 0x090, read-write */
   uint32_t contextconfig_8;
   /** SSS Context Configuration (contd.) at address offset 0x094, read-write */
   uint32_t contextconfig1_8;
   /** SSS Context Configuration at address offset 0x098, read-write */
   uint32_t contextconfig_9;
   /** SSS Context Configuration (contd.) at address offset 0x09C, read-write */
   uint32_t contextconfig1_9;
   /** SSS Context Configuration at address offset 0x0A0, read-write */
   uint32_t contextconfig_10;
   /** SSS Context Configuration (contd.) at address offset 0x0A4, read-write */
   uint32_t contextconfig1_10;
   /** SSS Context Configuration at address offset 0x0A8, read-write */
   uint32_t contextconfig_11;
   /** SSS Context Configuration (contd.) at address offset 0x0AC, read-write */
   uint32_t contextconfig1_11;
   /** SSS Context Configuration at address offset 0x0B0, read-write */
   uint32_t contextconfig_12;
   /** SSS Context Configuration (contd.) at address offset 0x0B4, read-write */
   uint32_t contextconfig1_12;
   /** SSS Context Configuration at address offset 0x0B8, read-write */
   uint32_t contextconfig_13;
   /** SSS Context Configuration (contd.) at address offset 0x0BC, read-write */
   uint32_t contextconfig1_13;
   /** SSS Context Configuration at address offset 0x0C0, read-write */
   uint32_t contextconfig_14;
   /** SSS Context Configuration (contd.) at address offset 0x0C4, read-write */
   uint32_t contextconfig1_14;
   /** SSS Context Configuration at address offset 0x0C8, read-write */
   uint32_t contextconfig_15;
   /** SSS Context Configuration (contd.) at address offset 0x0CC, read-write */
   uint32_t contextconfig1_15;
   /** SSS (axi) Transfer Criteria (combination (0,0) means no transferring) at address offset 0x0D0, read-write */
   uint32_t transfertrigger;
   /** SSS (axi) Coefficient address at address offset 0x0D4, read-write */
   uint32_t coefftransfer;
   /** SSS (axi) Soft Combine address at address offset 0x0D8, read-write */
   uint32_t softcombtransfer;
   /** SSS (axi) "pss covariance" address at address offset 0x0DC, read-write */
   uint32_t psscovtransfer;
   /**  at address offset 0x0E0, read-only */
   uint32_t reader;
   /** SSS Event Status NOT SHADOWED / ReadOnly at address offset 0x0E4, read-write */
   uint32_t eventstatus;
   /** SSS Interrupt Mask at address offset 0x0E8, read-write */
   uint32_t interruptmask;
   /** SSS Interrupt Status. Write to EventStatus to clear. at address offset 0x0EC, read-only */
   uint32_t interruptstatus;
   /** Interrupt mask for hw sequence pulse at address offset 0x0F0, read-write */
   uint32_t interruptpulsemask;
   /** Hardware Observation Port at address offset 0x0F4, read-write */
   uint32_t hwobs;
};

/** bit field defines for km_sss_s#commandctrl */
#define KM_SSS_COMMANDCTRL_NEXTIDX_OFFSET 0
#define KM_SSS_COMMANDCTRL_NEXTIDX_SIZE 3
#define KM_SSS_COMMANDCTRL_DONEXT_OFFSET 3
#define KM_SSS_COMMANDCTRL_DONEXT_SIZE 1
#define KM_SSS_COMMANDCTRL_RESET_OFFSET 4
#define KM_SSS_COMMANDCTRL_RESET_SIZE 1

/** bit field defines for km_sss_s#commandstatus1 */
#define KM_SSS_COMMANDSTATUS1_NEXTIDX_OFFSET 0
#define KM_SSS_COMMANDSTATUS1_NEXTIDX_SIZE 3
#define KM_SSS_COMMANDSTATUS1_ISRUNNINGIDX_OFFSET 3
#define KM_SSS_COMMANDSTATUS1_ISRUNNINGIDX_SIZE 3
#define KM_SSS_COMMANDSTATUS1_COMMANDSTATE_OFFSET 6
#define KM_SSS_COMMANDSTATUS1_COMMANDSTATE_SIZE 4
/** Covariance: including {pss_load, pss_correlate, pss_covariance} */
#define KM_SSS_COMMANDSTATUS1_COMMANDSTATE_COVPROC_VALUE 3
/** Axi Transfer the Covariance */
#define KM_SSS_COMMANDSTATUS1_COMMANDSTATE_COVXFER_VALUE 10
/** Sweep 16 contexts looking for next candidate */
#define KM_SSS_COMMANDSTATUS1_COMMANDSTATE_CTXSEL_VALUE 2
/** Accumulate the pdpNorm */
#define KM_SSS_COMMANDSTATUS1_COMMANDSTATE_PDPACC_VALUE 7
/** PDP comprising (sparse input 62/129)  pdp_fft and norm  (re^2 + im^2) */
#define KM_SSS_COMMANDSTATUS1_COMMANDSTATE_PDPPROC_VALUE 6
/** PSS including {pss_fft, coarse_chest, chest} */
#define KM_SSS_COMMANDSTATUS1_COMMANDSTATE_PSSPROC_VALUE 5
/** Axi transfer the SSS (and Meta) */
#define KM_SSS_COMMANDSTATUS1_COMMANDSTATE_SSSXFER_VALUE 13
/** Waiting for current contexts previous Transfer Event Flag to clear. */
#define KM_SSS_COMMANDSTATUS1_COMMANDSTATE_STALLXFER_VALUE 14
/** Load upto 3 banks of coefficients; each bank is 15x15byte, packed as 15x16byte, axi xfer as 60x32b */
#define KM_SSS_COMMANDSTATUS1_COMMANDSTATE_COEFF_VALUE 1
/** Accumulate the Covariance */
#define KM_SSS_COMMANDSTATUS1_COMMANDSTATE_COVACC_VALUE 4
/**  */
#define KM_SSS_COMMANDSTATUS1_COMMANDSTATE_IDLE_VALUE 0
/**  */
#define KM_SSS_COMMANDSTATUS1_COMMANDSTATE_PDPSTALLXFER_VALUE 12
/** Axi Transfer the PDP */
#define KM_SSS_COMMANDSTATUS1_COMMANDSTATE_PDPXFER_VALUE 11
/** Accumulate the SSS (and sss_meta) */
#define KM_SSS_COMMANDSTATUS1_COMMANDSTATE_SSSACC_VALUE 9
/** SSS including {sss_load, sss_fft, sss_noise, sss_eq} */
#define KM_SSS_COMMANDSTATUS1_COMMANDSTATE_SSSPROC_VALUE 8
#define KM_SSS_COMMANDSTATUS1_CONTEXTIDX_OFFSET 10
#define KM_SSS_COMMANDSTATUS1_CONTEXTIDX_SIZE 4
#define KM_SSS_COMMANDSTATUS1_CONTEXTSLOTHALF_OFFSET 14
#define KM_SSS_COMMANDSTATUS1_CONTEXTSLOTHALF_SIZE 1
#define KM_SSS_COMMANDSTATUS1_CONTEXTIDXNEXT_OFFSET 15
#define KM_SSS_COMMANDSTATUS1_CONTEXTIDXNEXT_SIZE 5

/** bit field defines for km_sss_s#commandstatus2 */
#define KM_SSS_COMMANDSTATUS2_TIMEOFFSETNEXT_OFFSET 0
#define KM_SSS_COMMANDSTATUS2_TIMEOFFSETNEXT_SIZE 15
#define KM_SSS_COMMANDSTATUS2_TIMEREMAINING_OFFSET 15
#define KM_SSS_COMMANDSTATUS2_TIMEREMAINING_SIZE 16

/** bit field defines for km_sss_s#commandstatus3 */
#define KM_SSS_COMMANDSTATUS3_COMBINECOUNT0_OFFSET 0
#define KM_SSS_COMMANDSTATUS3_COMBINECOUNT0_SIZE 5
#define KM_SSS_COMMANDSTATUS3_COMBINECOUNT1_OFFSET 5
#define KM_SSS_COMMANDSTATUS3_COMBINECOUNT1_SIZE 5
#define KM_SSS_COMMANDSTATUS3_NUMREMCOUNT_OFFSET 10
#define KM_SSS_COMMANDSTATUS3_NUMREMCOUNT_SIZE 6
#define KM_SSS_COMMANDSTATUS3_DOTRANSFERRING_OFFSET 16
#define KM_SSS_COMMANDSTATUS3_DOTRANSFERRING_SIZE 1

/** bit field defines for km_sss_s#commandparams1_0 */
#define KM_SSS_COMMANDPARAMS1_0_PSSOFFSETSTART_OFFSET 0
#define KM_SSS_COMMANDPARAMS1_0_PSSOFFSETSTART_SIZE 15
#define KM_SSS_COMMANDPARAMS1_0_PSSOFFSETDURATION_OFFSET 16
#define KM_SSS_COMMANDPARAMS1_0_PSSOFFSETDURATION_SIZE 16

/** bit field defines for km_sss_s#commandparams2_0 */
#define KM_SSS_COMMANDPARAMS2_0_FBUFPTRSTART_OFFSET 0
#define KM_SSS_COMMANDPARAMS2_0_FBUFPTRSTART_SIZE 16
#define KM_SSS_COMMANDPARAMS2_0_GROUPID_OFFSET 16
#define KM_SSS_COMMANDPARAMS2_0_GROUPID_SIZE 2
#define KM_SSS_COMMANDPARAMS2_0_DOTRANSFERRING_OFFSET 18
#define KM_SSS_COMMANDPARAMS2_0_DOTRANSFERRING_SIZE 1
#define KM_SSS_COMMANDPARAMS2_0_DOLOADCOEFF_OFFSET 19
#define KM_SSS_COMMANDPARAMS2_0_DOLOADCOEFF_SIZE 3

/** bit field defines for km_sss_s#commandparams1_1 */
#define KM_SSS_COMMANDPARAMS1_1_PSSOFFSETSTART_OFFSET 0
#define KM_SSS_COMMANDPARAMS1_1_PSSOFFSETSTART_SIZE 15
#define KM_SSS_COMMANDPARAMS1_1_PSSOFFSETDURATION_OFFSET 16
#define KM_SSS_COMMANDPARAMS1_1_PSSOFFSETDURATION_SIZE 16

/** bit field defines for km_sss_s#commandparams2_1 */
#define KM_SSS_COMMANDPARAMS2_1_FBUFPTRSTART_OFFSET 0
#define KM_SSS_COMMANDPARAMS2_1_FBUFPTRSTART_SIZE 16
#define KM_SSS_COMMANDPARAMS2_1_GROUPID_OFFSET 16
#define KM_SSS_COMMANDPARAMS2_1_GROUPID_SIZE 2
#define KM_SSS_COMMANDPARAMS2_1_DOTRANSFERRING_OFFSET 18
#define KM_SSS_COMMANDPARAMS2_1_DOTRANSFERRING_SIZE 1
#define KM_SSS_COMMANDPARAMS2_1_DOLOADCOEFF_OFFSET 19
#define KM_SSS_COMMANDPARAMS2_1_DOLOADCOEFF_SIZE 3

/** bit field defines for km_sss_s#commandparams1_2 */
#define KM_SSS_COMMANDPARAMS1_2_PSSOFFSETSTART_OFFSET 0
#define KM_SSS_COMMANDPARAMS1_2_PSSOFFSETSTART_SIZE 15
#define KM_SSS_COMMANDPARAMS1_2_PSSOFFSETDURATION_OFFSET 16
#define KM_SSS_COMMANDPARAMS1_2_PSSOFFSETDURATION_SIZE 16

/** bit field defines for km_sss_s#commandparams2_2 */
#define KM_SSS_COMMANDPARAMS2_2_FBUFPTRSTART_OFFSET 0
#define KM_SSS_COMMANDPARAMS2_2_FBUFPTRSTART_SIZE 16
#define KM_SSS_COMMANDPARAMS2_2_GROUPID_OFFSET 16
#define KM_SSS_COMMANDPARAMS2_2_GROUPID_SIZE 2
#define KM_SSS_COMMANDPARAMS2_2_DOTRANSFERRING_OFFSET 18
#define KM_SSS_COMMANDPARAMS2_2_DOTRANSFERRING_SIZE 1
#define KM_SSS_COMMANDPARAMS2_2_DOLOADCOEFF_OFFSET 19
#define KM_SSS_COMMANDPARAMS2_2_DOLOADCOEFF_SIZE 3

/** bit field defines for km_sss_s#commandparams1_3 */
#define KM_SSS_COMMANDPARAMS1_3_PSSOFFSETSTART_OFFSET 0
#define KM_SSS_COMMANDPARAMS1_3_PSSOFFSETSTART_SIZE 15
#define KM_SSS_COMMANDPARAMS1_3_PSSOFFSETDURATION_OFFSET 16
#define KM_SSS_COMMANDPARAMS1_3_PSSOFFSETDURATION_SIZE 16

/** bit field defines for km_sss_s#commandparams2_3 */
#define KM_SSS_COMMANDPARAMS2_3_FBUFPTRSTART_OFFSET 0
#define KM_SSS_COMMANDPARAMS2_3_FBUFPTRSTART_SIZE 16
#define KM_SSS_COMMANDPARAMS2_3_GROUPID_OFFSET 16
#define KM_SSS_COMMANDPARAMS2_3_GROUPID_SIZE 2
#define KM_SSS_COMMANDPARAMS2_3_DOTRANSFERRING_OFFSET 18
#define KM_SSS_COMMANDPARAMS2_3_DOTRANSFERRING_SIZE 1
#define KM_SSS_COMMANDPARAMS2_3_DOLOADCOEFF_OFFSET 19
#define KM_SSS_COMMANDPARAMS2_3_DOLOADCOEFF_SIZE 3

/** bit field defines for km_sss_s#commandparams1_4 */
#define KM_SSS_COMMANDPARAMS1_4_PSSOFFSETSTART_OFFSET 0
#define KM_SSS_COMMANDPARAMS1_4_PSSOFFSETSTART_SIZE 15
#define KM_SSS_COMMANDPARAMS1_4_PSSOFFSETDURATION_OFFSET 16
#define KM_SSS_COMMANDPARAMS1_4_PSSOFFSETDURATION_SIZE 16

/** bit field defines for km_sss_s#commandparams2_4 */
#define KM_SSS_COMMANDPARAMS2_4_FBUFPTRSTART_OFFSET 0
#define KM_SSS_COMMANDPARAMS2_4_FBUFPTRSTART_SIZE 16
#define KM_SSS_COMMANDPARAMS2_4_GROUPID_OFFSET 16
#define KM_SSS_COMMANDPARAMS2_4_GROUPID_SIZE 2
#define KM_SSS_COMMANDPARAMS2_4_DOTRANSFERRING_OFFSET 18
#define KM_SSS_COMMANDPARAMS2_4_DOTRANSFERRING_SIZE 1
#define KM_SSS_COMMANDPARAMS2_4_DOLOADCOEFF_OFFSET 19
#define KM_SSS_COMMANDPARAMS2_4_DOLOADCOEFF_SIZE 3

/** bit field defines for km_sss_s#commandparams1_5 */
#define KM_SSS_COMMANDPARAMS1_5_PSSOFFSETSTART_OFFSET 0
#define KM_SSS_COMMANDPARAMS1_5_PSSOFFSETSTART_SIZE 15
#define KM_SSS_COMMANDPARAMS1_5_PSSOFFSETDURATION_OFFSET 16
#define KM_SSS_COMMANDPARAMS1_5_PSSOFFSETDURATION_SIZE 16

/** bit field defines for km_sss_s#commandparams2_5 */
#define KM_SSS_COMMANDPARAMS2_5_FBUFPTRSTART_OFFSET 0
#define KM_SSS_COMMANDPARAMS2_5_FBUFPTRSTART_SIZE 16
#define KM_SSS_COMMANDPARAMS2_5_GROUPID_OFFSET 16
#define KM_SSS_COMMANDPARAMS2_5_GROUPID_SIZE 2
#define KM_SSS_COMMANDPARAMS2_5_DOTRANSFERRING_OFFSET 18
#define KM_SSS_COMMANDPARAMS2_5_DOTRANSFERRING_SIZE 1
#define KM_SSS_COMMANDPARAMS2_5_DOLOADCOEFF_OFFSET 19
#define KM_SSS_COMMANDPARAMS2_5_DOLOADCOEFF_SIZE 3

/** bit field defines for km_sss_s#commandparams1_6 */
#define KM_SSS_COMMANDPARAMS1_6_PSSOFFSETSTART_OFFSET 0
#define KM_SSS_COMMANDPARAMS1_6_PSSOFFSETSTART_SIZE 15
#define KM_SSS_COMMANDPARAMS1_6_PSSOFFSETDURATION_OFFSET 16
#define KM_SSS_COMMANDPARAMS1_6_PSSOFFSETDURATION_SIZE 16

/** bit field defines for km_sss_s#commandparams2_6 */
#define KM_SSS_COMMANDPARAMS2_6_FBUFPTRSTART_OFFSET 0
#define KM_SSS_COMMANDPARAMS2_6_FBUFPTRSTART_SIZE 16
#define KM_SSS_COMMANDPARAMS2_6_GROUPID_OFFSET 16
#define KM_SSS_COMMANDPARAMS2_6_GROUPID_SIZE 2
#define KM_SSS_COMMANDPARAMS2_6_DOTRANSFERRING_OFFSET 18
#define KM_SSS_COMMANDPARAMS2_6_DOTRANSFERRING_SIZE 1
#define KM_SSS_COMMANDPARAMS2_6_DOLOADCOEFF_OFFSET 19
#define KM_SSS_COMMANDPARAMS2_6_DOLOADCOEFF_SIZE 3

/** bit field defines for km_sss_s#commandparams1_7 */
#define KM_SSS_COMMANDPARAMS1_7_PSSOFFSETSTART_OFFSET 0
#define KM_SSS_COMMANDPARAMS1_7_PSSOFFSETSTART_SIZE 15
#define KM_SSS_COMMANDPARAMS1_7_PSSOFFSETDURATION_OFFSET 16
#define KM_SSS_COMMANDPARAMS1_7_PSSOFFSETDURATION_SIZE 16

/** bit field defines for km_sss_s#commandparams2_7 */
#define KM_SSS_COMMANDPARAMS2_7_FBUFPTRSTART_OFFSET 0
#define KM_SSS_COMMANDPARAMS2_7_FBUFPTRSTART_SIZE 16
#define KM_SSS_COMMANDPARAMS2_7_GROUPID_OFFSET 16
#define KM_SSS_COMMANDPARAMS2_7_GROUPID_SIZE 2
#define KM_SSS_COMMANDPARAMS2_7_DOTRANSFERRING_OFFSET 18
#define KM_SSS_COMMANDPARAMS2_7_DOTRANSFERRING_SIZE 1
#define KM_SSS_COMMANDPARAMS2_7_DOLOADCOEFF_OFFSET 19
#define KM_SSS_COMMANDPARAMS2_7_DOLOADCOEFF_SIZE 3

/** bit field defines for km_sss_s#contextconfig_0 */
#define KM_SSS_CONTEXTCONFIG_0_GROUPID_OFFSET 0
#define KM_SSS_CONTEXTCONFIG_0_GROUPID_SIZE 2
#define KM_SSS_CONTEXTCONFIG_0_RESET_OFFSET 2
#define KM_SSS_CONTEXTCONFIG_0_RESET_SIZE 1
#define KM_SSS_CONTEXTCONFIG_0_RESETTXF_OFFSET 3
#define KM_SSS_CONTEXTCONFIG_0_RESETTXF_SIZE 1
#define KM_SSS_CONTEXTCONFIG_0_PDPENABLE_OFFSET 4
#define KM_SSS_CONTEXTCONFIG_0_PDPENABLE_SIZE 1
#define KM_SSS_CONTEXTCONFIG_0_NID2_OFFSET 5
#define KM_SSS_CONTEXTCONFIG_0_NID2_SIZE 2
#define KM_SSS_CONTEXTCONFIG_0_PSSOFFSET_OFFSET 7
#define KM_SSS_CONTEXTCONFIG_0_PSSOFFSET_SIZE 15
#define KM_SSS_CONTEXTCONFIG_0_DUPLEXMODE_OFFSET 22
#define KM_SSS_CONTEXTCONFIG_0_DUPLEXMODE_SIZE 2
/**  */
#define KM_SSS_CONTEXTCONFIG_0_DUPLEXMODE_ECP_FDD_VALUE 1
/**  */
#define KM_SSS_CONTEXTCONFIG_0_DUPLEXMODE_ECP_TDD_VALUE 3
/**  */
#define KM_SSS_CONTEXTCONFIG_0_DUPLEXMODE_NCP_FDD_VALUE 0
/**  */
#define KM_SSS_CONTEXTCONFIG_0_DUPLEXMODE_NCP_TDD_VALUE 2
#define KM_SSS_CONTEXTCONFIG_0_PSSCOVROTATE_OFFSET 24
#define KM_SSS_CONTEXTCONFIG_0_PSSCOVROTATE_SIZE 4
#define KM_SSS_CONTEXTCONFIG_0_PREFFTROTATE_OFFSET 28
#define KM_SSS_CONTEXTCONFIG_0_PREFFTROTATE_SIZE 4

/** bit field defines for km_sss_s#contextconfig1_0 */
#define KM_SSS_CONTEXTCONFIG1_0_FREQOFFSET_OFFSET 0
#define KM_SSS_CONTEXTCONFIG1_0_FREQOFFSET_SIZE 16
#define KM_SSS_CONTEXTCONFIG1_0_CHANESTFILTERID_OFFSET 16
#define KM_SSS_CONTEXTCONFIG1_0_CHANESTFILTERID_SIZE 2
#define KM_SSS_CONTEXTCONFIG1_0_DESTINATIONOFFSET_OFFSET 18
#define KM_SSS_CONTEXTCONFIG1_0_DESTINATIONOFFSET_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_0_PDPCONTEXTIDX_OFFSET 22
#define KM_SSS_CONTEXTCONFIG1_0_PDPCONTEXTIDX_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_0_PDPDESTINATIONOFFSET_OFFSET 26
#define KM_SSS_CONTEXTCONFIG1_0_PDPDESTINATIONOFFSET_SIZE 4

/** bit field defines for km_sss_s#contextconfig_1 */
#define KM_SSS_CONTEXTCONFIG_1_GROUPID_OFFSET 0
#define KM_SSS_CONTEXTCONFIG_1_GROUPID_SIZE 2
#define KM_SSS_CONTEXTCONFIG_1_RESET_OFFSET 2
#define KM_SSS_CONTEXTCONFIG_1_RESET_SIZE 1
#define KM_SSS_CONTEXTCONFIG_1_RESETTXF_OFFSET 3
#define KM_SSS_CONTEXTCONFIG_1_RESETTXF_SIZE 1
#define KM_SSS_CONTEXTCONFIG_1_PDPENABLE_OFFSET 4
#define KM_SSS_CONTEXTCONFIG_1_PDPENABLE_SIZE 1
#define KM_SSS_CONTEXTCONFIG_1_NID2_OFFSET 5
#define KM_SSS_CONTEXTCONFIG_1_NID2_SIZE 2
#define KM_SSS_CONTEXTCONFIG_1_PSSOFFSET_OFFSET 7
#define KM_SSS_CONTEXTCONFIG_1_PSSOFFSET_SIZE 15
#define KM_SSS_CONTEXTCONFIG_1_DUPLEXMODE_OFFSET 22
#define KM_SSS_CONTEXTCONFIG_1_DUPLEXMODE_SIZE 2
/**  */
#define KM_SSS_CONTEXTCONFIG_1_DUPLEXMODE_ECP_FDD_VALUE 1
/**  */
#define KM_SSS_CONTEXTCONFIG_1_DUPLEXMODE_ECP_TDD_VALUE 3
/**  */
#define KM_SSS_CONTEXTCONFIG_1_DUPLEXMODE_NCP_FDD_VALUE 0
/**  */
#define KM_SSS_CONTEXTCONFIG_1_DUPLEXMODE_NCP_TDD_VALUE 2
#define KM_SSS_CONTEXTCONFIG_1_PSSCOVROTATE_OFFSET 24
#define KM_SSS_CONTEXTCONFIG_1_PSSCOVROTATE_SIZE 4
#define KM_SSS_CONTEXTCONFIG_1_PREFFTROTATE_OFFSET 28
#define KM_SSS_CONTEXTCONFIG_1_PREFFTROTATE_SIZE 4

/** bit field defines for km_sss_s#contextconfig1_1 */
#define KM_SSS_CONTEXTCONFIG1_1_FREQOFFSET_OFFSET 0
#define KM_SSS_CONTEXTCONFIG1_1_FREQOFFSET_SIZE 16
#define KM_SSS_CONTEXTCONFIG1_1_CHANESTFILTERID_OFFSET 16
#define KM_SSS_CONTEXTCONFIG1_1_CHANESTFILTERID_SIZE 2
#define KM_SSS_CONTEXTCONFIG1_1_DESTINATIONOFFSET_OFFSET 18
#define KM_SSS_CONTEXTCONFIG1_1_DESTINATIONOFFSET_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_1_PDPCONTEXTIDX_OFFSET 22
#define KM_SSS_CONTEXTCONFIG1_1_PDPCONTEXTIDX_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_1_PDPDESTINATIONOFFSET_OFFSET 26
#define KM_SSS_CONTEXTCONFIG1_1_PDPDESTINATIONOFFSET_SIZE 4

/** bit field defines for km_sss_s#contextconfig_2 */
#define KM_SSS_CONTEXTCONFIG_2_GROUPID_OFFSET 0
#define KM_SSS_CONTEXTCONFIG_2_GROUPID_SIZE 2
#define KM_SSS_CONTEXTCONFIG_2_RESET_OFFSET 2
#define KM_SSS_CONTEXTCONFIG_2_RESET_SIZE 1
#define KM_SSS_CONTEXTCONFIG_2_RESETTXF_OFFSET 3
#define KM_SSS_CONTEXTCONFIG_2_RESETTXF_SIZE 1
#define KM_SSS_CONTEXTCONFIG_2_PDPENABLE_OFFSET 4
#define KM_SSS_CONTEXTCONFIG_2_PDPENABLE_SIZE 1
#define KM_SSS_CONTEXTCONFIG_2_NID2_OFFSET 5
#define KM_SSS_CONTEXTCONFIG_2_NID2_SIZE 2
#define KM_SSS_CONTEXTCONFIG_2_PSSOFFSET_OFFSET 7
#define KM_SSS_CONTEXTCONFIG_2_PSSOFFSET_SIZE 15
#define KM_SSS_CONTEXTCONFIG_2_DUPLEXMODE_OFFSET 22
#define KM_SSS_CONTEXTCONFIG_2_DUPLEXMODE_SIZE 2
/**  */
#define KM_SSS_CONTEXTCONFIG_2_DUPLEXMODE_ECP_FDD_VALUE 1
/**  */
#define KM_SSS_CONTEXTCONFIG_2_DUPLEXMODE_ECP_TDD_VALUE 3
/**  */
#define KM_SSS_CONTEXTCONFIG_2_DUPLEXMODE_NCP_FDD_VALUE 0
/**  */
#define KM_SSS_CONTEXTCONFIG_2_DUPLEXMODE_NCP_TDD_VALUE 2
#define KM_SSS_CONTEXTCONFIG_2_PSSCOVROTATE_OFFSET 24
#define KM_SSS_CONTEXTCONFIG_2_PSSCOVROTATE_SIZE 4
#define KM_SSS_CONTEXTCONFIG_2_PREFFTROTATE_OFFSET 28
#define KM_SSS_CONTEXTCONFIG_2_PREFFTROTATE_SIZE 4

/** bit field defines for km_sss_s#contextconfig1_2 */
#define KM_SSS_CONTEXTCONFIG1_2_FREQOFFSET_OFFSET 0
#define KM_SSS_CONTEXTCONFIG1_2_FREQOFFSET_SIZE 16
#define KM_SSS_CONTEXTCONFIG1_2_CHANESTFILTERID_OFFSET 16
#define KM_SSS_CONTEXTCONFIG1_2_CHANESTFILTERID_SIZE 2
#define KM_SSS_CONTEXTCONFIG1_2_DESTINATIONOFFSET_OFFSET 18
#define KM_SSS_CONTEXTCONFIG1_2_DESTINATIONOFFSET_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_2_PDPCONTEXTIDX_OFFSET 22
#define KM_SSS_CONTEXTCONFIG1_2_PDPCONTEXTIDX_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_2_PDPDESTINATIONOFFSET_OFFSET 26
#define KM_SSS_CONTEXTCONFIG1_2_PDPDESTINATIONOFFSET_SIZE 4

/** bit field defines for km_sss_s#contextconfig_3 */
#define KM_SSS_CONTEXTCONFIG_3_GROUPID_OFFSET 0
#define KM_SSS_CONTEXTCONFIG_3_GROUPID_SIZE 2
#define KM_SSS_CONTEXTCONFIG_3_RESET_OFFSET 2
#define KM_SSS_CONTEXTCONFIG_3_RESET_SIZE 1
#define KM_SSS_CONTEXTCONFIG_3_RESETTXF_OFFSET 3
#define KM_SSS_CONTEXTCONFIG_3_RESETTXF_SIZE 1
#define KM_SSS_CONTEXTCONFIG_3_PDPENABLE_OFFSET 4
#define KM_SSS_CONTEXTCONFIG_3_PDPENABLE_SIZE 1
#define KM_SSS_CONTEXTCONFIG_3_NID2_OFFSET 5
#define KM_SSS_CONTEXTCONFIG_3_NID2_SIZE 2
#define KM_SSS_CONTEXTCONFIG_3_PSSOFFSET_OFFSET 7
#define KM_SSS_CONTEXTCONFIG_3_PSSOFFSET_SIZE 15
#define KM_SSS_CONTEXTCONFIG_3_DUPLEXMODE_OFFSET 22
#define KM_SSS_CONTEXTCONFIG_3_DUPLEXMODE_SIZE 2
/**  */
#define KM_SSS_CONTEXTCONFIG_3_DUPLEXMODE_ECP_FDD_VALUE 1
/**  */
#define KM_SSS_CONTEXTCONFIG_3_DUPLEXMODE_ECP_TDD_VALUE 3
/**  */
#define KM_SSS_CONTEXTCONFIG_3_DUPLEXMODE_NCP_FDD_VALUE 0
/**  */
#define KM_SSS_CONTEXTCONFIG_3_DUPLEXMODE_NCP_TDD_VALUE 2
#define KM_SSS_CONTEXTCONFIG_3_PSSCOVROTATE_OFFSET 24
#define KM_SSS_CONTEXTCONFIG_3_PSSCOVROTATE_SIZE 4
#define KM_SSS_CONTEXTCONFIG_3_PREFFTROTATE_OFFSET 28
#define KM_SSS_CONTEXTCONFIG_3_PREFFTROTATE_SIZE 4

/** bit field defines for km_sss_s#contextconfig1_3 */
#define KM_SSS_CONTEXTCONFIG1_3_FREQOFFSET_OFFSET 0
#define KM_SSS_CONTEXTCONFIG1_3_FREQOFFSET_SIZE 16
#define KM_SSS_CONTEXTCONFIG1_3_CHANESTFILTERID_OFFSET 16
#define KM_SSS_CONTEXTCONFIG1_3_CHANESTFILTERID_SIZE 2
#define KM_SSS_CONTEXTCONFIG1_3_DESTINATIONOFFSET_OFFSET 18
#define KM_SSS_CONTEXTCONFIG1_3_DESTINATIONOFFSET_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_3_PDPCONTEXTIDX_OFFSET 22
#define KM_SSS_CONTEXTCONFIG1_3_PDPCONTEXTIDX_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_3_PDPDESTINATIONOFFSET_OFFSET 26
#define KM_SSS_CONTEXTCONFIG1_3_PDPDESTINATIONOFFSET_SIZE 4

/** bit field defines for km_sss_s#contextconfig_4 */
#define KM_SSS_CONTEXTCONFIG_4_GROUPID_OFFSET 0
#define KM_SSS_CONTEXTCONFIG_4_GROUPID_SIZE 2
#define KM_SSS_CONTEXTCONFIG_4_RESET_OFFSET 2
#define KM_SSS_CONTEXTCONFIG_4_RESET_SIZE 1
#define KM_SSS_CONTEXTCONFIG_4_RESETTXF_OFFSET 3
#define KM_SSS_CONTEXTCONFIG_4_RESETTXF_SIZE 1
#define KM_SSS_CONTEXTCONFIG_4_PDPENABLE_OFFSET 4
#define KM_SSS_CONTEXTCONFIG_4_PDPENABLE_SIZE 1
#define KM_SSS_CONTEXTCONFIG_4_NID2_OFFSET 5
#define KM_SSS_CONTEXTCONFIG_4_NID2_SIZE 2
#define KM_SSS_CONTEXTCONFIG_4_PSSOFFSET_OFFSET 7
#define KM_SSS_CONTEXTCONFIG_4_PSSOFFSET_SIZE 15
#define KM_SSS_CONTEXTCONFIG_4_DUPLEXMODE_OFFSET 22
#define KM_SSS_CONTEXTCONFIG_4_DUPLEXMODE_SIZE 2
/**  */
#define KM_SSS_CONTEXTCONFIG_4_DUPLEXMODE_ECP_FDD_VALUE 1
/**  */
#define KM_SSS_CONTEXTCONFIG_4_DUPLEXMODE_ECP_TDD_VALUE 3
/**  */
#define KM_SSS_CONTEXTCONFIG_4_DUPLEXMODE_NCP_FDD_VALUE 0
/**  */
#define KM_SSS_CONTEXTCONFIG_4_DUPLEXMODE_NCP_TDD_VALUE 2
#define KM_SSS_CONTEXTCONFIG_4_PSSCOVROTATE_OFFSET 24
#define KM_SSS_CONTEXTCONFIG_4_PSSCOVROTATE_SIZE 4
#define KM_SSS_CONTEXTCONFIG_4_PREFFTROTATE_OFFSET 28
#define KM_SSS_CONTEXTCONFIG_4_PREFFTROTATE_SIZE 4

/** bit field defines for km_sss_s#contextconfig1_4 */
#define KM_SSS_CONTEXTCONFIG1_4_FREQOFFSET_OFFSET 0
#define KM_SSS_CONTEXTCONFIG1_4_FREQOFFSET_SIZE 16
#define KM_SSS_CONTEXTCONFIG1_4_CHANESTFILTERID_OFFSET 16
#define KM_SSS_CONTEXTCONFIG1_4_CHANESTFILTERID_SIZE 2
#define KM_SSS_CONTEXTCONFIG1_4_DESTINATIONOFFSET_OFFSET 18
#define KM_SSS_CONTEXTCONFIG1_4_DESTINATIONOFFSET_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_4_PDPCONTEXTIDX_OFFSET 22
#define KM_SSS_CONTEXTCONFIG1_4_PDPCONTEXTIDX_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_4_PDPDESTINATIONOFFSET_OFFSET 26
#define KM_SSS_CONTEXTCONFIG1_4_PDPDESTINATIONOFFSET_SIZE 4

/** bit field defines for km_sss_s#contextconfig_5 */
#define KM_SSS_CONTEXTCONFIG_5_GROUPID_OFFSET 0
#define KM_SSS_CONTEXTCONFIG_5_GROUPID_SIZE 2
#define KM_SSS_CONTEXTCONFIG_5_RESET_OFFSET 2
#define KM_SSS_CONTEXTCONFIG_5_RESET_SIZE 1
#define KM_SSS_CONTEXTCONFIG_5_RESETTXF_OFFSET 3
#define KM_SSS_CONTEXTCONFIG_5_RESETTXF_SIZE 1
#define KM_SSS_CONTEXTCONFIG_5_PDPENABLE_OFFSET 4
#define KM_SSS_CONTEXTCONFIG_5_PDPENABLE_SIZE 1
#define KM_SSS_CONTEXTCONFIG_5_NID2_OFFSET 5
#define KM_SSS_CONTEXTCONFIG_5_NID2_SIZE 2
#define KM_SSS_CONTEXTCONFIG_5_PSSOFFSET_OFFSET 7
#define KM_SSS_CONTEXTCONFIG_5_PSSOFFSET_SIZE 15
#define KM_SSS_CONTEXTCONFIG_5_DUPLEXMODE_OFFSET 22
#define KM_SSS_CONTEXTCONFIG_5_DUPLEXMODE_SIZE 2
/**  */
#define KM_SSS_CONTEXTCONFIG_5_DUPLEXMODE_ECP_FDD_VALUE 1
/**  */
#define KM_SSS_CONTEXTCONFIG_5_DUPLEXMODE_ECP_TDD_VALUE 3
/**  */
#define KM_SSS_CONTEXTCONFIG_5_DUPLEXMODE_NCP_FDD_VALUE 0
/**  */
#define KM_SSS_CONTEXTCONFIG_5_DUPLEXMODE_NCP_TDD_VALUE 2
#define KM_SSS_CONTEXTCONFIG_5_PSSCOVROTATE_OFFSET 24
#define KM_SSS_CONTEXTCONFIG_5_PSSCOVROTATE_SIZE 4
#define KM_SSS_CONTEXTCONFIG_5_PREFFTROTATE_OFFSET 28
#define KM_SSS_CONTEXTCONFIG_5_PREFFTROTATE_SIZE 4

/** bit field defines for km_sss_s#contextconfig1_5 */
#define KM_SSS_CONTEXTCONFIG1_5_FREQOFFSET_OFFSET 0
#define KM_SSS_CONTEXTCONFIG1_5_FREQOFFSET_SIZE 16
#define KM_SSS_CONTEXTCONFIG1_5_CHANESTFILTERID_OFFSET 16
#define KM_SSS_CONTEXTCONFIG1_5_CHANESTFILTERID_SIZE 2
#define KM_SSS_CONTEXTCONFIG1_5_DESTINATIONOFFSET_OFFSET 18
#define KM_SSS_CONTEXTCONFIG1_5_DESTINATIONOFFSET_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_5_PDPCONTEXTIDX_OFFSET 22
#define KM_SSS_CONTEXTCONFIG1_5_PDPCONTEXTIDX_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_5_PDPDESTINATIONOFFSET_OFFSET 26
#define KM_SSS_CONTEXTCONFIG1_5_PDPDESTINATIONOFFSET_SIZE 4

/** bit field defines for km_sss_s#contextconfig_6 */
#define KM_SSS_CONTEXTCONFIG_6_GROUPID_OFFSET 0
#define KM_SSS_CONTEXTCONFIG_6_GROUPID_SIZE 2
#define KM_SSS_CONTEXTCONFIG_6_RESET_OFFSET 2
#define KM_SSS_CONTEXTCONFIG_6_RESET_SIZE 1
#define KM_SSS_CONTEXTCONFIG_6_RESETTXF_OFFSET 3
#define KM_SSS_CONTEXTCONFIG_6_RESETTXF_SIZE 1
#define KM_SSS_CONTEXTCONFIG_6_PDPENABLE_OFFSET 4
#define KM_SSS_CONTEXTCONFIG_6_PDPENABLE_SIZE 1
#define KM_SSS_CONTEXTCONFIG_6_NID2_OFFSET 5
#define KM_SSS_CONTEXTCONFIG_6_NID2_SIZE 2
#define KM_SSS_CONTEXTCONFIG_6_PSSOFFSET_OFFSET 7
#define KM_SSS_CONTEXTCONFIG_6_PSSOFFSET_SIZE 15
#define KM_SSS_CONTEXTCONFIG_6_DUPLEXMODE_OFFSET 22
#define KM_SSS_CONTEXTCONFIG_6_DUPLEXMODE_SIZE 2
/**  */
#define KM_SSS_CONTEXTCONFIG_6_DUPLEXMODE_ECP_FDD_VALUE 1
/**  */
#define KM_SSS_CONTEXTCONFIG_6_DUPLEXMODE_ECP_TDD_VALUE 3
/**  */
#define KM_SSS_CONTEXTCONFIG_6_DUPLEXMODE_NCP_FDD_VALUE 0
/**  */
#define KM_SSS_CONTEXTCONFIG_6_DUPLEXMODE_NCP_TDD_VALUE 2
#define KM_SSS_CONTEXTCONFIG_6_PSSCOVROTATE_OFFSET 24
#define KM_SSS_CONTEXTCONFIG_6_PSSCOVROTATE_SIZE 4
#define KM_SSS_CONTEXTCONFIG_6_PREFFTROTATE_OFFSET 28
#define KM_SSS_CONTEXTCONFIG_6_PREFFTROTATE_SIZE 4

/** bit field defines for km_sss_s#contextconfig1_6 */
#define KM_SSS_CONTEXTCONFIG1_6_FREQOFFSET_OFFSET 0
#define KM_SSS_CONTEXTCONFIG1_6_FREQOFFSET_SIZE 16
#define KM_SSS_CONTEXTCONFIG1_6_CHANESTFILTERID_OFFSET 16
#define KM_SSS_CONTEXTCONFIG1_6_CHANESTFILTERID_SIZE 2
#define KM_SSS_CONTEXTCONFIG1_6_DESTINATIONOFFSET_OFFSET 18
#define KM_SSS_CONTEXTCONFIG1_6_DESTINATIONOFFSET_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_6_PDPCONTEXTIDX_OFFSET 22
#define KM_SSS_CONTEXTCONFIG1_6_PDPCONTEXTIDX_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_6_PDPDESTINATIONOFFSET_OFFSET 26
#define KM_SSS_CONTEXTCONFIG1_6_PDPDESTINATIONOFFSET_SIZE 4

/** bit field defines for km_sss_s#contextconfig_7 */
#define KM_SSS_CONTEXTCONFIG_7_GROUPID_OFFSET 0
#define KM_SSS_CONTEXTCONFIG_7_GROUPID_SIZE 2
#define KM_SSS_CONTEXTCONFIG_7_RESET_OFFSET 2
#define KM_SSS_CONTEXTCONFIG_7_RESET_SIZE 1
#define KM_SSS_CONTEXTCONFIG_7_RESETTXF_OFFSET 3
#define KM_SSS_CONTEXTCONFIG_7_RESETTXF_SIZE 1
#define KM_SSS_CONTEXTCONFIG_7_PDPENABLE_OFFSET 4
#define KM_SSS_CONTEXTCONFIG_7_PDPENABLE_SIZE 1
#define KM_SSS_CONTEXTCONFIG_7_NID2_OFFSET 5
#define KM_SSS_CONTEXTCONFIG_7_NID2_SIZE 2
#define KM_SSS_CONTEXTCONFIG_7_PSSOFFSET_OFFSET 7
#define KM_SSS_CONTEXTCONFIG_7_PSSOFFSET_SIZE 15
#define KM_SSS_CONTEXTCONFIG_7_DUPLEXMODE_OFFSET 22
#define KM_SSS_CONTEXTCONFIG_7_DUPLEXMODE_SIZE 2
/**  */
#define KM_SSS_CONTEXTCONFIG_7_DUPLEXMODE_ECP_FDD_VALUE 1
/**  */
#define KM_SSS_CONTEXTCONFIG_7_DUPLEXMODE_ECP_TDD_VALUE 3
/**  */
#define KM_SSS_CONTEXTCONFIG_7_DUPLEXMODE_NCP_FDD_VALUE 0
/**  */
#define KM_SSS_CONTEXTCONFIG_7_DUPLEXMODE_NCP_TDD_VALUE 2
#define KM_SSS_CONTEXTCONFIG_7_PSSCOVROTATE_OFFSET 24
#define KM_SSS_CONTEXTCONFIG_7_PSSCOVROTATE_SIZE 4
#define KM_SSS_CONTEXTCONFIG_7_PREFFTROTATE_OFFSET 28
#define KM_SSS_CONTEXTCONFIG_7_PREFFTROTATE_SIZE 4

/** bit field defines for km_sss_s#contextconfig1_7 */
#define KM_SSS_CONTEXTCONFIG1_7_FREQOFFSET_OFFSET 0
#define KM_SSS_CONTEXTCONFIG1_7_FREQOFFSET_SIZE 16
#define KM_SSS_CONTEXTCONFIG1_7_CHANESTFILTERID_OFFSET 16
#define KM_SSS_CONTEXTCONFIG1_7_CHANESTFILTERID_SIZE 2
#define KM_SSS_CONTEXTCONFIG1_7_DESTINATIONOFFSET_OFFSET 18
#define KM_SSS_CONTEXTCONFIG1_7_DESTINATIONOFFSET_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_7_PDPCONTEXTIDX_OFFSET 22
#define KM_SSS_CONTEXTCONFIG1_7_PDPCONTEXTIDX_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_7_PDPDESTINATIONOFFSET_OFFSET 26
#define KM_SSS_CONTEXTCONFIG1_7_PDPDESTINATIONOFFSET_SIZE 4

/** bit field defines for km_sss_s#contextconfig_8 */
#define KM_SSS_CONTEXTCONFIG_8_GROUPID_OFFSET 0
#define KM_SSS_CONTEXTCONFIG_8_GROUPID_SIZE 2
#define KM_SSS_CONTEXTCONFIG_8_RESET_OFFSET 2
#define KM_SSS_CONTEXTCONFIG_8_RESET_SIZE 1
#define KM_SSS_CONTEXTCONFIG_8_RESETTXF_OFFSET 3
#define KM_SSS_CONTEXTCONFIG_8_RESETTXF_SIZE 1
#define KM_SSS_CONTEXTCONFIG_8_PDPENABLE_OFFSET 4
#define KM_SSS_CONTEXTCONFIG_8_PDPENABLE_SIZE 1
#define KM_SSS_CONTEXTCONFIG_8_NID2_OFFSET 5
#define KM_SSS_CONTEXTCONFIG_8_NID2_SIZE 2
#define KM_SSS_CONTEXTCONFIG_8_PSSOFFSET_OFFSET 7
#define KM_SSS_CONTEXTCONFIG_8_PSSOFFSET_SIZE 15
#define KM_SSS_CONTEXTCONFIG_8_DUPLEXMODE_OFFSET 22
#define KM_SSS_CONTEXTCONFIG_8_DUPLEXMODE_SIZE 2
/**  */
#define KM_SSS_CONTEXTCONFIG_8_DUPLEXMODE_ECP_FDD_VALUE 1
/**  */
#define KM_SSS_CONTEXTCONFIG_8_DUPLEXMODE_ECP_TDD_VALUE 3
/**  */
#define KM_SSS_CONTEXTCONFIG_8_DUPLEXMODE_NCP_FDD_VALUE 0
/**  */
#define KM_SSS_CONTEXTCONFIG_8_DUPLEXMODE_NCP_TDD_VALUE 2
#define KM_SSS_CONTEXTCONFIG_8_PSSCOVROTATE_OFFSET 24
#define KM_SSS_CONTEXTCONFIG_8_PSSCOVROTATE_SIZE 4
#define KM_SSS_CONTEXTCONFIG_8_PREFFTROTATE_OFFSET 28
#define KM_SSS_CONTEXTCONFIG_8_PREFFTROTATE_SIZE 4

/** bit field defines for km_sss_s#contextconfig1_8 */
#define KM_SSS_CONTEXTCONFIG1_8_FREQOFFSET_OFFSET 0
#define KM_SSS_CONTEXTCONFIG1_8_FREQOFFSET_SIZE 16
#define KM_SSS_CONTEXTCONFIG1_8_CHANESTFILTERID_OFFSET 16
#define KM_SSS_CONTEXTCONFIG1_8_CHANESTFILTERID_SIZE 2
#define KM_SSS_CONTEXTCONFIG1_8_DESTINATIONOFFSET_OFFSET 18
#define KM_SSS_CONTEXTCONFIG1_8_DESTINATIONOFFSET_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_8_PDPCONTEXTIDX_OFFSET 22
#define KM_SSS_CONTEXTCONFIG1_8_PDPCONTEXTIDX_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_8_PDPDESTINATIONOFFSET_OFFSET 26
#define KM_SSS_CONTEXTCONFIG1_8_PDPDESTINATIONOFFSET_SIZE 4

/** bit field defines for km_sss_s#contextconfig_9 */
#define KM_SSS_CONTEXTCONFIG_9_GROUPID_OFFSET 0
#define KM_SSS_CONTEXTCONFIG_9_GROUPID_SIZE 2
#define KM_SSS_CONTEXTCONFIG_9_RESET_OFFSET 2
#define KM_SSS_CONTEXTCONFIG_9_RESET_SIZE 1
#define KM_SSS_CONTEXTCONFIG_9_RESETTXF_OFFSET 3
#define KM_SSS_CONTEXTCONFIG_9_RESETTXF_SIZE 1
#define KM_SSS_CONTEXTCONFIG_9_PDPENABLE_OFFSET 4
#define KM_SSS_CONTEXTCONFIG_9_PDPENABLE_SIZE 1
#define KM_SSS_CONTEXTCONFIG_9_NID2_OFFSET 5
#define KM_SSS_CONTEXTCONFIG_9_NID2_SIZE 2
#define KM_SSS_CONTEXTCONFIG_9_PSSOFFSET_OFFSET 7
#define KM_SSS_CONTEXTCONFIG_9_PSSOFFSET_SIZE 15
#define KM_SSS_CONTEXTCONFIG_9_DUPLEXMODE_OFFSET 22
#define KM_SSS_CONTEXTCONFIG_9_DUPLEXMODE_SIZE 2
/**  */
#define KM_SSS_CONTEXTCONFIG_9_DUPLEXMODE_ECP_FDD_VALUE 1
/**  */
#define KM_SSS_CONTEXTCONFIG_9_DUPLEXMODE_ECP_TDD_VALUE 3
/**  */
#define KM_SSS_CONTEXTCONFIG_9_DUPLEXMODE_NCP_FDD_VALUE 0
/**  */
#define KM_SSS_CONTEXTCONFIG_9_DUPLEXMODE_NCP_TDD_VALUE 2
#define KM_SSS_CONTEXTCONFIG_9_PSSCOVROTATE_OFFSET 24
#define KM_SSS_CONTEXTCONFIG_9_PSSCOVROTATE_SIZE 4
#define KM_SSS_CONTEXTCONFIG_9_PREFFTROTATE_OFFSET 28
#define KM_SSS_CONTEXTCONFIG_9_PREFFTROTATE_SIZE 4

/** bit field defines for km_sss_s#contextconfig1_9 */
#define KM_SSS_CONTEXTCONFIG1_9_FREQOFFSET_OFFSET 0
#define KM_SSS_CONTEXTCONFIG1_9_FREQOFFSET_SIZE 16
#define KM_SSS_CONTEXTCONFIG1_9_CHANESTFILTERID_OFFSET 16
#define KM_SSS_CONTEXTCONFIG1_9_CHANESTFILTERID_SIZE 2
#define KM_SSS_CONTEXTCONFIG1_9_DESTINATIONOFFSET_OFFSET 18
#define KM_SSS_CONTEXTCONFIG1_9_DESTINATIONOFFSET_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_9_PDPCONTEXTIDX_OFFSET 22
#define KM_SSS_CONTEXTCONFIG1_9_PDPCONTEXTIDX_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_9_PDPDESTINATIONOFFSET_OFFSET 26
#define KM_SSS_CONTEXTCONFIG1_9_PDPDESTINATIONOFFSET_SIZE 4

/** bit field defines for km_sss_s#contextconfig_10 */
#define KM_SSS_CONTEXTCONFIG_10_GROUPID_OFFSET 0
#define KM_SSS_CONTEXTCONFIG_10_GROUPID_SIZE 2
#define KM_SSS_CONTEXTCONFIG_10_RESET_OFFSET 2
#define KM_SSS_CONTEXTCONFIG_10_RESET_SIZE 1
#define KM_SSS_CONTEXTCONFIG_10_RESETTXF_OFFSET 3
#define KM_SSS_CONTEXTCONFIG_10_RESETTXF_SIZE 1
#define KM_SSS_CONTEXTCONFIG_10_PDPENABLE_OFFSET 4
#define KM_SSS_CONTEXTCONFIG_10_PDPENABLE_SIZE 1
#define KM_SSS_CONTEXTCONFIG_10_NID2_OFFSET 5
#define KM_SSS_CONTEXTCONFIG_10_NID2_SIZE 2
#define KM_SSS_CONTEXTCONFIG_10_PSSOFFSET_OFFSET 7
#define KM_SSS_CONTEXTCONFIG_10_PSSOFFSET_SIZE 15
#define KM_SSS_CONTEXTCONFIG_10_DUPLEXMODE_OFFSET 22
#define KM_SSS_CONTEXTCONFIG_10_DUPLEXMODE_SIZE 2
/**  */
#define KM_SSS_CONTEXTCONFIG_10_DUPLEXMODE_ECP_FDD_VALUE 1
/**  */
#define KM_SSS_CONTEXTCONFIG_10_DUPLEXMODE_ECP_TDD_VALUE 3
/**  */
#define KM_SSS_CONTEXTCONFIG_10_DUPLEXMODE_NCP_FDD_VALUE 0
/**  */
#define KM_SSS_CONTEXTCONFIG_10_DUPLEXMODE_NCP_TDD_VALUE 2
#define KM_SSS_CONTEXTCONFIG_10_PSSCOVROTATE_OFFSET 24
#define KM_SSS_CONTEXTCONFIG_10_PSSCOVROTATE_SIZE 4
#define KM_SSS_CONTEXTCONFIG_10_PREFFTROTATE_OFFSET 28
#define KM_SSS_CONTEXTCONFIG_10_PREFFTROTATE_SIZE 4

/** bit field defines for km_sss_s#contextconfig1_10 */
#define KM_SSS_CONTEXTCONFIG1_10_FREQOFFSET_OFFSET 0
#define KM_SSS_CONTEXTCONFIG1_10_FREQOFFSET_SIZE 16
#define KM_SSS_CONTEXTCONFIG1_10_CHANESTFILTERID_OFFSET 16
#define KM_SSS_CONTEXTCONFIG1_10_CHANESTFILTERID_SIZE 2
#define KM_SSS_CONTEXTCONFIG1_10_DESTINATIONOFFSET_OFFSET 18
#define KM_SSS_CONTEXTCONFIG1_10_DESTINATIONOFFSET_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_10_PDPCONTEXTIDX_OFFSET 22
#define KM_SSS_CONTEXTCONFIG1_10_PDPCONTEXTIDX_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_10_PDPDESTINATIONOFFSET_OFFSET 26
#define KM_SSS_CONTEXTCONFIG1_10_PDPDESTINATIONOFFSET_SIZE 4

/** bit field defines for km_sss_s#contextconfig_11 */
#define KM_SSS_CONTEXTCONFIG_11_GROUPID_OFFSET 0
#define KM_SSS_CONTEXTCONFIG_11_GROUPID_SIZE 2
#define KM_SSS_CONTEXTCONFIG_11_RESET_OFFSET 2
#define KM_SSS_CONTEXTCONFIG_11_RESET_SIZE 1
#define KM_SSS_CONTEXTCONFIG_11_RESETTXF_OFFSET 3
#define KM_SSS_CONTEXTCONFIG_11_RESETTXF_SIZE 1
#define KM_SSS_CONTEXTCONFIG_11_PDPENABLE_OFFSET 4
#define KM_SSS_CONTEXTCONFIG_11_PDPENABLE_SIZE 1
#define KM_SSS_CONTEXTCONFIG_11_NID2_OFFSET 5
#define KM_SSS_CONTEXTCONFIG_11_NID2_SIZE 2
#define KM_SSS_CONTEXTCONFIG_11_PSSOFFSET_OFFSET 7
#define KM_SSS_CONTEXTCONFIG_11_PSSOFFSET_SIZE 15
#define KM_SSS_CONTEXTCONFIG_11_DUPLEXMODE_OFFSET 22
#define KM_SSS_CONTEXTCONFIG_11_DUPLEXMODE_SIZE 2
/**  */
#define KM_SSS_CONTEXTCONFIG_11_DUPLEXMODE_ECP_FDD_VALUE 1
/**  */
#define KM_SSS_CONTEXTCONFIG_11_DUPLEXMODE_ECP_TDD_VALUE 3
/**  */
#define KM_SSS_CONTEXTCONFIG_11_DUPLEXMODE_NCP_FDD_VALUE 0
/**  */
#define KM_SSS_CONTEXTCONFIG_11_DUPLEXMODE_NCP_TDD_VALUE 2
#define KM_SSS_CONTEXTCONFIG_11_PSSCOVROTATE_OFFSET 24
#define KM_SSS_CONTEXTCONFIG_11_PSSCOVROTATE_SIZE 4
#define KM_SSS_CONTEXTCONFIG_11_PREFFTROTATE_OFFSET 28
#define KM_SSS_CONTEXTCONFIG_11_PREFFTROTATE_SIZE 4

/** bit field defines for km_sss_s#contextconfig1_11 */
#define KM_SSS_CONTEXTCONFIG1_11_FREQOFFSET_OFFSET 0
#define KM_SSS_CONTEXTCONFIG1_11_FREQOFFSET_SIZE 16
#define KM_SSS_CONTEXTCONFIG1_11_CHANESTFILTERID_OFFSET 16
#define KM_SSS_CONTEXTCONFIG1_11_CHANESTFILTERID_SIZE 2
#define KM_SSS_CONTEXTCONFIG1_11_DESTINATIONOFFSET_OFFSET 18
#define KM_SSS_CONTEXTCONFIG1_11_DESTINATIONOFFSET_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_11_PDPCONTEXTIDX_OFFSET 22
#define KM_SSS_CONTEXTCONFIG1_11_PDPCONTEXTIDX_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_11_PDPDESTINATIONOFFSET_OFFSET 26
#define KM_SSS_CONTEXTCONFIG1_11_PDPDESTINATIONOFFSET_SIZE 4

/** bit field defines for km_sss_s#contextconfig_12 */
#define KM_SSS_CONTEXTCONFIG_12_GROUPID_OFFSET 0
#define KM_SSS_CONTEXTCONFIG_12_GROUPID_SIZE 2
#define KM_SSS_CONTEXTCONFIG_12_RESET_OFFSET 2
#define KM_SSS_CONTEXTCONFIG_12_RESET_SIZE 1
#define KM_SSS_CONTEXTCONFIG_12_RESETTXF_OFFSET 3
#define KM_SSS_CONTEXTCONFIG_12_RESETTXF_SIZE 1
#define KM_SSS_CONTEXTCONFIG_12_PDPENABLE_OFFSET 4
#define KM_SSS_CONTEXTCONFIG_12_PDPENABLE_SIZE 1
#define KM_SSS_CONTEXTCONFIG_12_NID2_OFFSET 5
#define KM_SSS_CONTEXTCONFIG_12_NID2_SIZE 2
#define KM_SSS_CONTEXTCONFIG_12_PSSOFFSET_OFFSET 7
#define KM_SSS_CONTEXTCONFIG_12_PSSOFFSET_SIZE 15
#define KM_SSS_CONTEXTCONFIG_12_DUPLEXMODE_OFFSET 22
#define KM_SSS_CONTEXTCONFIG_12_DUPLEXMODE_SIZE 2
/**  */
#define KM_SSS_CONTEXTCONFIG_12_DUPLEXMODE_ECP_FDD_VALUE 1
/**  */
#define KM_SSS_CONTEXTCONFIG_12_DUPLEXMODE_ECP_TDD_VALUE 3
/**  */
#define KM_SSS_CONTEXTCONFIG_12_DUPLEXMODE_NCP_FDD_VALUE 0
/**  */
#define KM_SSS_CONTEXTCONFIG_12_DUPLEXMODE_NCP_TDD_VALUE 2
#define KM_SSS_CONTEXTCONFIG_12_PSSCOVROTATE_OFFSET 24
#define KM_SSS_CONTEXTCONFIG_12_PSSCOVROTATE_SIZE 4
#define KM_SSS_CONTEXTCONFIG_12_PREFFTROTATE_OFFSET 28
#define KM_SSS_CONTEXTCONFIG_12_PREFFTROTATE_SIZE 4

/** bit field defines for km_sss_s#contextconfig1_12 */
#define KM_SSS_CONTEXTCONFIG1_12_FREQOFFSET_OFFSET 0
#define KM_SSS_CONTEXTCONFIG1_12_FREQOFFSET_SIZE 16
#define KM_SSS_CONTEXTCONFIG1_12_CHANESTFILTERID_OFFSET 16
#define KM_SSS_CONTEXTCONFIG1_12_CHANESTFILTERID_SIZE 2
#define KM_SSS_CONTEXTCONFIG1_12_DESTINATIONOFFSET_OFFSET 18
#define KM_SSS_CONTEXTCONFIG1_12_DESTINATIONOFFSET_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_12_PDPCONTEXTIDX_OFFSET 22
#define KM_SSS_CONTEXTCONFIG1_12_PDPCONTEXTIDX_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_12_PDPDESTINATIONOFFSET_OFFSET 26
#define KM_SSS_CONTEXTCONFIG1_12_PDPDESTINATIONOFFSET_SIZE 4

/** bit field defines for km_sss_s#contextconfig_13 */
#define KM_SSS_CONTEXTCONFIG_13_GROUPID_OFFSET 0
#define KM_SSS_CONTEXTCONFIG_13_GROUPID_SIZE 2
#define KM_SSS_CONTEXTCONFIG_13_RESET_OFFSET 2
#define KM_SSS_CONTEXTCONFIG_13_RESET_SIZE 1
#define KM_SSS_CONTEXTCONFIG_13_RESETTXF_OFFSET 3
#define KM_SSS_CONTEXTCONFIG_13_RESETTXF_SIZE 1
#define KM_SSS_CONTEXTCONFIG_13_PDPENABLE_OFFSET 4
#define KM_SSS_CONTEXTCONFIG_13_PDPENABLE_SIZE 1
#define KM_SSS_CONTEXTCONFIG_13_NID2_OFFSET 5
#define KM_SSS_CONTEXTCONFIG_13_NID2_SIZE 2
#define KM_SSS_CONTEXTCONFIG_13_PSSOFFSET_OFFSET 7
#define KM_SSS_CONTEXTCONFIG_13_PSSOFFSET_SIZE 15
#define KM_SSS_CONTEXTCONFIG_13_DUPLEXMODE_OFFSET 22
#define KM_SSS_CONTEXTCONFIG_13_DUPLEXMODE_SIZE 2
/**  */
#define KM_SSS_CONTEXTCONFIG_13_DUPLEXMODE_ECP_FDD_VALUE 1
/**  */
#define KM_SSS_CONTEXTCONFIG_13_DUPLEXMODE_ECP_TDD_VALUE 3
/**  */
#define KM_SSS_CONTEXTCONFIG_13_DUPLEXMODE_NCP_FDD_VALUE 0
/**  */
#define KM_SSS_CONTEXTCONFIG_13_DUPLEXMODE_NCP_TDD_VALUE 2
#define KM_SSS_CONTEXTCONFIG_13_PSSCOVROTATE_OFFSET 24
#define KM_SSS_CONTEXTCONFIG_13_PSSCOVROTATE_SIZE 4
#define KM_SSS_CONTEXTCONFIG_13_PREFFTROTATE_OFFSET 28
#define KM_SSS_CONTEXTCONFIG_13_PREFFTROTATE_SIZE 4

/** bit field defines for km_sss_s#contextconfig1_13 */
#define KM_SSS_CONTEXTCONFIG1_13_FREQOFFSET_OFFSET 0
#define KM_SSS_CONTEXTCONFIG1_13_FREQOFFSET_SIZE 16
#define KM_SSS_CONTEXTCONFIG1_13_CHANESTFILTERID_OFFSET 16
#define KM_SSS_CONTEXTCONFIG1_13_CHANESTFILTERID_SIZE 2
#define KM_SSS_CONTEXTCONFIG1_13_DESTINATIONOFFSET_OFFSET 18
#define KM_SSS_CONTEXTCONFIG1_13_DESTINATIONOFFSET_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_13_PDPCONTEXTIDX_OFFSET 22
#define KM_SSS_CONTEXTCONFIG1_13_PDPCONTEXTIDX_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_13_PDPDESTINATIONOFFSET_OFFSET 26
#define KM_SSS_CONTEXTCONFIG1_13_PDPDESTINATIONOFFSET_SIZE 4

/** bit field defines for km_sss_s#contextconfig_14 */
#define KM_SSS_CONTEXTCONFIG_14_GROUPID_OFFSET 0
#define KM_SSS_CONTEXTCONFIG_14_GROUPID_SIZE 2
#define KM_SSS_CONTEXTCONFIG_14_RESET_OFFSET 2
#define KM_SSS_CONTEXTCONFIG_14_RESET_SIZE 1
#define KM_SSS_CONTEXTCONFIG_14_RESETTXF_OFFSET 3
#define KM_SSS_CONTEXTCONFIG_14_RESETTXF_SIZE 1
#define KM_SSS_CONTEXTCONFIG_14_PDPENABLE_OFFSET 4
#define KM_SSS_CONTEXTCONFIG_14_PDPENABLE_SIZE 1
#define KM_SSS_CONTEXTCONFIG_14_NID2_OFFSET 5
#define KM_SSS_CONTEXTCONFIG_14_NID2_SIZE 2
#define KM_SSS_CONTEXTCONFIG_14_PSSOFFSET_OFFSET 7
#define KM_SSS_CONTEXTCONFIG_14_PSSOFFSET_SIZE 15
#define KM_SSS_CONTEXTCONFIG_14_DUPLEXMODE_OFFSET 22
#define KM_SSS_CONTEXTCONFIG_14_DUPLEXMODE_SIZE 2
/**  */
#define KM_SSS_CONTEXTCONFIG_14_DUPLEXMODE_ECP_FDD_VALUE 1
/**  */
#define KM_SSS_CONTEXTCONFIG_14_DUPLEXMODE_ECP_TDD_VALUE 3
/**  */
#define KM_SSS_CONTEXTCONFIG_14_DUPLEXMODE_NCP_FDD_VALUE 0
/**  */
#define KM_SSS_CONTEXTCONFIG_14_DUPLEXMODE_NCP_TDD_VALUE 2
#define KM_SSS_CONTEXTCONFIG_14_PSSCOVROTATE_OFFSET 24
#define KM_SSS_CONTEXTCONFIG_14_PSSCOVROTATE_SIZE 4
#define KM_SSS_CONTEXTCONFIG_14_PREFFTROTATE_OFFSET 28
#define KM_SSS_CONTEXTCONFIG_14_PREFFTROTATE_SIZE 4

/** bit field defines for km_sss_s#contextconfig1_14 */
#define KM_SSS_CONTEXTCONFIG1_14_FREQOFFSET_OFFSET 0
#define KM_SSS_CONTEXTCONFIG1_14_FREQOFFSET_SIZE 16
#define KM_SSS_CONTEXTCONFIG1_14_CHANESTFILTERID_OFFSET 16
#define KM_SSS_CONTEXTCONFIG1_14_CHANESTFILTERID_SIZE 2
#define KM_SSS_CONTEXTCONFIG1_14_DESTINATIONOFFSET_OFFSET 18
#define KM_SSS_CONTEXTCONFIG1_14_DESTINATIONOFFSET_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_14_PDPCONTEXTIDX_OFFSET 22
#define KM_SSS_CONTEXTCONFIG1_14_PDPCONTEXTIDX_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_14_PDPDESTINATIONOFFSET_OFFSET 26
#define KM_SSS_CONTEXTCONFIG1_14_PDPDESTINATIONOFFSET_SIZE 4

/** bit field defines for km_sss_s#contextconfig_15 */
#define KM_SSS_CONTEXTCONFIG_15_GROUPID_OFFSET 0
#define KM_SSS_CONTEXTCONFIG_15_GROUPID_SIZE 2
#define KM_SSS_CONTEXTCONFIG_15_RESET_OFFSET 2
#define KM_SSS_CONTEXTCONFIG_15_RESET_SIZE 1
#define KM_SSS_CONTEXTCONFIG_15_RESETTXF_OFFSET 3
#define KM_SSS_CONTEXTCONFIG_15_RESETTXF_SIZE 1
#define KM_SSS_CONTEXTCONFIG_15_PDPENABLE_OFFSET 4
#define KM_SSS_CONTEXTCONFIG_15_PDPENABLE_SIZE 1
#define KM_SSS_CONTEXTCONFIG_15_NID2_OFFSET 5
#define KM_SSS_CONTEXTCONFIG_15_NID2_SIZE 2
#define KM_SSS_CONTEXTCONFIG_15_PSSOFFSET_OFFSET 7
#define KM_SSS_CONTEXTCONFIG_15_PSSOFFSET_SIZE 15
#define KM_SSS_CONTEXTCONFIG_15_DUPLEXMODE_OFFSET 22
#define KM_SSS_CONTEXTCONFIG_15_DUPLEXMODE_SIZE 2
/**  */
#define KM_SSS_CONTEXTCONFIG_15_DUPLEXMODE_ECP_FDD_VALUE 1
/**  */
#define KM_SSS_CONTEXTCONFIG_15_DUPLEXMODE_ECP_TDD_VALUE 3
/**  */
#define KM_SSS_CONTEXTCONFIG_15_DUPLEXMODE_NCP_FDD_VALUE 0
/**  */
#define KM_SSS_CONTEXTCONFIG_15_DUPLEXMODE_NCP_TDD_VALUE 2
#define KM_SSS_CONTEXTCONFIG_15_PSSCOVROTATE_OFFSET 24
#define KM_SSS_CONTEXTCONFIG_15_PSSCOVROTATE_SIZE 4
#define KM_SSS_CONTEXTCONFIG_15_PREFFTROTATE_OFFSET 28
#define KM_SSS_CONTEXTCONFIG_15_PREFFTROTATE_SIZE 4

/** bit field defines for km_sss_s#contextconfig1_15 */
#define KM_SSS_CONTEXTCONFIG1_15_FREQOFFSET_OFFSET 0
#define KM_SSS_CONTEXTCONFIG1_15_FREQOFFSET_SIZE 16
#define KM_SSS_CONTEXTCONFIG1_15_CHANESTFILTERID_OFFSET 16
#define KM_SSS_CONTEXTCONFIG1_15_CHANESTFILTERID_SIZE 2
#define KM_SSS_CONTEXTCONFIG1_15_DESTINATIONOFFSET_OFFSET 18
#define KM_SSS_CONTEXTCONFIG1_15_DESTINATIONOFFSET_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_15_PDPCONTEXTIDX_OFFSET 22
#define KM_SSS_CONTEXTCONFIG1_15_PDPCONTEXTIDX_SIZE 4
#define KM_SSS_CONTEXTCONFIG1_15_PDPDESTINATIONOFFSET_OFFSET 26
#define KM_SSS_CONTEXTCONFIG1_15_PDPDESTINATIONOFFSET_SIZE 4

/** bit field defines for km_sss_s#transfertrigger */
#define KM_SSS_TRANSFERTRIGGER_COMBINECOUNTMIN_OFFSET 0
#define KM_SSS_TRANSFERTRIGGER_COMBINECOUNTMIN_SIZE 5
#define KM_SSS_TRANSFERTRIGGER_COMBINECOUNTITER_OFFSET 5
#define KM_SSS_TRANSFERTRIGGER_COMBINECOUNTITER_SIZE 5

/** bit field defines for km_sss_s#coefftransfer */
#define KM_SSS_COEFFTRANSFER_BASEADDR_OFFSET 6
#define KM_SSS_COEFFTRANSFER_BASEADDR_SIZE 26

/** bit field defines for km_sss_s#softcombtransfer */
#define KM_SSS_SOFTCOMBTRANSFER_BASEADDR_OFFSET 6
#define KM_SSS_SOFTCOMBTRANSFER_BASEADDR_SIZE 26

/** bit field defines for km_sss_s#psscovtransfer */
#define KM_SSS_PSSCOVTRANSFER_BASEADDR_OFFSET 6
#define KM_SSS_PSSCOVTRANSFER_BASEADDR_SIZE 26

/** bit field defines for km_sss_s#reader */
#define KM_SSS_READER_LOG2LEN_OFFSET 0
#define KM_SSS_READER_LOG2LEN_SIZE 4
#define KM_SSS_READER_PTR_OFFSET 4
#define KM_SSS_READER_PTR_SIZE 16
#define KM_SSS_READER_STATE_OFFSET 20
#define KM_SSS_READER_STATE_SIZE 2
/**  */
#define KM_SSS_READER_STATE_IDLE_VALUE 0
/** request is done. Wait for first sample */
#define KM_SSS_READER_STATE_REQ_VALUE 1
/** samples transfer */
#define KM_SSS_READER_STATE_TFR_VALUE 2

/** bit field defines for km_sss_s#eventstatus */
#define KM_SSS_EVENTSTATUS_TRANSFER_OFFSET 0
#define KM_SSS_EVENTSTATUS_TRANSFER_SIZE 16
#define KM_SSS_EVENTSTATUS_COMMANDCOMPLETE_OFFSET 16
#define KM_SSS_EVENTSTATUS_COMMANDCOMPLETE_SIZE 1
#define KM_SSS_EVENTSTATUS_WARNFLG_OFFSET 17
#define KM_SSS_EVENTSTATUS_WARNFLG_SIZE 1
#define KM_SSS_EVENTSTATUS_COMMANDWARNFLG_OFFSET 18
#define KM_SSS_EVENTSTATUS_COMMANDWARNFLG_SIZE 1

/** bit field defines for km_sss_s#interruptmask */
#define KM_SSS_INTERRUPTMASK_TRANSFER_OFFSET 0
#define KM_SSS_INTERRUPTMASK_TRANSFER_SIZE 16
#define KM_SSS_INTERRUPTMASK_COMMANDCOMPLETE_OFFSET 16
#define KM_SSS_INTERRUPTMASK_COMMANDCOMPLETE_SIZE 1
#define KM_SSS_INTERRUPTMASK_WARNFLG_OFFSET 17
#define KM_SSS_INTERRUPTMASK_WARNFLG_SIZE 1
#define KM_SSS_INTERRUPTMASK_COMMANDWARNFLG_OFFSET 18
#define KM_SSS_INTERRUPTMASK_COMMANDWARNFLG_SIZE 1

/** bit field defines for km_sss_s#interruptstatus */
#define KM_SSS_INTERRUPTSTATUS_TRANSFER_OFFSET 0
#define KM_SSS_INTERRUPTSTATUS_TRANSFER_SIZE 16
#define KM_SSS_INTERRUPTSTATUS_COMMANDCOMPLETE_OFFSET 16
#define KM_SSS_INTERRUPTSTATUS_COMMANDCOMPLETE_SIZE 1
#define KM_SSS_INTERRUPTSTATUS_WARNFLG_OFFSET 17
#define KM_SSS_INTERRUPTSTATUS_WARNFLG_SIZE 1
#define KM_SSS_INTERRUPTSTATUS_COMMANDWARNFLG_OFFSET 18
#define KM_SSS_INTERRUPTSTATUS_COMMANDWARNFLG_SIZE 1

/** bit field defines for km_sss_s#interruptpulsemask */
#define KM_SSS_INTERRUPTPULSEMASK_TRANSFER_OFFSET 0
#define KM_SSS_INTERRUPTPULSEMASK_TRANSFER_SIZE 16
#define KM_SSS_INTERRUPTPULSEMASK_COMMANDCOMPLETE_OFFSET 16
#define KM_SSS_INTERRUPTPULSEMASK_COMMANDCOMPLETE_SIZE 1
#define KM_SSS_INTERRUPTPULSEMASK_WARNFLG_OFFSET 17
#define KM_SSS_INTERRUPTPULSEMASK_WARNFLG_SIZE 1
#define KM_SSS_INTERRUPTPULSEMASK_COMMANDWARNFLG_OFFSET 18
#define KM_SSS_INTERRUPTPULSEMASK_COMMANDWARNFLG_SIZE 1

/** bit field defines for km_sss_s#hwobs */
#define KM_SSS_HWOBS_SEL_OFFSET 0
#define KM_SSS_HWOBS_SEL_SIZE 3
/** accumulator - (generally) from scratch memory to accumulator memory */
#define KM_SSS_HWOBS_SEL_ACCUM_VALUE 6
/** fsm channel estimate */
#define KM_SSS_HWOBS_SEL_CHEST_VALUE 4
/** data-path "function" state and datapath memory access */
#define KM_SSS_HWOBS_SEL_DP_VALUE 2
/** fsm equaliser */
#define KM_SSS_HWOBS_SEL_EQ_VALUE 5
/** fsm fft */
#define KM_SSS_HWOBS_SEL_FFT_VALUE 3
/** sss local memory UVM event trigger */
#define KM_SSS_HWOBS_SEL_MEM_TRIG_VALUE 1
/** All zeros */
#define KM_SSS_HWOBS_SEL_OFF_VALUE 0
/** transfer - (generally) from accumulator memory to axi interace */
#define KM_SSS_HWOBS_SEL_XFER_VALUE 7

/* EOF km_sss.h */
#endif
