; 
; Copyright (C) u-blox
; All rights reserved.
; This source file is the sole property of u-blox. Reproduction or utilization
; of this source in whole or part is forbidden without the written consent of
; u-blox.
; 
; FILE: km_sf.hs

KM_SF_HAL_VERSION EQU 5
KM_SF_MEMMARG EQU 0x000
KM_SF_MEMMARGEN0 EQU 0x004
KM_SF_MEMMARGEN1 EQU 0x008
KM_SF_MEMMARGLSB0 EQU 0x00C
KM_SF_MEMMARGLSB1 EQU 0x010
KM_SF_MEMMARGMSB0 EQU 0x014
KM_SF_MEMMARGMSB1 EQU 0x018
KM_SF_REFCLKCTRL EQU 0x01C
KM_SF_DVSHWCTRL EQU 0x020
KM_SF_PERIPHDMACTRL EQU 0x024
KM_SF_SDIOCTRL EQU 0x028
KM_SF_RFFERSET EQU 0x02C
KM_SF_OSPICTRLS EQU 0x030
KM_SF_OSPICTRLC EQU 0x034
KM_SF_OSPICTRL EQU 0x038
KM_SF_RFANARSTORIDES EQU 0x03C
KM_SF_RFANARSTORIDEC EQU 0x040
KM_SF_RFANARSTORIDE EQU 0x044
; EOF: km_sf.hs
   END
