; 
; Copyright (C) u-blox
; All rights reserved.
; This source file is the sole property of u-blox. Reproduction or utilization
; of this source in whole or part is forbidden without the written consent of
; u-blox.
; 
; FILE: km_ul_bpe.hs

KM_UL_BPE_HAL_VERSION EQU 2
KM_UL_BPE_CTRL EQU 0x000
KM_UL_BPE_TRANSPORTBLOCK EQU 0x004
KM_UL_BPE_SYMBOLBUFFER EQU 0x008
KM_UL_BPE_CQI EQU 0x00C
KM_UL_BPE_ACK EQU 0x010
KM_UL_BPE_CINIT EQU 0x014
KM_UL_BPE_MODES EQU 0x018
KM_UL_BPE_ULBPESTATUS EQU 0x01C
KM_UL_BPE_SRCADDR EQU 0x020
KM_UL_BPE_DSTADDR EQU 0x024
KM_UL_BPE_ENABLE EQU 0x028
KM_UL_BPE_RUNTRANSPORTBLOCK EQU 0x02C
KM_UL_BPE_RUNSYMBOLBUFFER EQU 0x030
KM_UL_BPE_RUNCQI EQU 0x034
KM_UL_BPE_RUNACK EQU 0x038
KM_UL_BPE_RUNCINIT EQU 0x03C
KM_UL_BPE_RUNMODES EQU 0x040
KM_UL_BPE_RUNSRCADDR EQU 0x044
KM_UL_BPE_RUNDSTADDR EQU 0x048
KM_UL_BPE_FAULT EQU 0x200
KM_UL_BPE_STAT EQU 0x204
KM_UL_BPE_FLTCLEAR EQU 0x300
KM_UL_BPE_FLTSTATUS EQU 0x304
KM_UL_BPE_FLTRAWSTATUS EQU 0x308
KM_UL_BPE_FLTMASKCLR EQU 0x30C
KM_UL_BPE_FLTMASKSET EQU 0x310
KM_UL_BPE_FLTMASKSTATUS EQU 0x314
KM_UL_BPE_PERIPHERALID4 EQU 0xFD0
KM_UL_BPE_PERIPHERALID5 EQU 0xFD4
KM_UL_BPE_PERIPHERALID6 EQU 0xFD8
KM_UL_BPE_PERIPHERALID7 EQU 0xFDC
KM_UL_BPE_PERIPHERALID0 EQU 0xFE0
KM_UL_BPE_PERIPHERALID1 EQU 0xFE4
KM_UL_BPE_PERIPHERALID2 EQU 0xFE8
KM_UL_BPE_PERIPHERALID3 EQU 0xFEC
KM_UL_BPE_COMPONENTID0 EQU 0xFF0
KM_UL_BPE_COMPONENTID1 EQU 0xFF4
KM_UL_BPE_COMPONENTID2 EQU 0xFF8
KM_UL_BPE_COMPONENTID3 EQU 0xFFC
; EOF: km_ul_bpe.hs
   END
