#ifndef INCLUDED_KMGO_RF_DIG_CCU
#define INCLUDED_KMGO_RF_DIG_CCU
/*
 * Copyright (C) u-blox 
 * All rights reserved. 
 * This source file is the sole property of u-blox. Reproduction or utilization 
 * of this source in whole or part is forbidden without the written consent of 
 * u-blox.
 *
 */

#include <stdint.h>

/** kmgo_rf_dig_ccu HAL Spreadsheet version number */
#define KMGO_RF_DIG_CCU_HAL_VERSION 1

/** RF Digital Clock Control Unit for Gottardo and Klein Matterhorn
*/
struct kmgo_rf_dig_ccu_s {
   /** Clock Gating Control.  Set to 1 to enable clock Enable at address offset 0x000, read-write */
   uint32_t ccuclkctrls;
   /** Clock Gating Control.  Set to 1 to enable clock Disable at address offset 0x004, read-write */
   uint32_t ccuclkctrlc;
   /** Clock Gating Control.  Set to 1 to enable clock at address offset 0x008, read-write */
   uint32_t ccuclkctrl;
   /** Reset Control (Active High).  Set to 1 to reset Enable at address offset 0x00C, read-write */
   uint32_t ccurstctrls;
   /** Reset Control (Active High).  Set to 1 to reset Disable at address offset 0x010, read-write */
   uint32_t ccurstctrlc;
   /** Reset Control (Active High).  Set to 1 to reset at address offset 0x014, read-write */
   uint32_t ccurstctrl;
   /** Clock Lost Detector Enables.  Disable clock lost detector to clear interrupt and reset the monitor logic at address offset 0x018, read-write */
   uint32_t clklost;
   /** Interrupt Mask. Set to 1 to enable interrupt at address offset 0x01C, read-write */
   uint32_t intmask;
   /** Interrupt Status.  Interrupt is active when set at address offset 0x020, read-only */
   uint32_t intstatus;
};

/** bit field defines for kmgo_rf_dig_ccu_s#ccuclkctrls */
#define KMGO_RF_DIG_CCU_CCUCLKCTRLS_RX1EN_OFFSET 0
#define KMGO_RF_DIG_CCU_CCUCLKCTRLS_RX1EN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRLS_RX2EN_OFFSET 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRLS_RX2EN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRLS_TX1EN_OFFSET 2
#define KMGO_RF_DIG_CCU_CCUCLKCTRLS_TX1EN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRLS_TX2EN_OFFSET 3
#define KMGO_RF_DIG_CCU_CCUCLKCTRLS_TX2EN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRLS_AUXEN_OFFSET 4
#define KMGO_RF_DIG_CCU_CCUCLKCTRLS_AUXEN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRLS_REFCLKEN_OFFSET 5
#define KMGO_RF_DIG_CCU_CCUCLKCTRLS_REFCLKEN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRLS_RX1DIGIFEN_OFFSET 8
#define KMGO_RF_DIG_CCU_CCUCLKCTRLS_RX1DIGIFEN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRLS_RX2DIGIFEN_OFFSET 9
#define KMGO_RF_DIG_CCU_CCUCLKCTRLS_RX2DIGIFEN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRLS_TX1DIGIFEN_OFFSET 10
#define KMGO_RF_DIG_CCU_CCUCLKCTRLS_TX1DIGIFEN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRLS_TX2DIGIFEN_OFFSET 11
#define KMGO_RF_DIG_CCU_CCUCLKCTRLS_TX2DIGIFEN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRLS_AUXDIGIFEN_OFFSET 12
#define KMGO_RF_DIG_CCU_CCUCLKCTRLS_AUXDIGIFEN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRLS_PLL1DIGIFEN_OFFSET 13
#define KMGO_RF_DIG_CCU_CCUCLKCTRLS_PLL1DIGIFEN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRLS_PLL2DIGIFEN_OFFSET 14
#define KMGO_RF_DIG_CCU_CCUCLKCTRLS_PLL2DIGIFEN_SIZE 1

/** bit field defines for kmgo_rf_dig_ccu_s#ccuclkctrlc */
#define KMGO_RF_DIG_CCU_CCUCLKCTRLC_RX1EN_OFFSET 0
#define KMGO_RF_DIG_CCU_CCUCLKCTRLC_RX1EN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRLC_RX2EN_OFFSET 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRLC_RX2EN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRLC_TX1EN_OFFSET 2
#define KMGO_RF_DIG_CCU_CCUCLKCTRLC_TX1EN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRLC_TX2EN_OFFSET 3
#define KMGO_RF_DIG_CCU_CCUCLKCTRLC_TX2EN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRLC_AUXEN_OFFSET 4
#define KMGO_RF_DIG_CCU_CCUCLKCTRLC_AUXEN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRLC_REFCLKEN_OFFSET 5
#define KMGO_RF_DIG_CCU_CCUCLKCTRLC_REFCLKEN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRLC_RX1DIGIFEN_OFFSET 8
#define KMGO_RF_DIG_CCU_CCUCLKCTRLC_RX1DIGIFEN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRLC_RX2DIGIFEN_OFFSET 9
#define KMGO_RF_DIG_CCU_CCUCLKCTRLC_RX2DIGIFEN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRLC_TX1DIGIFEN_OFFSET 10
#define KMGO_RF_DIG_CCU_CCUCLKCTRLC_TX1DIGIFEN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRLC_TX2DIGIFEN_OFFSET 11
#define KMGO_RF_DIG_CCU_CCUCLKCTRLC_TX2DIGIFEN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRLC_AUXDIGIFEN_OFFSET 12
#define KMGO_RF_DIG_CCU_CCUCLKCTRLC_AUXDIGIFEN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRLC_PLL1DIGIFEN_OFFSET 13
#define KMGO_RF_DIG_CCU_CCUCLKCTRLC_PLL1DIGIFEN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRLC_PLL2DIGIFEN_OFFSET 14
#define KMGO_RF_DIG_CCU_CCUCLKCTRLC_PLL2DIGIFEN_SIZE 1

/** bit field defines for kmgo_rf_dig_ccu_s#ccuclkctrl */
#define KMGO_RF_DIG_CCU_CCUCLKCTRL_RX1EN_OFFSET 0
#define KMGO_RF_DIG_CCU_CCUCLKCTRL_RX1EN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRL_RX2EN_OFFSET 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRL_RX2EN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRL_TX1EN_OFFSET 2
#define KMGO_RF_DIG_CCU_CCUCLKCTRL_TX1EN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRL_TX2EN_OFFSET 3
#define KMGO_RF_DIG_CCU_CCUCLKCTRL_TX2EN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRL_AUXEN_OFFSET 4
#define KMGO_RF_DIG_CCU_CCUCLKCTRL_AUXEN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRL_REFCLKEN_OFFSET 5
#define KMGO_RF_DIG_CCU_CCUCLKCTRL_REFCLKEN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRL_RX1DIGIFEN_OFFSET 8
#define KMGO_RF_DIG_CCU_CCUCLKCTRL_RX1DIGIFEN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRL_RX2DIGIFEN_OFFSET 9
#define KMGO_RF_DIG_CCU_CCUCLKCTRL_RX2DIGIFEN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRL_TX1DIGIFEN_OFFSET 10
#define KMGO_RF_DIG_CCU_CCUCLKCTRL_TX1DIGIFEN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRL_TX2DIGIFEN_OFFSET 11
#define KMGO_RF_DIG_CCU_CCUCLKCTRL_TX2DIGIFEN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRL_AUXDIGIFEN_OFFSET 12
#define KMGO_RF_DIG_CCU_CCUCLKCTRL_AUXDIGIFEN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRL_PLL1DIGIFEN_OFFSET 13
#define KMGO_RF_DIG_CCU_CCUCLKCTRL_PLL1DIGIFEN_SIZE 1
#define KMGO_RF_DIG_CCU_CCUCLKCTRL_PLL2DIGIFEN_OFFSET 14
#define KMGO_RF_DIG_CCU_CCUCLKCTRL_PLL2DIGIFEN_SIZE 1

/** bit field defines for kmgo_rf_dig_ccu_s#ccurstctrls */
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_RX1EN_OFFSET 0
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_RX1EN_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_RX2EN_OFFSET 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_RX2EN_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_TX1EN_OFFSET 2
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_TX1EN_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_TX2EN_OFFSET 3
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_TX2EN_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_AUXEN_OFFSET 4
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_AUXEN_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_REFCLKEN_OFFSET 5
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_REFCLKEN_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_TX1DIGIFRST_OFFSET 8
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_TX1DIGIFRST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_TX2DIGIFRST_OFFSET 9
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_TX2DIGIFRST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_TX1DIGIFDFERST_OFFSET 10
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_TX1DIGIFDFERST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_TX2DIGIFDFERST_OFFSET 11
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_TX2DIGIFDFERST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_RX1DIGIFRST_OFFSET 12
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_RX1DIGIFRST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_RX2DIGIFRST_OFFSET 13
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_RX2DIGIFRST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_AUXDIGIFRST_OFFSET 14
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_AUXDIGIFRST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_PLL1DIGIFRST_OFFSET 15
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_PLL1DIGIFRST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_PLL1DIGIFAPBRST_OFFSET 16
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_PLL1DIGIFAPBRST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_PLL2DIGIFRST_OFFSET 17
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_PLL2DIGIFRST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_PLL2DIGIFAPBRST_OFFSET 18
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_PLL2DIGIFAPBRST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_RFSYSTEM_OFFSET 31
#define KMGO_RF_DIG_CCU_CCURSTCTRLS_RFSYSTEM_SIZE 1

/** bit field defines for kmgo_rf_dig_ccu_s#ccurstctrlc */
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_RX1EN_OFFSET 0
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_RX1EN_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_RX2EN_OFFSET 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_RX2EN_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_TX1EN_OFFSET 2
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_TX1EN_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_TX2EN_OFFSET 3
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_TX2EN_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_AUXEN_OFFSET 4
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_AUXEN_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_REFCLKEN_OFFSET 5
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_REFCLKEN_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_TX1DIGIFRST_OFFSET 8
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_TX1DIGIFRST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_TX2DIGIFRST_OFFSET 9
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_TX2DIGIFRST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_TX1DIGIFDFERST_OFFSET 10
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_TX1DIGIFDFERST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_TX2DIGIFDFERST_OFFSET 11
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_TX2DIGIFDFERST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_RX1DIGIFRST_OFFSET 12
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_RX1DIGIFRST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_RX2DIGIFRST_OFFSET 13
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_RX2DIGIFRST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_AUXDIGIFRST_OFFSET 14
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_AUXDIGIFRST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_PLL1DIGIFRST_OFFSET 15
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_PLL1DIGIFRST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_PLL1DIGIFAPBRST_OFFSET 16
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_PLL1DIGIFAPBRST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_PLL2DIGIFRST_OFFSET 17
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_PLL2DIGIFRST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_PLL2DIGIFAPBRST_OFFSET 18
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_PLL2DIGIFAPBRST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_RFSYSTEM_OFFSET 31
#define KMGO_RF_DIG_CCU_CCURSTCTRLC_RFSYSTEM_SIZE 1

/** bit field defines for kmgo_rf_dig_ccu_s#ccurstctrl */
#define KMGO_RF_DIG_CCU_CCURSTCTRL_RX1EN_OFFSET 0
#define KMGO_RF_DIG_CCU_CCURSTCTRL_RX1EN_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRL_RX2EN_OFFSET 1
#define KMGO_RF_DIG_CCU_CCURSTCTRL_RX2EN_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRL_TX1EN_OFFSET 2
#define KMGO_RF_DIG_CCU_CCURSTCTRL_TX1EN_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRL_TX2EN_OFFSET 3
#define KMGO_RF_DIG_CCU_CCURSTCTRL_TX2EN_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRL_AUXEN_OFFSET 4
#define KMGO_RF_DIG_CCU_CCURSTCTRL_AUXEN_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRL_REFCLKEN_OFFSET 5
#define KMGO_RF_DIG_CCU_CCURSTCTRL_REFCLKEN_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRL_TX1DIGIFRST_OFFSET 8
#define KMGO_RF_DIG_CCU_CCURSTCTRL_TX1DIGIFRST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRL_TX2DIGIFRST_OFFSET 9
#define KMGO_RF_DIG_CCU_CCURSTCTRL_TX2DIGIFRST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRL_TX1DIGIFDFERST_OFFSET 10
#define KMGO_RF_DIG_CCU_CCURSTCTRL_TX1DIGIFDFERST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRL_TX2DIGIFDFERST_OFFSET 11
#define KMGO_RF_DIG_CCU_CCURSTCTRL_TX2DIGIFDFERST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRL_RX1DIGIFRST_OFFSET 12
#define KMGO_RF_DIG_CCU_CCURSTCTRL_RX1DIGIFRST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRL_RX2DIGIFRST_OFFSET 13
#define KMGO_RF_DIG_CCU_CCURSTCTRL_RX2DIGIFRST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRL_AUXDIGIFRST_OFFSET 14
#define KMGO_RF_DIG_CCU_CCURSTCTRL_AUXDIGIFRST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRL_PLL1DIGIFRST_OFFSET 15
#define KMGO_RF_DIG_CCU_CCURSTCTRL_PLL1DIGIFRST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRL_PLL1DIGIFAPBRST_OFFSET 16
#define KMGO_RF_DIG_CCU_CCURSTCTRL_PLL1DIGIFAPBRST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRL_PLL2DIGIFRST_OFFSET 17
#define KMGO_RF_DIG_CCU_CCURSTCTRL_PLL2DIGIFRST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRL_PLL2DIGIFAPBRST_OFFSET 18
#define KMGO_RF_DIG_CCU_CCURSTCTRL_PLL2DIGIFAPBRST_SIZE 1
#define KMGO_RF_DIG_CCU_CCURSTCTRL_RFSYSTEM_OFFSET 31
#define KMGO_RF_DIG_CCU_CCURSTCTRL_RFSYSTEM_SIZE 1

/** bit field defines for kmgo_rf_dig_ccu_s#clklost */
#define KMGO_RF_DIG_CCU_CLKLOST_RX1EN_OFFSET 0
#define KMGO_RF_DIG_CCU_CLKLOST_RX1EN_SIZE 1
#define KMGO_RF_DIG_CCU_CLKLOST_RX2EN_OFFSET 1
#define KMGO_RF_DIG_CCU_CLKLOST_RX2EN_SIZE 1
#define KMGO_RF_DIG_CCU_CLKLOST_TX1EN_OFFSET 2
#define KMGO_RF_DIG_CCU_CLKLOST_TX1EN_SIZE 1
#define KMGO_RF_DIG_CCU_CLKLOST_TX2EN_OFFSET 3
#define KMGO_RF_DIG_CCU_CLKLOST_TX2EN_SIZE 1

/** bit field defines for kmgo_rf_dig_ccu_s#intmask */
#define KMGO_RF_DIG_CCU_INTMASK_RX1EN_OFFSET 0
#define KMGO_RF_DIG_CCU_INTMASK_RX1EN_SIZE 1
#define KMGO_RF_DIG_CCU_INTMASK_RX2EN_OFFSET 1
#define KMGO_RF_DIG_CCU_INTMASK_RX2EN_SIZE 1
#define KMGO_RF_DIG_CCU_INTMASK_TX1EN_OFFSET 2
#define KMGO_RF_DIG_CCU_INTMASK_TX1EN_SIZE 1
#define KMGO_RF_DIG_CCU_INTMASK_TX2EN_OFFSET 3
#define KMGO_RF_DIG_CCU_INTMASK_TX2EN_SIZE 1

/** bit field defines for kmgo_rf_dig_ccu_s#intstatus */
#define KMGO_RF_DIG_CCU_INTSTATUS_RX1_OFFSET 0
#define KMGO_RF_DIG_CCU_INTSTATUS_RX1_SIZE 1
#define KMGO_RF_DIG_CCU_INTSTATUS_RX2_OFFSET 1
#define KMGO_RF_DIG_CCU_INTSTATUS_RX2_SIZE 1
#define KMGO_RF_DIG_CCU_INTSTATUS_TX1_OFFSET 2
#define KMGO_RF_DIG_CCU_INTSTATUS_TX1_SIZE 1
#define KMGO_RF_DIG_CCU_INTSTATUS_TX2_OFFSET 3
#define KMGO_RF_DIG_CCU_INTSTATUS_TX2_SIZE 1

/* EOF kmgo_rf_dig_ccu.h */
#endif
