#ifndef INCLUDED_OSPI
#define INCLUDED_OSPI
/*
 * Copyright (C) u-blox 
 * All rights reserved. 
 * This source file is the sole property of u-blox. Reproduction or utilization 
 * of this source in whole or part is forbidden without the written consent of 
 * u-blox.
 *
 */

#include <stdint.h>

/** ospi HAL Spreadsheet version number */
#define OSPI_HAL_VERSION 1

/**  ospi_flash_apb_regs
*/
struct ospi_s {
   /** Octal-SPI Configuration Register at address offset 0x000, read-write */
   uint32_t config_reg;
   /** Device Read Instruction Configuration Register at address offset 0x004, read-write */
   uint32_t dev_instr_rd_config_reg;
   /** Device Write Instruction Configuration Register at address offset 0x008, read-write */
   uint32_t dev_instr_wr_config_reg;
   /** Octal-SPI Device Delay Register: This register is used to introduce relative delays into the generation of the master output signals. All timings are defined in cycles of the SPI REFERENCE CLOCK/ext_clk  defined in this table as SPI master ref clock. at address offset 0x00C, read-write */
   uint32_t dev_delay_reg;
   /** Read Data Capture Register at address offset 0x010, read-write */
   uint32_t rd_data_capture_reg;
   /** Device Size Configuration Register at address offset 0x014, read-write */
   uint32_t dev_size_config_reg;
   /** SRAM Partition Configuration Register at address offset 0x018, read-write */
   uint32_t sram_partition_cfg_reg;
   /** Indirect AHB Address Trigger Register at address offset 0x01C, read-write */
   uint32_t ind_ahb_addr_trigger_reg;
   /** DMA Peripheral Configuration Register at address offset 0x020, read-write */
   uint32_t dma_periph_config_reg;
   /** Remap Address Register at address offset 0x024, read-write */
   uint32_t remap_addr_reg;
   /** Mode Bit Configuration Register at address offset 0x028, read-write */
   uint32_t mode_bit_config_reg;
   /** SRAM Fill Register at address offset 0x02C, read-only */
   uint32_t sram_fill_reg;
   /** TX Threshold Register at address offset 0x030, read-write */
   uint32_t tx_thresh_reg;
   /** RX Threshold Register at address offset 0x034, read-write */
   uint32_t rx_thresh_reg;
   /** Write Completion Control Register: This register defines how the controller will poll the device following a write transfer at address offset 0x038, read-write */
   uint32_t write_completion_ctrl_reg;
   /** Polling Expiration Register at address offset 0x03C, read-write */
   uint32_t no_of_polls_bef_exp_reg;
   /** Interrupt Status Register: The status fields in this register are set when the described event occurs and the interrupt is enabled in the mask register. When any of these bit fields are set  the interrupt output is asserted high. The fields are each cleared by writing a 1 to the field. Note that bit fields 6 thru 10 are only valid when legacy SPI mode is active. at address offset 0x040, read-write */
   uint32_t irq_status_reg;
   /**  at address offset 0x044, read-write */
   uint32_t irq_mask_reg;
   /** Reserved space */
   uint8_t fill0[8];
   /** Lower Write Protection Register at address offset 0x050, read-write */
   uint32_t lower_wr_prot_reg;
   /** Upper Write Protection Register at address offset 0x054, read-write */
   uint32_t upper_wr_prot_reg;
   /** Write Protection Control Register at address offset 0x058, read-write */
   uint32_t wr_prot_ctrl_reg;
   /** Reserved space */
   uint8_t fill1[4];
   /** Indirect Read Transfer Control Register at address offset 0x060, read-write */
   uint32_t indirect_read_xfer_ctrl_reg;
   /** Indirect Read Transfer Watermark Register at address offset 0x064, read-write */
   uint32_t indirect_read_xfer_watermark_reg;
   /** Indirect Read Transfer Start Address Register at address offset 0x068, read-write */
   uint32_t indirect_read_xfer_start_reg;
   /** Indirect Read Transfer Number Bytes Register at address offset 0x06C, read-write */
   uint32_t indirect_read_xfer_num_bytes_reg;
   /** Indirect Write Transfer Control Register at address offset 0x070, read-write */
   uint32_t indirect_write_xfer_ctrl_reg;
   /** Indirect Write Transfer Watermark Register at address offset 0x074, read-write */
   uint32_t indirect_write_xfer_watermark_reg;
   /** Indirect Write Transfer Start Address Register at address offset 0x078, read-write */
   uint32_t indirect_write_xfer_start_reg;
   /** Indirect Write Transfer Number Bytes Register at address offset 0x07C, read-write */
   uint32_t indirect_write_xfer_num_bytes_reg;
   /** Indirect Trigger Address Range Register at address offset 0x080, read-write */
   uint32_t indirect_trigger_addr_range_reg;
   /** Reserved space */
   uint8_t fill2[8];
   /** Flash Command Control Memory Register at address offset 0x08C, read-write */
   uint32_t flash_command_ctrl_mem_reg;
   /** Flash Command Control Register at address offset 0x090, read-write */
   uint32_t flash_cmd_ctrl_reg;
   /** Flash Command Address Register at address offset 0x094, read-write */
   uint32_t flash_cmd_addr_reg;
   /** Reserved space */
   uint8_t fill3[8];
   /** Flash Command Read Data Register (Lower) at address offset 0x0A0, read-only */
   uint32_t flash_rd_data_lower_reg;
   /** Flash Command Read Data Register (Upper) at address offset 0x0A4, read-only */
   uint32_t flash_rd_data_upper_reg;
   /** Flash Command Write Data Register (Lower) at address offset 0x0A8, read-write */
   uint32_t flash_wr_data_lower_reg;
   /** Flash Command Write Data Register (Upper) at address offset 0x0AC, read-write */
   uint32_t flash_wr_data_upper_reg;
   /** Polling Flash Status Register at address offset 0x0B0, read-write */
   uint32_t polling_flash_status_reg;
   /** PHY Configuration Register at address offset 0x0B4, read-write */
   uint32_t phy_configuration_reg;
   /** PHY DLL Master Control Register at address offset 0x0B8, read-write */
   uint32_t phy_master_control_reg;
   /** DLL Observable Register Lower at address offset 0x0BC, read-only */
   uint32_t dll_observable_lower_reg;
   /** DLL Observable Register Upper at address offset 0x0C0, read-only */
   uint32_t dll_observable_upper_reg;
   /** Reserved space */
   uint8_t fill4[28];
   /** Opcode Extension Register (Lower) at address offset 0x0E0, read-write */
   uint32_t opcode_ext_lower_reg;
   /** Opcode Extension Register (Upper) at address offset 0x0E4, read-write */
   uint32_t opcode_ext_upper_reg;
   /** Reserved space */
   uint8_t fill5[20];
   /** Module ID Register at address offset 0x0FC, read-only */
   uint32_t module_id_reg;
};

/** bit field defines for ospi_s#config_reg */
#define OSPI_CONFIG_REG_ENB_SPI_FLD_OFFSET 0
#define OSPI_CONFIG_REG_ENB_SPI_FLD_SIZE 1
#define OSPI_CONFIG_REG_SEL_CLK_POL_FLD_OFFSET 1
#define OSPI_CONFIG_REG_SEL_CLK_POL_FLD_SIZE 1
#define OSPI_CONFIG_REG_SEL_CLK_PHASE_FLD_OFFSET 2
#define OSPI_CONFIG_REG_SEL_CLK_PHASE_FLD_SIZE 1
#define OSPI_CONFIG_REG_PHY_MODE_ENABLE_FLD_OFFSET 3
#define OSPI_CONFIG_REG_PHY_MODE_ENABLE_FLD_SIZE 1
#define OSPI_CONFIG_REG_HOLD_PIN_FLD_OFFSET 4
#define OSPI_CONFIG_REG_HOLD_PIN_FLD_SIZE 1
#define OSPI_CONFIG_REG_RESET_PIN_FLD_OFFSET 5
#define OSPI_CONFIG_REG_RESET_PIN_FLD_SIZE 1
#define OSPI_CONFIG_REG_RESET_CFG_FLD_OFFSET 6
#define OSPI_CONFIG_REG_RESET_CFG_FLD_SIZE 1
#define OSPI_CONFIG_REG_ENB_DIR_ACC_CTLR_FLD_OFFSET 7
#define OSPI_CONFIG_REG_ENB_DIR_ACC_CTLR_FLD_SIZE 1
#define OSPI_CONFIG_REG_ENB_LEGACY_IP_MODE_FLD_OFFSET 8
#define OSPI_CONFIG_REG_ENB_LEGACY_IP_MODE_FLD_SIZE 1
#define OSPI_CONFIG_REG_PERIPH_SEL_DEC_FLD_OFFSET 9
#define OSPI_CONFIG_REG_PERIPH_SEL_DEC_FLD_SIZE 1
#define OSPI_CONFIG_REG_PERIPH_CS_LINES_FLD_OFFSET 10
#define OSPI_CONFIG_REG_PERIPH_CS_LINES_FLD_SIZE 4
#define OSPI_CONFIG_REG_WR_PROT_FLASH_FLD_OFFSET 14
#define OSPI_CONFIG_REG_WR_PROT_FLASH_FLD_SIZE 1
#define OSPI_CONFIG_REG_ENB_DMA_IF_FLD_OFFSET 15
#define OSPI_CONFIG_REG_ENB_DMA_IF_FLD_SIZE 1
#define OSPI_CONFIG_REG_ENB_AHB_ADDR_REMAP_FLD_OFFSET 16
#define OSPI_CONFIG_REG_ENB_AHB_ADDR_REMAP_FLD_SIZE 1
#define OSPI_CONFIG_REG_ENTER_XIP_MODE_FLD_OFFSET 17
#define OSPI_CONFIG_REG_ENTER_XIP_MODE_FLD_SIZE 1
#define OSPI_CONFIG_REG_ENTER_XIP_MODE_IMM_FLD_OFFSET 18
#define OSPI_CONFIG_REG_ENTER_XIP_MODE_IMM_FLD_SIZE 1
#define OSPI_CONFIG_REG_MSTR_BAUD_DIV_FLD_OFFSET 19
#define OSPI_CONFIG_REG_MSTR_BAUD_DIV_FLD_SIZE 4
#define OSPI_CONFIG_REG_ENABLE_AHB_DECODER_FLD_OFFSET 23
#define OSPI_CONFIG_REG_ENABLE_AHB_DECODER_FLD_SIZE 1
#define OSPI_CONFIG_REG_ENABLE_DTR_PROTOCOL_FLD_OFFSET 24
#define OSPI_CONFIG_REG_ENABLE_DTR_PROTOCOL_FLD_SIZE 1
#define OSPI_CONFIG_REG_PIPELINE_PHY_FLD_OFFSET 25
#define OSPI_CONFIG_REG_PIPELINE_PHY_FLD_SIZE 1
#define OSPI_CONFIG_REG_CONFIG_RESV2_FLD_OFFSET 26
#define OSPI_CONFIG_REG_CONFIG_RESV2_FLD_SIZE 3
#define OSPI_CONFIG_REG_CRC_ENABLE_FLD_OFFSET 29
#define OSPI_CONFIG_REG_CRC_ENABLE_FLD_SIZE 1
#define OSPI_CONFIG_REG_DUAL_BYTE_OPCODE_EN_FLD_OFFSET 30
#define OSPI_CONFIG_REG_DUAL_BYTE_OPCODE_EN_FLD_SIZE 1
#define OSPI_CONFIG_REG_IDLE_FLD_OFFSET 31
#define OSPI_CONFIG_REG_IDLE_FLD_SIZE 1

/** bit field defines for ospi_s#dev_instr_rd_config_reg */
#define OSPI_DEV_INSTR_RD_CONFIG_REG_RD_OPCODE_NON_XIP_FLD_OFFSET 0
#define OSPI_DEV_INSTR_RD_CONFIG_REG_RD_OPCODE_NON_XIP_FLD_SIZE 8
#define OSPI_DEV_INSTR_RD_CONFIG_REG_INSTR_TYPE_FLD_OFFSET 8
#define OSPI_DEV_INSTR_RD_CONFIG_REG_INSTR_TYPE_FLD_SIZE 2
#define OSPI_DEV_INSTR_RD_CONFIG_REG_DDR_EN_FLD_OFFSET 10
#define OSPI_DEV_INSTR_RD_CONFIG_REG_DDR_EN_FLD_SIZE 1
#define OSPI_DEV_INSTR_RD_CONFIG_REG_PRED_DIS_FLD_OFFSET 11
#define OSPI_DEV_INSTR_RD_CONFIG_REG_PRED_DIS_FLD_SIZE 1
#define OSPI_DEV_INSTR_RD_CONFIG_REG_ADDR_XFER_TYPE_STD_MODE_FLD_OFFSET 12
#define OSPI_DEV_INSTR_RD_CONFIG_REG_ADDR_XFER_TYPE_STD_MODE_FLD_SIZE 2
#define OSPI_DEV_INSTR_RD_CONFIG_REG_RD_INSTR_RESV2_FLD_OFFSET 14
#define OSPI_DEV_INSTR_RD_CONFIG_REG_RD_INSTR_RESV2_FLD_SIZE 2
#define OSPI_DEV_INSTR_RD_CONFIG_REG_DATA_XFER_TYPE_EXT_MODE_FLD_OFFSET 16
#define OSPI_DEV_INSTR_RD_CONFIG_REG_DATA_XFER_TYPE_EXT_MODE_FLD_SIZE 2
#define OSPI_DEV_INSTR_RD_CONFIG_REG_RD_INSTR_RESV3_FLD_OFFSET 18
#define OSPI_DEV_INSTR_RD_CONFIG_REG_RD_INSTR_RESV3_FLD_SIZE 2
#define OSPI_DEV_INSTR_RD_CONFIG_REG_MODE_BIT_ENABLE_FLD_OFFSET 20
#define OSPI_DEV_INSTR_RD_CONFIG_REG_MODE_BIT_ENABLE_FLD_SIZE 1
#define OSPI_DEV_INSTR_RD_CONFIG_REG_RD_INSTR_RESV4_FLD_OFFSET 21
#define OSPI_DEV_INSTR_RD_CONFIG_REG_RD_INSTR_RESV4_FLD_SIZE 3
#define OSPI_DEV_INSTR_RD_CONFIG_REG_DUMMY_RD_CLK_CYCLES_FLD_OFFSET 24
#define OSPI_DEV_INSTR_RD_CONFIG_REG_DUMMY_RD_CLK_CYCLES_FLD_SIZE 5
#define OSPI_DEV_INSTR_RD_CONFIG_REG_RD_INSTR_RESV5_FLD_OFFSET 29
#define OSPI_DEV_INSTR_RD_CONFIG_REG_RD_INSTR_RESV5_FLD_SIZE 3

/** bit field defines for ospi_s#dev_instr_wr_config_reg */
#define OSPI_DEV_INSTR_WR_CONFIG_REG_WR_OPCODE_FLD_OFFSET 0
#define OSPI_DEV_INSTR_WR_CONFIG_REG_WR_OPCODE_FLD_SIZE 8
#define OSPI_DEV_INSTR_WR_CONFIG_REG_WEL_DIS_FLD_OFFSET 8
#define OSPI_DEV_INSTR_WR_CONFIG_REG_WEL_DIS_FLD_SIZE 1
#define OSPI_DEV_INSTR_WR_CONFIG_REG_WR_INSTR_RESV1_FLD_OFFSET 9
#define OSPI_DEV_INSTR_WR_CONFIG_REG_WR_INSTR_RESV1_FLD_SIZE 3
#define OSPI_DEV_INSTR_WR_CONFIG_REG_ADDR_XFER_TYPE_STD_MODE_FLD_OFFSET 12
#define OSPI_DEV_INSTR_WR_CONFIG_REG_ADDR_XFER_TYPE_STD_MODE_FLD_SIZE 2
#define OSPI_DEV_INSTR_WR_CONFIG_REG_WR_INSTR_RESV2_FLD_OFFSET 14
#define OSPI_DEV_INSTR_WR_CONFIG_REG_WR_INSTR_RESV2_FLD_SIZE 2
#define OSPI_DEV_INSTR_WR_CONFIG_REG_DATA_XFER_TYPE_EXT_MODE_FLD_OFFSET 16
#define OSPI_DEV_INSTR_WR_CONFIG_REG_DATA_XFER_TYPE_EXT_MODE_FLD_SIZE 2
#define OSPI_DEV_INSTR_WR_CONFIG_REG_WR_INSTR_RESV3_FLD_OFFSET 18
#define OSPI_DEV_INSTR_WR_CONFIG_REG_WR_INSTR_RESV3_FLD_SIZE 6
#define OSPI_DEV_INSTR_WR_CONFIG_REG_DUMMY_WR_CLK_CYCLES_FLD_OFFSET 24
#define OSPI_DEV_INSTR_WR_CONFIG_REG_DUMMY_WR_CLK_CYCLES_FLD_SIZE 5
#define OSPI_DEV_INSTR_WR_CONFIG_REG_WR_INSTR_RESV4_FLD_OFFSET 29
#define OSPI_DEV_INSTR_WR_CONFIG_REG_WR_INSTR_RESV4_FLD_SIZE 3

/** bit field defines for ospi_s#dev_delay_reg */
#define OSPI_DEV_DELAY_REG_D_INIT_FLD_OFFSET 0
#define OSPI_DEV_DELAY_REG_D_INIT_FLD_SIZE 8
#define OSPI_DEV_DELAY_REG_D_AFTER_FLD_OFFSET 8
#define OSPI_DEV_DELAY_REG_D_AFTER_FLD_SIZE 8
#define OSPI_DEV_DELAY_REG_D_BTWN_FLD_OFFSET 16
#define OSPI_DEV_DELAY_REG_D_BTWN_FLD_SIZE 8
#define OSPI_DEV_DELAY_REG_D_NSS_FLD_OFFSET 24
#define OSPI_DEV_DELAY_REG_D_NSS_FLD_SIZE 8

/** bit field defines for ospi_s#rd_data_capture_reg */
#define OSPI_RD_DATA_CAPTURE_REG_BYPASS_FLD_OFFSET 0
#define OSPI_RD_DATA_CAPTURE_REG_BYPASS_FLD_SIZE 1
#define OSPI_RD_DATA_CAPTURE_REG_DELAY_FLD_OFFSET 1
#define OSPI_RD_DATA_CAPTURE_REG_DELAY_FLD_SIZE 4
#define OSPI_RD_DATA_CAPTURE_REG_SAMPLE_EDGE_SEL_FLD_OFFSET 5
#define OSPI_RD_DATA_CAPTURE_REG_SAMPLE_EDGE_SEL_FLD_SIZE 1
#define OSPI_RD_DATA_CAPTURE_REG_RD_DATA_RESV1_FLD_OFFSET 6
#define OSPI_RD_DATA_CAPTURE_REG_RD_DATA_RESV1_FLD_SIZE 2
#define OSPI_RD_DATA_CAPTURE_REG_DQS_ENABLE_FLD_OFFSET 8
#define OSPI_RD_DATA_CAPTURE_REG_DQS_ENABLE_FLD_SIZE 1
#define OSPI_RD_DATA_CAPTURE_REG_RD_DATA_RESV2_FLD_OFFSET 9
#define OSPI_RD_DATA_CAPTURE_REG_RD_DATA_RESV2_FLD_SIZE 7
#define OSPI_RD_DATA_CAPTURE_REG_DDR_READ_DELAY_FLD_OFFSET 16
#define OSPI_RD_DATA_CAPTURE_REG_DDR_READ_DELAY_FLD_SIZE 4
#define OSPI_RD_DATA_CAPTURE_REG_RD_DATA_RESV3_FLD_OFFSET 20
#define OSPI_RD_DATA_CAPTURE_REG_RD_DATA_RESV3_FLD_SIZE 12

/** bit field defines for ospi_s#dev_size_config_reg */
#define OSPI_DEV_SIZE_CONFIG_REG_NUM_ADDR_BYTES_FLD_OFFSET 0
#define OSPI_DEV_SIZE_CONFIG_REG_NUM_ADDR_BYTES_FLD_SIZE 4
#define OSPI_DEV_SIZE_CONFIG_REG_BYTES_PER_DEVICE_PAGE_FLD_OFFSET 4
#define OSPI_DEV_SIZE_CONFIG_REG_BYTES_PER_DEVICE_PAGE_FLD_SIZE 12
#define OSPI_DEV_SIZE_CONFIG_REG_BYTES_PER_SUBSECTOR_FLD_OFFSET 16
#define OSPI_DEV_SIZE_CONFIG_REG_BYTES_PER_SUBSECTOR_FLD_SIZE 5
#define OSPI_DEV_SIZE_CONFIG_REG_MEM_SIZE_ON_CS0_FLD_OFFSET 21
#define OSPI_DEV_SIZE_CONFIG_REG_MEM_SIZE_ON_CS0_FLD_SIZE 2
#define OSPI_DEV_SIZE_CONFIG_REG_MEM_SIZE_ON_CS1_FLD_OFFSET 23
#define OSPI_DEV_SIZE_CONFIG_REG_MEM_SIZE_ON_CS1_FLD_SIZE 2
#define OSPI_DEV_SIZE_CONFIG_REG_MEM_SIZE_ON_CS2_FLD_OFFSET 25
#define OSPI_DEV_SIZE_CONFIG_REG_MEM_SIZE_ON_CS2_FLD_SIZE 2
#define OSPI_DEV_SIZE_CONFIG_REG_MEM_SIZE_ON_CS3_FLD_OFFSET 27
#define OSPI_DEV_SIZE_CONFIG_REG_MEM_SIZE_ON_CS3_FLD_SIZE 2
#define OSPI_DEV_SIZE_CONFIG_REG_DEV_SIZE_RESV_FLD_OFFSET 29
#define OSPI_DEV_SIZE_CONFIG_REG_DEV_SIZE_RESV_FLD_SIZE 3

/** bit field defines for ospi_s#sram_partition_cfg_reg */
#define OSPI_SRAM_PARTITION_CFG_REG_ADDR_FLD_OFFSET 0
#define OSPI_SRAM_PARTITION_CFG_REG_ADDR_FLD_SIZE 8
#define OSPI_SRAM_PARTITION_CFG_REG_SRAM_PARTITION_RESV_FLD_OFFSET 8
#define OSPI_SRAM_PARTITION_CFG_REG_SRAM_PARTITION_RESV_FLD_SIZE 24

/** bit field defines for ospi_s#ind_ahb_addr_trigger_reg */
#define OSPI_IND_AHB_ADDR_TRIGGER_REG_ADDR_FLD_OFFSET 0
#define OSPI_IND_AHB_ADDR_TRIGGER_REG_ADDR_FLD_SIZE 32

/** bit field defines for ospi_s#dma_periph_config_reg */
#define OSPI_DMA_PERIPH_CONFIG_REG_NUM_SINGLE_REQ_BYTES_FLD_OFFSET 0
#define OSPI_DMA_PERIPH_CONFIG_REG_NUM_SINGLE_REQ_BYTES_FLD_SIZE 4
#define OSPI_DMA_PERIPH_CONFIG_REG_DMA_PERIPH_RESV1_FLD_OFFSET 4
#define OSPI_DMA_PERIPH_CONFIG_REG_DMA_PERIPH_RESV1_FLD_SIZE 4
#define OSPI_DMA_PERIPH_CONFIG_REG_NUM_BURST_REQ_BYTES_FLD_OFFSET 8
#define OSPI_DMA_PERIPH_CONFIG_REG_NUM_BURST_REQ_BYTES_FLD_SIZE 4
#define OSPI_DMA_PERIPH_CONFIG_REG_DMA_PERIPH_RESV2_FLD_OFFSET 12
#define OSPI_DMA_PERIPH_CONFIG_REG_DMA_PERIPH_RESV2_FLD_SIZE 20

/** bit field defines for ospi_s#remap_addr_reg */
#define OSPI_REMAP_ADDR_REG_VALUE_FLD_OFFSET 0
#define OSPI_REMAP_ADDR_REG_VALUE_FLD_SIZE 32

/** bit field defines for ospi_s#mode_bit_config_reg */
#define OSPI_MODE_BIT_CONFIG_REG_MODE_FLD_OFFSET 0
#define OSPI_MODE_BIT_CONFIG_REG_MODE_FLD_SIZE 8
#define OSPI_MODE_BIT_CONFIG_REG_CHUNK_SIZE_FLD_OFFSET 8
#define OSPI_MODE_BIT_CONFIG_REG_CHUNK_SIZE_FLD_SIZE 3
#define OSPI_MODE_BIT_CONFIG_REG_MODE_BIT_RESV1_FLD_OFFSET 11
#define OSPI_MODE_BIT_CONFIG_REG_MODE_BIT_RESV1_FLD_SIZE 4
#define OSPI_MODE_BIT_CONFIG_REG_CRC_OUT_ENABLE_FLD_OFFSET 15
#define OSPI_MODE_BIT_CONFIG_REG_CRC_OUT_ENABLE_FLD_SIZE 1
#define OSPI_MODE_BIT_CONFIG_REG_RX_CRC_DATA_UP_FLD_OFFSET 16
#define OSPI_MODE_BIT_CONFIG_REG_RX_CRC_DATA_UP_FLD_SIZE 8
#define OSPI_MODE_BIT_CONFIG_REG_RX_CRC_DATA_LOW_FLD_OFFSET 24
#define OSPI_MODE_BIT_CONFIG_REG_RX_CRC_DATA_LOW_FLD_SIZE 8

/** bit field defines for ospi_s#sram_fill_reg */
#define OSPI_SRAM_FILL_REG_SRAM_FILL_INDAC_READ_FLD_OFFSET 0
#define OSPI_SRAM_FILL_REG_SRAM_FILL_INDAC_READ_FLD_SIZE 16
#define OSPI_SRAM_FILL_REG_SRAM_FILL_INDAC_WRITE_FLD_OFFSET 16
#define OSPI_SRAM_FILL_REG_SRAM_FILL_INDAC_WRITE_FLD_SIZE 16

/** bit field defines for ospi_s#tx_thresh_reg */
#define OSPI_TX_THRESH_REG_LEVEL_FLD_OFFSET 0
#define OSPI_TX_THRESH_REG_LEVEL_FLD_SIZE 5
#define OSPI_TX_THRESH_REG_TX_THRESH_RESV_FLD_OFFSET 5
#define OSPI_TX_THRESH_REG_TX_THRESH_RESV_FLD_SIZE 27

/** bit field defines for ospi_s#rx_thresh_reg */
#define OSPI_RX_THRESH_REG_LEVEL_FLD_OFFSET 0
#define OSPI_RX_THRESH_REG_LEVEL_FLD_SIZE 5
#define OSPI_RX_THRESH_REG_RX_THRESH_RESV_FLD_OFFSET 5
#define OSPI_RX_THRESH_REG_RX_THRESH_RESV_FLD_SIZE 27

/** bit field defines for ospi_s#write_completion_ctrl_reg */
#define OSPI_WRITE_COMPLETION_CTRL_REG_OPCODE_FLD_OFFSET 0
#define OSPI_WRITE_COMPLETION_CTRL_REG_OPCODE_FLD_SIZE 8
#define OSPI_WRITE_COMPLETION_CTRL_REG_POLLING_BIT_INDEX_FLD_OFFSET 8
#define OSPI_WRITE_COMPLETION_CTRL_REG_POLLING_BIT_INDEX_FLD_SIZE 3
#define OSPI_WRITE_COMPLETION_CTRL_REG_POLLING_ADDR_EN_FLD_OFFSET 11
#define OSPI_WRITE_COMPLETION_CTRL_REG_POLLING_ADDR_EN_FLD_SIZE 1
#define OSPI_WRITE_COMPLETION_CTRL_REG_WR_COMP_CTRL_RESV1_FLD_OFFSET 12
#define OSPI_WRITE_COMPLETION_CTRL_REG_WR_COMP_CTRL_RESV1_FLD_SIZE 1
#define OSPI_WRITE_COMPLETION_CTRL_REG_POLLING_POLARITY_FLD_OFFSET 13
#define OSPI_WRITE_COMPLETION_CTRL_REG_POLLING_POLARITY_FLD_SIZE 1
#define OSPI_WRITE_COMPLETION_CTRL_REG_DISABLE_POLLING_FLD_OFFSET 14
#define OSPI_WRITE_COMPLETION_CTRL_REG_DISABLE_POLLING_FLD_SIZE 1
#define OSPI_WRITE_COMPLETION_CTRL_REG_ENABLE_POLLING_EXP_FLD_OFFSET 15
#define OSPI_WRITE_COMPLETION_CTRL_REG_ENABLE_POLLING_EXP_FLD_SIZE 1
#define OSPI_WRITE_COMPLETION_CTRL_REG_POLL_COUNT_FLD_OFFSET 16
#define OSPI_WRITE_COMPLETION_CTRL_REG_POLL_COUNT_FLD_SIZE 8
#define OSPI_WRITE_COMPLETION_CTRL_REG_POLL_REP_DELAY_FLD_OFFSET 24
#define OSPI_WRITE_COMPLETION_CTRL_REG_POLL_REP_DELAY_FLD_SIZE 8

/** bit field defines for ospi_s#no_of_polls_bef_exp_reg */
#define OSPI_NO_OF_POLLS_BEF_EXP_REG_NO_OF_POLLS_BEF_EXP_FLD_OFFSET 0
#define OSPI_NO_OF_POLLS_BEF_EXP_REG_NO_OF_POLLS_BEF_EXP_FLD_SIZE 32

/** bit field defines for ospi_s#irq_status_reg */
#define OSPI_IRQ_STATUS_REG_MODE_M_FAIL_FLD_OFFSET 0
#define OSPI_IRQ_STATUS_REG_MODE_M_FAIL_FLD_SIZE 1
#define OSPI_IRQ_STATUS_REG_UNDERFLOW_DET_FLD_OFFSET 1
#define OSPI_IRQ_STATUS_REG_UNDERFLOW_DET_FLD_SIZE 1
#define OSPI_IRQ_STATUS_REG_INDIRECT_OP_DONE_FLD_OFFSET 2
#define OSPI_IRQ_STATUS_REG_INDIRECT_OP_DONE_FLD_SIZE 1
#define OSPI_IRQ_STATUS_REG_INDIRECT_TRANSFER_REJECT_FLD_OFFSET 3
#define OSPI_IRQ_STATUS_REG_INDIRECT_TRANSFER_REJECT_FLD_SIZE 1
#define OSPI_IRQ_STATUS_REG_PROT_WR_ATTEMPT_FLD_OFFSET 4
#define OSPI_IRQ_STATUS_REG_PROT_WR_ATTEMPT_FLD_SIZE 1
#define OSPI_IRQ_STATUS_REG_ILLEGAL_ACCESS_DET_FLD_OFFSET 5
#define OSPI_IRQ_STATUS_REG_ILLEGAL_ACCESS_DET_FLD_SIZE 1
#define OSPI_IRQ_STATUS_REG_INDIRECT_XFER_LEVEL_BREACH_FLD_OFFSET 6
#define OSPI_IRQ_STATUS_REG_INDIRECT_XFER_LEVEL_BREACH_FLD_SIZE 1
#define OSPI_IRQ_STATUS_REG_RECV_OVERFLOW_FLD_OFFSET 7
#define OSPI_IRQ_STATUS_REG_RECV_OVERFLOW_FLD_SIZE 1
#define OSPI_IRQ_STATUS_REG_TX_FIFO_NOT_FULL_FLD_OFFSET 8
#define OSPI_IRQ_STATUS_REG_TX_FIFO_NOT_FULL_FLD_SIZE 1
#define OSPI_IRQ_STATUS_REG_TX_FIFO_FULL_FLD_OFFSET 9
#define OSPI_IRQ_STATUS_REG_TX_FIFO_FULL_FLD_SIZE 1
#define OSPI_IRQ_STATUS_REG_RX_FIFO_NOT_EMPTY_FLD_OFFSET 10
#define OSPI_IRQ_STATUS_REG_RX_FIFO_NOT_EMPTY_FLD_SIZE 1
#define OSPI_IRQ_STATUS_REG_RX_FIFO_FULL_FLD_OFFSET 11
#define OSPI_IRQ_STATUS_REG_RX_FIFO_FULL_FLD_SIZE 1
#define OSPI_IRQ_STATUS_REG_INDRD_SRAM_FULL_FLD_OFFSET 12
#define OSPI_IRQ_STATUS_REG_INDRD_SRAM_FULL_FLD_SIZE 1
#define OSPI_IRQ_STATUS_REG_POLL_EXP_INT_FLD_OFFSET 13
#define OSPI_IRQ_STATUS_REG_POLL_EXP_INT_FLD_SIZE 1
#define OSPI_IRQ_STATUS_REG_STIG_REQ_INT_FLD_OFFSET 14
#define OSPI_IRQ_STATUS_REG_STIG_REQ_INT_FLD_SIZE 1
#define OSPI_IRQ_STATUS_REG_IRQ_STAT_RESV1_FLD_OFFSET 15
#define OSPI_IRQ_STATUS_REG_IRQ_STAT_RESV1_FLD_SIZE 1
#define OSPI_IRQ_STATUS_REG_RX_CRC_DATA_ERR_FLD_OFFSET 16
#define OSPI_IRQ_STATUS_REG_RX_CRC_DATA_ERR_FLD_SIZE 1
#define OSPI_IRQ_STATUS_REG_RX_CRC_DATA_VAL_FLD_OFFSET 17
#define OSPI_IRQ_STATUS_REG_RX_CRC_DATA_VAL_FLD_SIZE 1
#define OSPI_IRQ_STATUS_REG_TX_CRC_CHUNK_BRK_FLD_OFFSET 18
#define OSPI_IRQ_STATUS_REG_TX_CRC_CHUNK_BRK_FLD_SIZE 1
#define OSPI_IRQ_STATUS_REG_ECC_FAIL_FLD_OFFSET 19
#define OSPI_IRQ_STATUS_REG_ECC_FAIL_FLD_SIZE 1
#define OSPI_IRQ_STATUS_REG_IRQ_STAT_RESV_FLD_OFFSET 20
#define OSPI_IRQ_STATUS_REG_IRQ_STAT_RESV_FLD_SIZE 12

/** bit field defines for ospi_s#irq_mask_reg */
#define OSPI_IRQ_MASK_REG_MODE_M_FAIL_MASK_FLD_OFFSET 0
#define OSPI_IRQ_MASK_REG_MODE_M_FAIL_MASK_FLD_SIZE 1
#define OSPI_IRQ_MASK_REG_UNDERFLOW_DET_MASK_FLD_OFFSET 1
#define OSPI_IRQ_MASK_REG_UNDERFLOW_DET_MASK_FLD_SIZE 1
#define OSPI_IRQ_MASK_REG_INDIRECT_OP_DONE_MASK_FLD_OFFSET 2
#define OSPI_IRQ_MASK_REG_INDIRECT_OP_DONE_MASK_FLD_SIZE 1
#define OSPI_IRQ_MASK_REG_INDIRECT_TRANSFER_REJECT_MASK_FLD_OFFSET 3
#define OSPI_IRQ_MASK_REG_INDIRECT_TRANSFER_REJECT_MASK_FLD_SIZE 1
#define OSPI_IRQ_MASK_REG_PROT_WR_ATTEMPT_MASK_FLD_OFFSET 4
#define OSPI_IRQ_MASK_REG_PROT_WR_ATTEMPT_MASK_FLD_SIZE 1
#define OSPI_IRQ_MASK_REG_ILLEGAL_ACCESS_DET_MASK_FLD_OFFSET 5
#define OSPI_IRQ_MASK_REG_ILLEGAL_ACCESS_DET_MASK_FLD_SIZE 1
#define OSPI_IRQ_MASK_REG_INDIRECT_XFER_LEVEL_BREACH_MASK_FLD_OFFSET 6
#define OSPI_IRQ_MASK_REG_INDIRECT_XFER_LEVEL_BREACH_MASK_FLD_SIZE 1
#define OSPI_IRQ_MASK_REG_RECV_OVERFLOW_MASK_FLD_OFFSET 7
#define OSPI_IRQ_MASK_REG_RECV_OVERFLOW_MASK_FLD_SIZE 1
#define OSPI_IRQ_MASK_REG_TX_FIFO_NOT_FULL_MASK_FLD_OFFSET 8
#define OSPI_IRQ_MASK_REG_TX_FIFO_NOT_FULL_MASK_FLD_SIZE 1
#define OSPI_IRQ_MASK_REG_TX_FIFO_FULL_MASK_FLD_OFFSET 9
#define OSPI_IRQ_MASK_REG_TX_FIFO_FULL_MASK_FLD_SIZE 1
#define OSPI_IRQ_MASK_REG_RX_FIFO_NOT_EMPTY_MASK_FLD_OFFSET 10
#define OSPI_IRQ_MASK_REG_RX_FIFO_NOT_EMPTY_MASK_FLD_SIZE 1
#define OSPI_IRQ_MASK_REG_RX_FIFO_FULL_MASK_FLD_OFFSET 11
#define OSPI_IRQ_MASK_REG_RX_FIFO_FULL_MASK_FLD_SIZE 1
#define OSPI_IRQ_MASK_REG_INDRD_SRAM_FULL_MASK_FLD_OFFSET 12
#define OSPI_IRQ_MASK_REG_INDRD_SRAM_FULL_MASK_FLD_SIZE 1
#define OSPI_IRQ_MASK_REG_POLL_EXP_INT_MASK_FLD_OFFSET 13
#define OSPI_IRQ_MASK_REG_POLL_EXP_INT_MASK_FLD_SIZE 1
#define OSPI_IRQ_MASK_REG_STIG_REQ_MASK_FLD_OFFSET 14
#define OSPI_IRQ_MASK_REG_STIG_REQ_MASK_FLD_SIZE 1
#define OSPI_IRQ_MASK_REG_IRQ_MASK_RESV1_FLD_OFFSET 15
#define OSPI_IRQ_MASK_REG_IRQ_MASK_RESV1_FLD_SIZE 1
#define OSPI_IRQ_MASK_REG_RX_CRC_DATA_ERR_MASK_FLD_OFFSET 16
#define OSPI_IRQ_MASK_REG_RX_CRC_DATA_ERR_MASK_FLD_SIZE 1
#define OSPI_IRQ_MASK_REG_RX_CRC_DATA_VAL_MASK_FLD_OFFSET 17
#define OSPI_IRQ_MASK_REG_RX_CRC_DATA_VAL_MASK_FLD_SIZE 1
#define OSPI_IRQ_MASK_REG_TX_CRC_CHUNK_BRK_MASK_FLD_OFFSET 18
#define OSPI_IRQ_MASK_REG_TX_CRC_CHUNK_BRK_MASK_FLD_SIZE 1
#define OSPI_IRQ_MASK_REG_ECC_FAIL_MASK_FLD_OFFSET 19
#define OSPI_IRQ_MASK_REG_ECC_FAIL_MASK_FLD_SIZE 1
#define OSPI_IRQ_MASK_REG_IRQ_MASK_RESV_FLD_OFFSET 20
#define OSPI_IRQ_MASK_REG_IRQ_MASK_RESV_FLD_SIZE 12

/** bit field defines for ospi_s#lower_wr_prot_reg */
#define OSPI_LOWER_WR_PROT_REG_SUBSECTOR_FLD_OFFSET 0
#define OSPI_LOWER_WR_PROT_REG_SUBSECTOR_FLD_SIZE 32

/** bit field defines for ospi_s#upper_wr_prot_reg */
#define OSPI_UPPER_WR_PROT_REG_SUBSECTOR_FLD_OFFSET 0
#define OSPI_UPPER_WR_PROT_REG_SUBSECTOR_FLD_SIZE 32

/** bit field defines for ospi_s#wr_prot_ctrl_reg */
#define OSPI_WR_PROT_CTRL_REG_INV_FLD_OFFSET 0
#define OSPI_WR_PROT_CTRL_REG_INV_FLD_SIZE 1
#define OSPI_WR_PROT_CTRL_REG_ENB_FLD_OFFSET 1
#define OSPI_WR_PROT_CTRL_REG_ENB_FLD_SIZE 1
#define OSPI_WR_PROT_CTRL_REG_WR_PROT_CTRL_RESV_FLD_OFFSET 2
#define OSPI_WR_PROT_CTRL_REG_WR_PROT_CTRL_RESV_FLD_SIZE 30

/** bit field defines for ospi_s#indirect_read_xfer_ctrl_reg */
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_START_FLD_OFFSET 0
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_START_FLD_SIZE 1
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_CANCEL_FLD_OFFSET 1
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_CANCEL_FLD_SIZE 1
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_RD_STATUS_FLD_OFFSET 2
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_RD_STATUS_FLD_SIZE 1
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_SRAM_FULL_FLD_OFFSET 3
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_SRAM_FULL_FLD_SIZE 1
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_RD_QUEUED_FLD_OFFSET 4
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_RD_QUEUED_FLD_SIZE 1
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_IND_OPS_DONE_STATUS_FLD_OFFSET 5
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_IND_OPS_DONE_STATUS_FLD_SIZE 1
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_NUM_IND_OPS_DONE_FLD_OFFSET 6
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_NUM_IND_OPS_DONE_FLD_SIZE 2
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_INDIR_RD_XFER_RESV_FLD_OFFSET 8
#define OSPI_INDIRECT_READ_XFER_CTRL_REG_INDIR_RD_XFER_RESV_FLD_SIZE 24

/** bit field defines for ospi_s#indirect_read_xfer_watermark_reg */
#define OSPI_INDIRECT_READ_XFER_WATERMARK_REG_LEVEL_FLD_OFFSET 0
#define OSPI_INDIRECT_READ_XFER_WATERMARK_REG_LEVEL_FLD_SIZE 32

/** bit field defines for ospi_s#indirect_read_xfer_start_reg */
#define OSPI_INDIRECT_READ_XFER_START_REG_ADDR_FLD_OFFSET 0
#define OSPI_INDIRECT_READ_XFER_START_REG_ADDR_FLD_SIZE 32

/** bit field defines for ospi_s#indirect_read_xfer_num_bytes_reg */
#define OSPI_INDIRECT_READ_XFER_NUM_BYTES_REG_VALUE_FLD_OFFSET 0
#define OSPI_INDIRECT_READ_XFER_NUM_BYTES_REG_VALUE_FLD_SIZE 32

/** bit field defines for ospi_s#indirect_write_xfer_ctrl_reg */
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_START_FLD_OFFSET 0
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_START_FLD_SIZE 1
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_CANCEL_FLD_OFFSET 1
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_CANCEL_FLD_SIZE 1
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_WR_STATUS_FLD_OFFSET 2
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_WR_STATUS_FLD_SIZE 1
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_INDIR_WR_XFER_RESV1_FLD_OFFSET 3
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_INDIR_WR_XFER_RESV1_FLD_SIZE 1
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_WR_QUEUED_FLD_OFFSET 4
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_WR_QUEUED_FLD_SIZE 1
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_IND_OPS_DONE_STATUS_FLD_OFFSET 5
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_IND_OPS_DONE_STATUS_FLD_SIZE 1
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_NUM_IND_OPS_DONE_FLD_OFFSET 6
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_NUM_IND_OPS_DONE_FLD_SIZE 2
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_INDIR_WR_XFER_RESV2_FLD_OFFSET 8
#define OSPI_INDIRECT_WRITE_XFER_CTRL_REG_INDIR_WR_XFER_RESV2_FLD_SIZE 24

/** bit field defines for ospi_s#indirect_write_xfer_watermark_reg */
#define OSPI_INDIRECT_WRITE_XFER_WATERMARK_REG_LEVEL_FLD_OFFSET 0
#define OSPI_INDIRECT_WRITE_XFER_WATERMARK_REG_LEVEL_FLD_SIZE 32

/** bit field defines for ospi_s#indirect_write_xfer_start_reg */
#define OSPI_INDIRECT_WRITE_XFER_START_REG_ADDR_FLD_OFFSET 0
#define OSPI_INDIRECT_WRITE_XFER_START_REG_ADDR_FLD_SIZE 32

/** bit field defines for ospi_s#indirect_write_xfer_num_bytes_reg */
#define OSPI_INDIRECT_WRITE_XFER_NUM_BYTES_REG_VALUE_FLD_OFFSET 0
#define OSPI_INDIRECT_WRITE_XFER_NUM_BYTES_REG_VALUE_FLD_SIZE 32

/** bit field defines for ospi_s#indirect_trigger_addr_range_reg */
#define OSPI_INDIRECT_TRIGGER_ADDR_RANGE_REG_IND_RANGE_WIDTH_FLD_OFFSET 0
#define OSPI_INDIRECT_TRIGGER_ADDR_RANGE_REG_IND_RANGE_WIDTH_FLD_SIZE 4
#define OSPI_INDIRECT_TRIGGER_ADDR_RANGE_REG_IND_RANGE_RESV1_FLD_OFFSET 4
#define OSPI_INDIRECT_TRIGGER_ADDR_RANGE_REG_IND_RANGE_RESV1_FLD_SIZE 28

/** bit field defines for ospi_s#flash_command_ctrl_mem_reg */
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_TRIGGER_MEM_BANK_REQ_FLD_OFFSET 0
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_TRIGGER_MEM_BANK_REQ_FLD_SIZE 1
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_MEM_BANK_REQ_IN_PROGRESS_FLD_OFFSET 1
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_MEM_BANK_REQ_IN_PROGRESS_FLD_SIZE 1
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_FLASH_COMMAND_CTRL_MEM_RESV3_FLD_OFFSET 2
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_FLASH_COMMAND_CTRL_MEM_RESV3_FLD_SIZE 6
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_MEM_BANK_READ_DATA_FLD_OFFSET 8
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_MEM_BANK_READ_DATA_FLD_SIZE 8
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_NB_OF_STIG_READ_BYTES_FLD_OFFSET 16
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_NB_OF_STIG_READ_BYTES_FLD_SIZE 3
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_FLASH_COMMAND_CTRL_MEM_RESV2_FLD_OFFSET 19
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_FLASH_COMMAND_CTRL_MEM_RESV2_FLD_SIZE 1
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_MEM_BANK_ADDR_FLD_OFFSET 20
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_MEM_BANK_ADDR_FLD_SIZE 9
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_FLASH_COMMAND_CTRL_MEM_RESV1_FLD_OFFSET 29
#define OSPI_FLASH_COMMAND_CTRL_MEM_REG_FLASH_COMMAND_CTRL_MEM_RESV1_FLD_SIZE 3

/** bit field defines for ospi_s#flash_cmd_ctrl_reg */
#define OSPI_FLASH_CMD_CTRL_REG_CMD_EXEC_FLD_OFFSET 0
#define OSPI_FLASH_CMD_CTRL_REG_CMD_EXEC_FLD_SIZE 1
#define OSPI_FLASH_CMD_CTRL_REG_CMD_EXEC_STATUS_FLD_OFFSET 1
#define OSPI_FLASH_CMD_CTRL_REG_CMD_EXEC_STATUS_FLD_SIZE 1
#define OSPI_FLASH_CMD_CTRL_REG_STIG_MEM_BANK_EN_FLD_OFFSET 2
#define OSPI_FLASH_CMD_CTRL_REG_STIG_MEM_BANK_EN_FLD_SIZE 1
#define OSPI_FLASH_CMD_CTRL_REG_FLASH_CMD_CTRL_RESV1_FLD_OFFSET 3
#define OSPI_FLASH_CMD_CTRL_REG_FLASH_CMD_CTRL_RESV1_FLD_SIZE 4
#define OSPI_FLASH_CMD_CTRL_REG_NUM_DUMMY_CYCLES_FLD_OFFSET 7
#define OSPI_FLASH_CMD_CTRL_REG_NUM_DUMMY_CYCLES_FLD_SIZE 5
#define OSPI_FLASH_CMD_CTRL_REG_NUM_WR_DATA_BYTES_FLD_OFFSET 12
#define OSPI_FLASH_CMD_CTRL_REG_NUM_WR_DATA_BYTES_FLD_SIZE 3
#define OSPI_FLASH_CMD_CTRL_REG_ENB_WRITE_DATA_FLD_OFFSET 15
#define OSPI_FLASH_CMD_CTRL_REG_ENB_WRITE_DATA_FLD_SIZE 1
#define OSPI_FLASH_CMD_CTRL_REG_NUM_ADDR_BYTES_FLD_OFFSET 16
#define OSPI_FLASH_CMD_CTRL_REG_NUM_ADDR_BYTES_FLD_SIZE 2
#define OSPI_FLASH_CMD_CTRL_REG_ENB_MODE_BIT_FLD_OFFSET 18
#define OSPI_FLASH_CMD_CTRL_REG_ENB_MODE_BIT_FLD_SIZE 1
#define OSPI_FLASH_CMD_CTRL_REG_ENB_COMD_ADDR_FLD_OFFSET 19
#define OSPI_FLASH_CMD_CTRL_REG_ENB_COMD_ADDR_FLD_SIZE 1
#define OSPI_FLASH_CMD_CTRL_REG_NUM_RD_DATA_BYTES_FLD_OFFSET 20
#define OSPI_FLASH_CMD_CTRL_REG_NUM_RD_DATA_BYTES_FLD_SIZE 3
#define OSPI_FLASH_CMD_CTRL_REG_ENB_READ_DATA_FLD_OFFSET 23
#define OSPI_FLASH_CMD_CTRL_REG_ENB_READ_DATA_FLD_SIZE 1
#define OSPI_FLASH_CMD_CTRL_REG_CMD_OPCODE_FLD_OFFSET 24
#define OSPI_FLASH_CMD_CTRL_REG_CMD_OPCODE_FLD_SIZE 8

/** bit field defines for ospi_s#flash_cmd_addr_reg */
#define OSPI_FLASH_CMD_ADDR_REG_ADDR_FLD_OFFSET 0
#define OSPI_FLASH_CMD_ADDR_REG_ADDR_FLD_SIZE 32

/** bit field defines for ospi_s#flash_rd_data_lower_reg */
#define OSPI_FLASH_RD_DATA_LOWER_REG_DATA_FLD_OFFSET 0
#define OSPI_FLASH_RD_DATA_LOWER_REG_DATA_FLD_SIZE 32

/** bit field defines for ospi_s#flash_rd_data_upper_reg */
#define OSPI_FLASH_RD_DATA_UPPER_REG_DATA_FLD_OFFSET 0
#define OSPI_FLASH_RD_DATA_UPPER_REG_DATA_FLD_SIZE 32

/** bit field defines for ospi_s#flash_wr_data_lower_reg */
#define OSPI_FLASH_WR_DATA_LOWER_REG_DATA_FLD_OFFSET 0
#define OSPI_FLASH_WR_DATA_LOWER_REG_DATA_FLD_SIZE 32

/** bit field defines for ospi_s#flash_wr_data_upper_reg */
#define OSPI_FLASH_WR_DATA_UPPER_REG_DATA_FLD_OFFSET 0
#define OSPI_FLASH_WR_DATA_UPPER_REG_DATA_FLD_SIZE 32

/** bit field defines for ospi_s#polling_flash_status_reg */
#define OSPI_POLLING_FLASH_STATUS_REG_DEVICE_STATUS_FLD_OFFSET 0
#define OSPI_POLLING_FLASH_STATUS_REG_DEVICE_STATUS_FLD_SIZE 8
#define OSPI_POLLING_FLASH_STATUS_REG_DEVICE_STATUS_VALID_FLD_OFFSET 8
#define OSPI_POLLING_FLASH_STATUS_REG_DEVICE_STATUS_VALID_FLD_SIZE 1
#define OSPI_POLLING_FLASH_STATUS_REG_DEVICE_STATUS_RSVD_FLD1_OFFSET 9
#define OSPI_POLLING_FLASH_STATUS_REG_DEVICE_STATUS_RSVD_FLD1_SIZE 7
#define OSPI_POLLING_FLASH_STATUS_REG_DEVICE_STATUS_NB_DUMMY_OFFSET 16
#define OSPI_POLLING_FLASH_STATUS_REG_DEVICE_STATUS_NB_DUMMY_SIZE 5
#define OSPI_POLLING_FLASH_STATUS_REG_DEVICE_STATUS_RSVD_FLD2_OFFSET 21
#define OSPI_POLLING_FLASH_STATUS_REG_DEVICE_STATUS_RSVD_FLD2_SIZE 11

/** bit field defines for ospi_s#phy_configuration_reg */
#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_RX_DLL_DELAY_FLD_OFFSET 0
#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_RX_DLL_DELAY_FLD_SIZE 7
#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_RESV1_FLD_OFFSET 7
#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_RESV1_FLD_SIZE 9
#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_TX_DLL_DELAY_FLD_OFFSET 16
#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_TX_DLL_DELAY_FLD_SIZE 7
#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_RESV2_FLD_OFFSET 23
#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_RESV2_FLD_SIZE 6
#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_RX_DLL_BYPASS_FLD_OFFSET 29
#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_RX_DLL_BYPASS_FLD_SIZE 1
#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_RESET_FLD_OFFSET 30
#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_RESET_FLD_SIZE 1
#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_RESYNC_FLD_OFFSET 31
#define OSPI_PHY_CONFIGURATION_REG_PHY_CONFIG_RESYNC_FLD_SIZE 1

/** bit field defines for ospi_s#phy_master_control_reg */
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_INITIAL_DELAY_FLD_OFFSET 0
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_INITIAL_DELAY_FLD_SIZE 7
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_CONTROL_RESV1_FLD_OFFSET 7
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_CONTROL_RESV1_FLD_SIZE 9
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_NB_INDICATIONS_FLD_OFFSET 16
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_NB_INDICATIONS_FLD_SIZE 3
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_CONTROL_RESV2_FLD_OFFSET 19
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_CONTROL_RESV2_FLD_SIZE 1
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_PHASE_DETECT_SELECTOR_FLD_OFFSET 20
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_PHASE_DETECT_SELECTOR_FLD_SIZE 3
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_BYPASS_MODE_FLD_OFFSET 23
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_BYPASS_MODE_FLD_SIZE 1
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_LOCK_MODE_FLD_OFFSET 24
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_LOCK_MODE_FLD_SIZE 1
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_CONTROL_RESV3_FLD_OFFSET 25
#define OSPI_PHY_MASTER_CONTROL_REG_PHY_MASTER_CONTROL_RESV3_FLD_SIZE 7

/** bit field defines for ospi_s#dll_observable_lower_reg */
#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_DLL_LOCK_FLD_OFFSET 0
#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_DLL_LOCK_FLD_SIZE 1
#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_LOCK_MODE_FLD_OFFSET 1
#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_LOCK_MODE_FLD_SIZE 2
#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_UNLOCK_COUNTER_FLD_OFFSET 3
#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_UNLOCK_COUNTER_FLD_SIZE 5
#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_LOCK_VALUE_FLD_OFFSET 8
#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_LOCK_VALUE_FLD_SIZE 7
#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_LOOPBACK_LOCK_FLD_OFFSET 15
#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_LOOPBACK_LOCK_FLD_SIZE 1
#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_DLL_LOCK_DEC_FLD_OFFSET 16
#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_DLL_LOCK_DEC_FLD_SIZE 8
#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_DLL_LOCK_INC_FLD_OFFSET 24
#define OSPI_DLL_OBSERVABLE_LOWER_REG_DLL_OBSERVABLE_LOWER_DLL_LOCK_INC_FLD_SIZE 8

/** bit field defines for ospi_s#dll_observable_upper_reg */
#define OSPI_DLL_OBSERVABLE_UPPER_REG_DLL_OBSERVABLE__UPPER_RX_DECODER_OUTPUT_FLD_OFFSET 0
#define OSPI_DLL_OBSERVABLE_UPPER_REG_DLL_OBSERVABLE__UPPER_RX_DECODER_OUTPUT_FLD_SIZE 7
#define OSPI_DLL_OBSERVABLE_UPPER_REG_DLL_OBSERVABLE_UPPER_RESV1_FLD_OFFSET 7
#define OSPI_DLL_OBSERVABLE_UPPER_REG_DLL_OBSERVABLE_UPPER_RESV1_FLD_SIZE 9
#define OSPI_DLL_OBSERVABLE_UPPER_REG_DLL_OBSERVABLE_UPPER_TX_DECODER_OUTPUT_FLD_OFFSET 16
#define OSPI_DLL_OBSERVABLE_UPPER_REG_DLL_OBSERVABLE_UPPER_TX_DECODER_OUTPUT_FLD_SIZE 7
#define OSPI_DLL_OBSERVABLE_UPPER_REG_DLL_OBSERVABLE_UPPER_RESV2_FLD_OFFSET 23
#define OSPI_DLL_OBSERVABLE_UPPER_REG_DLL_OBSERVABLE_UPPER_RESV2_FLD_SIZE 9

/** bit field defines for ospi_s#opcode_ext_lower_reg */
#define OSPI_OPCODE_EXT_LOWER_REG_EXT_STIG_OPCODE_FLD_OFFSET 0
#define OSPI_OPCODE_EXT_LOWER_REG_EXT_STIG_OPCODE_FLD_SIZE 8
#define OSPI_OPCODE_EXT_LOWER_REG_EXT_POLL_OPCODE_FLD_OFFSET 8
#define OSPI_OPCODE_EXT_LOWER_REG_EXT_POLL_OPCODE_FLD_SIZE 8
#define OSPI_OPCODE_EXT_LOWER_REG_EXT_WRITE_OPCODE_FLD_OFFSET 16
#define OSPI_OPCODE_EXT_LOWER_REG_EXT_WRITE_OPCODE_FLD_SIZE 8
#define OSPI_OPCODE_EXT_LOWER_REG_EXT_READ_OPCODE_FLD_OFFSET 24
#define OSPI_OPCODE_EXT_LOWER_REG_EXT_READ_OPCODE_FLD_SIZE 8

/** bit field defines for ospi_s#opcode_ext_upper_reg */
#define OSPI_OPCODE_EXT_UPPER_REG_OPCODE_EXT_UPPER_RESV1_FLD_OFFSET 0
#define OSPI_OPCODE_EXT_UPPER_REG_OPCODE_EXT_UPPER_RESV1_FLD_SIZE 16
#define OSPI_OPCODE_EXT_UPPER_REG_EXT_WEL_OPCODE_FLD_OFFSET 16
#define OSPI_OPCODE_EXT_UPPER_REG_EXT_WEL_OPCODE_FLD_SIZE 8
#define OSPI_OPCODE_EXT_UPPER_REG_WEL_OPCODE_FLD_OFFSET 24
#define OSPI_OPCODE_EXT_UPPER_REG_WEL_OPCODE_FLD_SIZE 8

/** bit field defines for ospi_s#module_id_reg */
#define OSPI_MODULE_ID_REG_CONF_FLD_OFFSET 0
#define OSPI_MODULE_ID_REG_CONF_FLD_SIZE 2
#define OSPI_MODULE_ID_REG_MODULE_ID_RESV_FLD_OFFSET 2
#define OSPI_MODULE_ID_REG_MODULE_ID_RESV_FLD_SIZE 6
#define OSPI_MODULE_ID_REG_MODULE_ID_FLD_OFFSET 8
#define OSPI_MODULE_ID_REG_MODULE_ID_FLD_SIZE 16
#define OSPI_MODULE_ID_REG_FIX_PATCH_FLD_OFFSET 24
#define OSPI_MODULE_ID_REG_FIX_PATCH_FLD_SIZE 8

/* EOF ospi.h */
#endif
