; 
; Copyright (C) u-blox
; All rights reserved.
; This source file is the sole property of u-blox. Reproduction or utilization
; of this source in whole or part is forbidden without the written consent of
; u-blox.
; 
; FILE: otp_ctrl.hs

OTP_CTRL_OTP_STATUS EQU 0x000
OTP_CTRL_OTP_COMMAND_SET EQU 0x004
OTP_CTRL_OTP_ADDRESS EQU 0x008
OTP_CTRL_OTP_WRITE_DATA EQU 0x00C
OTP_CTRL_OTP_COUNT_STEP EQU 0x010
OTP_CTRL_OTP_BURN_COUNT EQU 0x014
OTP_CTRL_OTP_ERROR EQU 0x018
OTP_CTRL_OTP_READ_LOCK_1 EQU 0x01C
OTP_CTRL_OTP_READ_LOCK_2 EQU 0x020
OTP_CTRL_OTP_IRQ_MASK EQU 0x024
OTP_CTRL_OTP_SHADOW_REGION_1 EQU 0x100
OTP_CTRL_OTP_SHADOW_REGION_2 EQU 0x104
OTP_CTRL_OTP_WRITE_PROTECT EQU 0xFB0
OTP_CTRL_PERIPHERALID4 EQU 0xFD0
OTP_CTRL_PERIPHERALID5 EQU 0xFD4
OTP_CTRL_PERIPHERALID6 EQU 0xFD8
OTP_CTRL_PERIPHERALID7 EQU 0xFDC
OTP_CTRL_PERIPHERALID0 EQU 0xFE0
OTP_CTRL_PERIPHERALID1 EQU 0xFE4
OTP_CTRL_PERIPHERALID2 EQU 0xFE8
OTP_CTRL_PERIPHERALID3 EQU 0xFEC
OTP_CTRL_COMPONENTID0 EQU 0xFF0
OTP_CTRL_COMPONENTID2 EQU 0xFF4
OTP_CTRL_COMPONENTID3 EQU 0xFF8
OTP_CTRL_COMPONENTID4 EQU 0xFFC
; EOF: otp_ctrl.hs
   END
