#ifndef INCLUDED_PSRAM
#define INCLUDED_PSRAM
/*
 * Copyright (C) u-blox 
 * All rights reserved. 
 * This source file is the sole property of u-blox. Reproduction or utilization 
 * of this source in whole or part is forbidden without the written consent of 
 * u-blox.
 *
 */

#include <stdint.h>

/** psram HAL Spreadsheet version number */
#define PSRAM_HAL_VERSION 1

/** PSRAM IP.  
This module implements an AXI3-compatible PSRAM controller for Winbond and ISSI PSRAM devices
*/
struct psram_s {
   /** Mask to select which bits of the AXI ID will be used for priority selection. at address offset 0x000, read-write */
   uint32_t axi_id_prio_sel_mask0;
   /** Mask to select which bits of the AXI ID will be used for priority selection. at address offset 0x004, read-write */
   uint32_t axi_id_prio_sel_mask1;
   /** Mask to select which bits of the AXI ID will be used for priority selection. at address offset 0x008, read-write */
   uint32_t axi_id_prio_sel_mask2;
   /** Mask to select which bits of the AXI ID will be used for priority selection. at address offset 0x00C, read-write */
   uint32_t axi_id_prio_sel_mask3;
   /** Level of the masked AXI ID bits that corresponds to high priority. All other values will be low priority. at address offset 0x010, read-write */
   uint32_t axi_id_prio_sel_level0;
   /** Level of the masked AXI ID bits that corresponds to high priority. All other values will be low priority. at address offset 0x014, read-write */
   uint32_t axi_id_prio_sel_level1;
   /** Level of the masked AXI ID bits that corresponds to high priority. All other values will be low priority. at address offset 0x018, read-write */
   uint32_t axi_id_prio_sel_level2;
   /** Level of the masked AXI ID bits that corresponds to high priority. All other values will be low priority. at address offset 0x01C, read-write */
   uint32_t axi_id_prio_sel_level3;
   /** AXI control at address offset 0x020, read-write */
   uint32_t axi_ctrl;
   /** Synchronous reset abort request at address offset 0x024, read-write */
   uint32_t sync_reset_req;
   /** AXI busy at address offset 0x028, read-only */
   uint32_t axi_busy;
   /** Address width of the controlled PSRAM memory. at address offset 0x02C, read-write */
   uint32_t psram_addr_width;
   /** Configure the row length at which transaction splitting should happen if enabled. The minimum row length is 64 PSRAM words (16 bits). at address offset 0x030, read-write */
   uint32_t psram_row_length_split_cfg;
   /** Configure the arbitration ratio between read and write transactions. The default (reset) setting is for one write out of 8 transactions (1/8). Other values the the ones specified below will result in unpredictable behavior. at address offset 0x034, read-write */
   uint32_t psram_ar_aw_arb_prio_cnt_sel;
   /** Reserved space */
   uint8_t fill0[200];
   /**  Unmasked status of write/read requests to PSRAM configuration registers. at address offset 0x100, read-only */
   uint32_t psram_irq_and_fault_status_raw;
   /** Masked status of write/read requests to PSRAM configuration registers. at address offset 0x104, read-only */
   uint32_t psram_irq_and_fault_status;
   /** Mask set register. Used to mask psram_cfg_status_raw. at address offset 0x108, read-write */
   uint32_t psram_irq_and_fault_status_mask_set;
   /** Mask clear register. Used to mask psram_cfg_status_raw. at address offset 0x10C, read-write */
   uint32_t psram_irq_and_fault_status_mask_clr;
   /** Mask status register. Used to mask psram_cfg_status_raw. at address offset 0x110, read-only */
   uint32_t psram_irq_and_fault_status_mask_status;
   /** Clear status of write/read acknowledge registers. at address offset 0x114, read-write */
   uint32_t psram_irq_and_fault_status_clr;
   /** Reserved space */
   uint8_t fill1[232];
   /** States of AXI_FE internal FSMs to be used only for debug at address offset 0x200, read-only */
   uint32_t psram_fe_debug_fsm_states;
   /** The address of the command output from the AXI_FE that is pushed into the Command async fifo at address offset 0x204, read-only */
   uint32_t psram_fe_debug_command_addr;
   /** The control of the  command output from the AXI_FE that is pushed into the Command async fifo at address offset 0x208, read-only */
   uint32_t psram_fe_debug_command;
   /** Status of the AXI_FE internal FIFOs. Empty and full information. at address offset 0x20C, read-only */
   uint32_t psram_fe_debug_fifo_status;
   /** Status of the AXI_FE internal arbiter counters. at address offset 0x210, read-only */
   uint32_t psram_fe_debug_arbiter_cnt;
   /** PSRAM controller-PHY debug register at address offset 0x214, read-only */
   uint32_t psram_controller_phy_debug;
   /** PSRAM controller-phy internal counters at address offset 0x218, read-only */
   uint32_t psram_controller_phy_debug_cnt;
   /** PSRAM HW observation control register at address offset 0x21C, read-write */
   uint32_t psram_hwobs_control;
   /** Reserved space */
   uint8_t fill2[224];
   /** PSRAM bus configuration registers (BCR) at address offset 0x300, read-write */
   uint32_t bcr;
   /** PSRAM refresh configuration register (RCR) at address offset 0x304, read-write */
   uint32_t rcr;
   /** PSRAM device identification register (DIDR) at address offset 0x308, read-only */
   uint32_t didr;
   /** BCR write request to PSRAM. at address offset 0x30C, read-write */
   uint32_t bcr_write_req;
   /** BCR read request from PSRAM. at address offset 0x310, read-write */
   uint32_t bcr_read_req;
   /** RCR write request to PSRAM. at address offset 0x314, read-write */
   uint32_t rcr_write_req;
   /** RCR read request from PSRAM. at address offset 0x318, read-write */
   uint32_t rcr_read_req;
   /** DIDR read request from PSRAM. at address offset 0x31C, read-write */
   uint32_t didr_read_req;
   /** Reserved space */
   uint8_t fill3[224];
   /** PHY TX Configuration Register at address offset 0x400, read-write */
   uint32_t phy_tx_dll_configuration;
   /** PHY RX Configuration Register at address offset 0x404, read-write */
   uint32_t phy_rx_dll_configuration;
   /** PHY DLL Master Control Register at address offset 0x408, read-write */
   uint32_t phy_dll_master_control;
   /** Reserved space */
   uint8_t fill4[4];
   /** PHY TX DLL Observable Register (Slave DLL) at address offset 0x410, read-only */
   uint32_t phy_tx_dll_obs_reg_slave;
   /** PHY DLL Observable Register (Master DLL) at address offset 0x414, read-only */
   uint32_t phy_dll_obs_reg_master;
   /** PHY RX DLL Observable Register (Slave DLL) at address offset 0x418, read-only */
   uint32_t phy_rx_dll_obs_reg_slave;
   /** Reserved space */
   uint8_t fill5[4];
   /** PHY RX read data capture register at address offset 0x420, read-write */
   uint32_t phy_read_data_capture;
   /** Asynchronous mode write and read latencies for PSRAM controller-PHY at address offset 0x424, read-write */
   uint32_t async_mode_latency;
   /** DPD exit counter at address offset 0x428, read-write */
   uint32_t dpd_exit_counter;
   /** DPD exit control register at address offset 0x42C, read-write */
   uint32_t dpd_exit;
   /** PSRAM controller-PHY status at address offset 0x430, read-only */
   uint32_t psram_controller_phy_status;
   /** PSRAM controller-PHY ignore command at address offset 0x434, read-write */
   uint32_t psram_controller_phy_ignore;
   /** Generic PSRAM controller-PHY configuration register at address offset 0x438, read-write */
   uint32_t psram_controller_phy_cfg;
   /** Synchronous mode (SDR/DDR) write and read latency for PSRAM controller-PHY.\n This register sets the initial latency (for writes and read independently) between PSRAM address and data phase at address offset 0x43C, read-write */
   uint32_t sync_mode_latency;
   /** Reserved space */
   uint8_t fill6[192];
   /** DFT loopback control registers (lower byte - [7:0]) at address offset 0x500, read-write */
   uint32_t dft_loopback_control_lb;
   /** DFT loopback control registers (upper byte - [15:8]) at address offset 0x504, read-write */
   uint32_t dft_loopback_control_ub;
   /** DFT loopback data observable registers at address offset 0x508, read-only */
   uint32_t dft_loopback_obs_reg;
   /** DFT PSRAM memory control register. at address offset 0x50C, read-write */
   uint32_t dft_mem_ctrl;
   /** DFT PSRAM memory command register at address offset 0x510, read-write */
   uint32_t dft_mem_command;
   /** DFT PSRAM memory write data register (positive edge). Used in asynchronous and synchronous SDR mode at address offset 0x514, read-write */
   uint32_t dft_mem_write_data_pos;
   /** DFT PSRAM memory write data register (negative edge). Only used in sychronous DDR mode at address offset 0x518, read-write */
   uint32_t dft_mem_write_data_neg;
   /** DFT PSRAM memory read data and pass/fail register (positive edge). Used in async and synchronous SDR mode at address offset 0x51C, read-only */
   uint32_t dft_mem_read_data_pos;
   /** DFT PSRAM memory read data and pass/fail register (negative edge). Only used in sychronous DDR mode. at address offset 0x520, read-only */
   uint32_t dft_mem_read_data_neg;
   /** DFT PSRAM read configuration register (in case the command request a CRE access) at address offset 0x524, read-only */
   uint32_t dft_mem_read_data_cfg_regs;
};

/** bit field defines for psram_s#axi_id_prio_sel_mask0 */
#define PSRAM_AXI_ID_PRIO_SEL_MASK0_MASK_OFFSET 0
#define PSRAM_AXI_ID_PRIO_SEL_MASK0_MASK_SIZE 10

/** bit field defines for psram_s#axi_id_prio_sel_mask1 */
#define PSRAM_AXI_ID_PRIO_SEL_MASK1_MASK_OFFSET 0
#define PSRAM_AXI_ID_PRIO_SEL_MASK1_MASK_SIZE 10

/** bit field defines for psram_s#axi_id_prio_sel_mask2 */
#define PSRAM_AXI_ID_PRIO_SEL_MASK2_MASK_OFFSET 0
#define PSRAM_AXI_ID_PRIO_SEL_MASK2_MASK_SIZE 10

/** bit field defines for psram_s#axi_id_prio_sel_mask3 */
#define PSRAM_AXI_ID_PRIO_SEL_MASK3_MASK_OFFSET 0
#define PSRAM_AXI_ID_PRIO_SEL_MASK3_MASK_SIZE 10

/** bit field defines for psram_s#axi_id_prio_sel_level0 */
#define PSRAM_AXI_ID_PRIO_SEL_LEVEL0_LEVEL_OFFSET 0
#define PSRAM_AXI_ID_PRIO_SEL_LEVEL0_LEVEL_SIZE 10

/** bit field defines for psram_s#axi_id_prio_sel_level1 */
#define PSRAM_AXI_ID_PRIO_SEL_LEVEL1_LEVEL_OFFSET 0
#define PSRAM_AXI_ID_PRIO_SEL_LEVEL1_LEVEL_SIZE 10

/** bit field defines for psram_s#axi_id_prio_sel_level2 */
#define PSRAM_AXI_ID_PRIO_SEL_LEVEL2_LEVEL_OFFSET 0
#define PSRAM_AXI_ID_PRIO_SEL_LEVEL2_LEVEL_SIZE 10

/** bit field defines for psram_s#axi_id_prio_sel_level3 */
#define PSRAM_AXI_ID_PRIO_SEL_LEVEL3_LEVEL_OFFSET 0
#define PSRAM_AXI_ID_PRIO_SEL_LEVEL3_LEVEL_SIZE 10

/** bit field defines for psram_s#axi_ctrl */
#define PSRAM_AXI_CTRL_AXI_ENABLE_OFFSET 0
#define PSRAM_AXI_CTRL_AXI_ENABLE_SIZE 1
#define PSRAM_AXI_CTRL_MAP_TO_NON_BUFF_OFFSET 1
#define PSRAM_AXI_CTRL_MAP_TO_NON_BUFF_SIZE 1

/** bit field defines for psram_s#sync_reset_req */
#define PSRAM_SYNC_RESET_REQ_SYNC_RESET_REQ_ASYNC_FIFOS_OFFSET 0
#define PSRAM_SYNC_RESET_REQ_SYNC_RESET_REQ_ASYNC_FIFOS_SIZE 1

/** bit field defines for psram_s#axi_busy */
#define PSRAM_AXI_BUSY_AXI_BUSY_OFFSET 0
#define PSRAM_AXI_BUSY_AXI_BUSY_SIZE 1
#define PSRAM_AXI_BUSY_DEFAULT_SLAVE_BUSY_OFFSET 1
#define PSRAM_AXI_BUSY_DEFAULT_SLAVE_BUSY_SIZE 1

/** bit field defines for psram_s#psram_addr_width */
#define PSRAM_PSRAM_ADDR_WIDTH_PSRAM_ADDR_WIDTH_OFFSET 0
#define PSRAM_PSRAM_ADDR_WIDTH_PSRAM_ADDR_WIDTH_SIZE 25

/** bit field defines for psram_s#psram_row_length_split_cfg */
#define PSRAM_PSRAM_ROW_LENGTH_SPLIT_CFG_PSRAM_ROW_LENGTH_LOWER_OFFSET 0
#define PSRAM_PSRAM_ROW_LENGTH_SPLIT_CFG_PSRAM_ROW_LENGTH_LOWER_SIZE 6
#define PSRAM_PSRAM_ROW_LENGTH_SPLIT_CFG_PSRAM_ROW_LENGTH_UPPER_OFFSET 6
#define PSRAM_PSRAM_ROW_LENGTH_SPLIT_CFG_PSRAM_ROW_LENGTH_UPPER_SIZE 6
#define PSRAM_PSRAM_ROW_LENGTH_SPLIT_CFG_PSRAM_ROW_SPLIT_ENABLE_SDR_OFFSET 30
#define PSRAM_PSRAM_ROW_LENGTH_SPLIT_CFG_PSRAM_ROW_SPLIT_ENABLE_SDR_SIZE 1
#define PSRAM_PSRAM_ROW_LENGTH_SPLIT_CFG_PSRAM_ROW_SPLIT_ENABLE_DDR_OFFSET 31
#define PSRAM_PSRAM_ROW_LENGTH_SPLIT_CFG_PSRAM_ROW_SPLIT_ENABLE_DDR_SIZE 1

/** bit field defines for psram_s#psram_ar_aw_arb_prio_cnt_sel */
#define PSRAM_PSRAM_AR_AW_ARB_PRIO_CNT_SEL_PRIO_CNT_SEL_OFFSET 0
#define PSRAM_PSRAM_AR_AW_ARB_PRIO_CNT_SEL_PRIO_CNT_SEL_SIZE 3

/** bit field defines for psram_s#psram_irq_and_fault_status_raw */
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_RAW_BCR_WRITE_ACK_OFFSET 0
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_RAW_BCR_WRITE_ACK_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_RAW_BCR_READ_ACK_OFFSET 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_RAW_BCR_READ_ACK_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_RAW_RCR_WRITE_ACK_OFFSET 2
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_RAW_RCR_WRITE_ACK_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_RAW_RCR_READ_ACK_OFFSET 3
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_RAW_RCR_READ_ACK_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_RAW_DIDR_READ_ACK_OFFSET 4
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_RAW_DIDR_READ_ACK_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_RAW_BCR_SYNC_FAULT_OFFSET 5
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_RAW_BCR_SYNC_FAULT_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_RAW_PROG_WHILE_EN_FAULT_OFFSET 6
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_RAW_PROG_WHILE_EN_FAULT_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_RAW_RX_TIMEOUT_FAULT_OFFSET 7
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_RAW_RX_TIMEOUT_FAULT_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_RAW_DLL_MASTER_UNLOCK_FAULT_OFFSET 8
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_RAW_DLL_MASTER_UNLOCK_FAULT_SIZE 1

/** bit field defines for psram_s#psram_irq_and_fault_status */
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_BCR_WRITE_ACK_OFFSET 0
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_BCR_WRITE_ACK_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_BCR_READ_ACK_OFFSET 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_BCR_READ_ACK_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_RCR_WRITE_ACK_OFFSET 2
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_RCR_WRITE_ACK_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_RCR_READ_ACK_OFFSET 3
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_RCR_READ_ACK_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_DIDR_READ_ACK_OFFSET 4
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_DIDR_READ_ACK_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_BCR_SYNC_FAULT_OFFSET 5
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_BCR_SYNC_FAULT_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_PROG_WHILE_EN_FAULT_OFFSET 6
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_PROG_WHILE_EN_FAULT_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_RX_TIMEOUT_FAULT_OFFSET 7
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_RX_TIMEOUT_FAULT_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_DLL_MASTER_UNLOCK_FAULT_OFFSET 8
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_DLL_MASTER_UNLOCK_FAULT_SIZE 1

/** bit field defines for psram_s#psram_irq_and_fault_status_mask_set */
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_SET_BCR_WRITE_ACK_OFFSET 0
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_SET_BCR_WRITE_ACK_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_SET_BCR_READ_ACK_OFFSET 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_SET_BCR_READ_ACK_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_SET_RCR_WRITE_ACK_OFFSET 2
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_SET_RCR_WRITE_ACK_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_SET_RCR_READ_ACK_OFFSET 3
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_SET_RCR_READ_ACK_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_SET_DIDR_READ_ACK_OFFSET 4
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_SET_DIDR_READ_ACK_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_SET_BCR_SYNC_FAULT_OFFSET 5
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_SET_BCR_SYNC_FAULT_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_SET_PROG_WHILE_EN_FAULT_OFFSET 6
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_SET_PROG_WHILE_EN_FAULT_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_SET_RX_TIMEOUT_FAULT_OFFSET 7
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_SET_RX_TIMEOUT_FAULT_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_SET_DLL_MASTER_UNLOCK_FAULT_OFFSET 8
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_SET_DLL_MASTER_UNLOCK_FAULT_SIZE 1

/** bit field defines for psram_s#psram_irq_and_fault_status_mask_clr */
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_CLR_BCR_WRITE_ACK_OFFSET 0
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_CLR_BCR_WRITE_ACK_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_CLR_BCR_READ_ACK_OFFSET 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_CLR_BCR_READ_ACK_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_CLR_RCR_WRITE_ACK_OFFSET 2
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_CLR_RCR_WRITE_ACK_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_CLR_RCR_READ_ACK_OFFSET 3
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_CLR_RCR_READ_ACK_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_CLR_DIDR_READ_ACK_OFFSET 4
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_CLR_DIDR_READ_ACK_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_CLR_BCR_SYNC_FAULT_OFFSET 5
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_CLR_BCR_SYNC_FAULT_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_CLR_PROG_WHILE_EN_FAULT_OFFSET 6
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_CLR_PROG_WHILE_EN_FAULT_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_CLR_RX_TIMEOUT_FAULT_OFFSET 7
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_CLR_RX_TIMEOUT_FAULT_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_CLR_DLL_MASTER_UNLOCK_FAULT_OFFSET 8
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_CLR_DLL_MASTER_UNLOCK_FAULT_SIZE 1

/** bit field defines for psram_s#psram_irq_and_fault_status_mask_status */
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_STATUS_BCR_WRITE_ACK_OFFSET 0
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_STATUS_BCR_WRITE_ACK_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_STATUS_BCR_READ_ACK_OFFSET 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_STATUS_BCR_READ_ACK_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_STATUS_RCR_WRITE_ACK_OFFSET 2
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_STATUS_RCR_WRITE_ACK_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_STATUS_RCR_READ_ACK_OFFSET 3
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_STATUS_RCR_READ_ACK_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_STATUS_DIDR_READ_ACK_OFFSET 4
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_STATUS_DIDR_READ_ACK_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_STATUS_BCR_SYNC_FAULT_OFFSET 5
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_STATUS_BCR_SYNC_FAULT_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_STATUS_PROG_WHILE_EN_FAULT_OFFSET 6
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_STATUS_PROG_WHILE_EN_FAULT_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_STATUS_RX_TIMEOUT_FAULT_OFFSET 7
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_STATUS_RX_TIMEOUT_FAULT_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_STATUS_DLL_MASTER_UNLOCK_FAULT_OFFSET 8
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_MASK_STATUS_DLL_MASTER_UNLOCK_FAULT_SIZE 1

/** bit field defines for psram_s#psram_irq_and_fault_status_clr */
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_CLR_BCR_WRITE_ACK_OFFSET 0
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_CLR_BCR_WRITE_ACK_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_CLR_BCR_READ_ACK_OFFSET 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_CLR_BCR_READ_ACK_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_CLR_RCR_WRITE_ACK_OFFSET 2
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_CLR_RCR_WRITE_ACK_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_CLR_RCR_READ_ACK_OFFSET 3
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_CLR_RCR_READ_ACK_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_CLR_DIDR_READ_ACK_OFFSET 4
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_CLR_DIDR_READ_ACK_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_CLR_BCR_SYNC_FAULT_OFFSET 5
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_CLR_BCR_SYNC_FAULT_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_CLR_PROG_WHILE_EN_FAULT_OFFSET 6
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_CLR_PROG_WHILE_EN_FAULT_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_CLR_RX_TIMEOUT_FAULT_OFFSET 7
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_CLR_RX_TIMEOUT_FAULT_SIZE 1
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_CLR_DLL_MASTER_UNLOCK_FAULT_OFFSET 8
#define PSRAM_PSRAM_IRQ_AND_FAULT_STATUS_CLR_DLL_MASTER_UNLOCK_FAULT_SIZE 1

/** bit field defines for psram_s#psram_fe_debug_fsm_states */
#define PSRAM_PSRAM_FE_DEBUG_FSM_STATES_PSRAM_FE_WDATA_CONV_FSM_STATE_OFFSET 0
#define PSRAM_PSRAM_FE_DEBUG_FSM_STATES_PSRAM_FE_WDATA_CONV_FSM_STATE_SIZE 3
#define PSRAM_PSRAM_FE_DEBUG_FSM_STATES_PSRAM_FE_RDATA_CONV_FSM_STATE_OFFSET 3
#define PSRAM_PSRAM_FE_DEBUG_FSM_STATES_PSRAM_FE_RDATA_CONV_FSM_STATE_SIZE 3
#define PSRAM_PSRAM_FE_DEBUG_FSM_STATES_PSRAM_FE_BRESP_CONV_FSM_STATE_OFFSET 6
#define PSRAM_PSRAM_FE_DEBUG_FSM_STATES_PSRAM_FE_BRESP_CONV_FSM_STATE_SIZE 2

/** bit field defines for psram_s#psram_fe_debug_command_addr */
#define PSRAM_PSRAM_FE_DEBUG_COMMAND_ADDR_PSRAM_FE_COMMAND_ADDR_OFFSET 0
#define PSRAM_PSRAM_FE_DEBUG_COMMAND_ADDR_PSRAM_FE_COMMAND_ADDR_SIZE 32

/** bit field defines for psram_s#psram_fe_debug_command */
#define PSRAM_PSRAM_FE_DEBUG_COMMAND_PSRAM_FE_COMMAND_CTRL_OFFSET 0
#define PSRAM_PSRAM_FE_DEBUG_COMMAND_PSRAM_FE_COMMAND_CTRL_SIZE 32

/** bit field defines for psram_s#psram_fe_debug_fifo_status */
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_TRANS_HAZARD_BUF_FULL_OFFSET 0
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_TRANS_HAZARD_BUF_FULL_SIZE 1
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_SIZE_MPRIO_FULL_OFFSET 1
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_SIZE_MPRIO_FULL_SIZE 1
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_SIZE_HPRIO_FULL_OFFSET 2
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_SIZE_HPRIO_FULL_SIZE 1
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_MPRIO_VALID_FIFO_FULL_OFFSET 3
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_MPRIO_VALID_FIFO_FULL_SIZE 1
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_MPRIO_FIFO_FULL_OFFSET 4
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_MPRIO_FIFO_FULL_SIZE 1
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_HPRIO_VALID_FIFO_FULL_OFFSET 5
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_HPRIO_VALID_FIFO_FULL_SIZE 1
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_HPRIO_FIFO_FULL_OFFSET 6
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_HPRIO_FIFO_FULL_SIZE 1
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_CTRL_FIFO_FULL_OFFSET 7
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_CTRL_FIFO_FULL_SIZE 1
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AW_BUF_BRESP_FIFO_FULL_OFFSET 8
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AW_BUF_BRESP_FIFO_FULL_SIZE 1
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AW_NONBUF_BRESP_FIFO_FULL_OFFSET 9
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AW_NONBUF_BRESP_FIFO_FULL_SIZE 1
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AW_ID_FIFO_FULL_OFFSET 10
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AW_ID_FIFO_FULL_SIZE 1
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AW_CTRL_FIFO_FULL_OFFSET 11
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AW_CTRL_FIFO_FULL_SIZE 1
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AW_VALID_FIFO_FULL_OFFSET 12
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AW_VALID_FIFO_FULL_SIZE 1
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AW_FIFO_FULL_OFFSET 13
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AW_FIFO_FULL_SIZE 1
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_TRANS_HAZARD_BUF_EMPTY_OFFSET 14
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_TRANS_HAZARD_BUF_EMPTY_SIZE 1
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_SIZE_MPRIO_EMPTY_OFFSET 15
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_SIZE_MPRIO_EMPTY_SIZE 1
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_SIZE_HPRIO_EMPTY_OFFSET 16
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_SIZE_HPRIO_EMPTY_SIZE 1
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_MPRIO_VALID_FIFO_EMPTY_OFFSET 17
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_MPRIO_VALID_FIFO_EMPTY_SIZE 1
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_MPRIO_FIFO_EMPTY_OFFSET 18
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_MPRIO_FIFO_EMPTY_SIZE 1
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_HPRIO_VALID_FIFO_EMPTY_OFFSET 19
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_HPRIO_VALID_FIFO_EMPTY_SIZE 1
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_HPRIO_FIFO_EMPTY_OFFSET 20
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_HPRIO_FIFO_EMPTY_SIZE 1
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_CTRL_FIFO_EMPTY_OFFSET 21
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AR_CTRL_FIFO_EMPTY_SIZE 1
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AW_BUF_BRESP_FIFO_EMPTY_OFFSET 22
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AW_BUF_BRESP_FIFO_EMPTY_SIZE 1
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AW_NONBUF_BRESP_FIFO_EMPTY_OFFSET 23
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AW_NONBUF_BRESP_FIFO_EMPTY_SIZE 1
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AW_ID_FIFO_EMPTY_OFFSET 24
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AW_ID_FIFO_EMPTY_SIZE 1
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AW_CTRL_FIFO_EMPTY_OFFSET 25
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AW_CTRL_FIFO_EMPTY_SIZE 1
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AW_VALID_FIFO_EMPTY_OFFSET 26
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AW_VALID_FIFO_EMPTY_SIZE 1
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AW_FIFO_EMPTY_OFFSET 27
#define PSRAM_PSRAM_FE_DEBUG_FIFO_STATUS_AW_FIFO_EMPTY_SIZE 1

/** bit field defines for psram_s#psram_fe_debug_arbiter_cnt */
#define PSRAM_PSRAM_FE_DEBUG_ARBITER_CNT_AR_AW_ARB_PRIO_CNT_DEBUG_OFFSET 0
#define PSRAM_PSRAM_FE_DEBUG_ARBITER_CNT_AR_AW_ARB_PRIO_CNT_DEBUG_SIZE 3
#define PSRAM_PSRAM_FE_DEBUG_ARBITER_CNT_AR_HIGH_MEDIUM_ARB_PRIO_CNT_DEBUG_OFFSET 3
#define PSRAM_PSRAM_FE_DEBUG_ARBITER_CNT_AR_HIGH_MEDIUM_ARB_PRIO_CNT_DEBUG_SIZE 2

/** bit field defines for psram_s#psram_controller_phy_debug */
#define PSRAM_PSRAM_CONTROLLER_PHY_DEBUG_PSRAM_CTRL_PHY_FSM_STATE_OFFSET 0
#define PSRAM_PSRAM_CONTROLLER_PHY_DEBUG_PSRAM_CTRL_PHY_FSM_STATE_SIZE 5
#define PSRAM_PSRAM_CONTROLLER_PHY_DEBUG_PSRAM_CTRL_PHY_SW_CFG_FSM_STATE_OFFSET 8
#define PSRAM_PSRAM_CONTROLLER_PHY_DEBUG_PSRAM_CTRL_PHY_SW_CFG_FSM_STATE_SIZE 4
#define PSRAM_PSRAM_CONTROLLER_PHY_DEBUG_PSRAM_MODE_OFFSET 16
#define PSRAM_PSRAM_CONTROLLER_PHY_DEBUG_PSRAM_MODE_SIZE 2
#define PSRAM_PSRAM_CONTROLLER_PHY_DEBUG_PSRAM_CTRL_PHY_COMMAND_FIFO_READY_OFFSET 18
#define PSRAM_PSRAM_CONTROLLER_PHY_DEBUG_PSRAM_CTRL_PHY_COMMAND_FIFO_READY_SIZE 1
#define PSRAM_PSRAM_CONTROLLER_PHY_DEBUG_PSRAM_CTRL_PHY_COMMAND_FIFO_EMPTY_OFFSET 19
#define PSRAM_PSRAM_CONTROLLER_PHY_DEBUG_PSRAM_CTRL_PHY_COMMAND_FIFO_EMPTY_SIZE 1
#define PSRAM_PSRAM_CONTROLLER_PHY_DEBUG_PSRAM_CTRL_PHY_WDATA_FIFO_READY_OFFSET 20
#define PSRAM_PSRAM_CONTROLLER_PHY_DEBUG_PSRAM_CTRL_PHY_WDATA_FIFO_READY_SIZE 1
#define PSRAM_PSRAM_CONTROLLER_PHY_DEBUG_PSRAM_CTRL_PHY_WDATA_FIFO_EMPTY_OFFSET 21
#define PSRAM_PSRAM_CONTROLLER_PHY_DEBUG_PSRAM_CTRL_PHY_WDATA_FIFO_EMPTY_SIZE 1
#define PSRAM_PSRAM_CONTROLLER_PHY_DEBUG_PSRAM_CTRL_PHY_RDATA_FIFO_READY_OFFSET 22
#define PSRAM_PSRAM_CONTROLLER_PHY_DEBUG_PSRAM_CTRL_PHY_RDATA_FIFO_READY_SIZE 1
#define PSRAM_PSRAM_CONTROLLER_PHY_DEBUG_PSRAM_CTRL_PHY_RDATA_FIFO_EMPTY_OFFSET 23
#define PSRAM_PSRAM_CONTROLLER_PHY_DEBUG_PSRAM_CTRL_PHY_RDATA_FIFO_EMPTY_SIZE 1

/** bit field defines for psram_s#psram_controller_phy_debug_cnt */
#define PSRAM_PSRAM_CONTROLLER_PHY_DEBUG_CNT_PSRAM_ASYNC_COUNTER_OFFSET 0
#define PSRAM_PSRAM_CONTROLLER_PHY_DEBUG_CNT_PSRAM_ASYNC_COUNTER_SIZE 5
#define PSRAM_PSRAM_CONTROLLER_PHY_DEBUG_CNT_PSRAM_SYNC_BURST_COUNTER_OFFSET 8
#define PSRAM_PSRAM_CONTROLLER_PHY_DEBUG_CNT_PSRAM_SYNC_BURST_COUNTER_SIZE 7
#define PSRAM_PSRAM_CONTROLLER_PHY_DEBUG_CNT_PSRAM_SYNC_LATENCY_COUNTER_OFFSET 16
#define PSRAM_PSRAM_CONTROLLER_PHY_DEBUG_CNT_PSRAM_SYNC_LATENCY_COUNTER_SIZE 4

/** bit field defines for psram_s#psram_hwobs_control */
#define PSRAM_PSRAM_HWOBS_CONTROL_PSRAM_HWOBS_MUX_CONTROL_OFFSET 0
#define PSRAM_PSRAM_HWOBS_CONTROL_PSRAM_HWOBS_MUX_CONTROL_SIZE 2

/** bit field defines for psram_s#bcr */
#define PSRAM_BCR_BURST_LENGTH_OFFSET 0
#define PSRAM_BCR_BURST_LENGTH_SIZE 3
#define PSRAM_BCR_BURST_WRAP_OFFSET 3
#define PSRAM_BCR_BURST_WRAP_SIZE 1
#define PSRAM_BCR_DRIVE_STRENGTH_OFFSET 4
#define PSRAM_BCR_DRIVE_STRENGTH_SIZE 2
#define PSRAM_BCR_RESERVED_BCR_0_OFFSET 6
#define PSRAM_BCR_RESERVED_BCR_0_SIZE 1
#define PSRAM_BCR_SDR_DDR_MODE_WINDBOND_OFFSET 7
#define PSRAM_BCR_SDR_DDR_MODE_WINDBOND_SIZE 1
#define PSRAM_BCR_WAIT_CONFIGURATION_OFFSET 8
#define PSRAM_BCR_WAIT_CONFIGURATION_SIZE 1
#define PSRAM_BCR_SDR_DDR_MODE_AP_MEMORY_OFFSET 9
#define PSRAM_BCR_SDR_DDR_MODE_AP_MEMORY_SIZE 1
#define PSRAM_BCR_WAIT_POLARITY_OFFSET 10
#define PSRAM_BCR_WAIT_POLARITY_SIZE 1
#define PSRAM_BCR_LATENCY_COUNTER_OFFSET 11
#define PSRAM_BCR_LATENCY_COUNTER_SIZE 3
#define PSRAM_BCR_INITIAL_LATENCY_OFFSET 14
#define PSRAM_BCR_INITIAL_LATENCY_SIZE 1
#define PSRAM_BCR_OPERATING_MODE_OFFSET 15
#define PSRAM_BCR_OPERATING_MODE_SIZE 1

/** bit field defines for psram_s#rcr */
#define PSRAM_RCR_PAR_OFFSET 0
#define PSRAM_RCR_PAR_SIZE 3
#define PSRAM_RCR_RESERVED_RCR_0_OFFSET 3
#define PSRAM_RCR_RESERVED_RCR_0_SIZE 1
#define PSRAM_RCR_DEEP_POWER_DOWN_OFFSET 4
#define PSRAM_RCR_DEEP_POWER_DOWN_SIZE 1
#define PSRAM_RCR_RESERVED_RCR_SETTINGS_OFFSET 5
#define PSRAM_RCR_RESERVED_RCR_SETTINGS_SIZE 2
#define PSRAM_RCR_RESERVED_RCR_1_OFFSET 7
#define PSRAM_RCR_RESERVED_RCR_1_SIZE 9

/** bit field defines for psram_s#didr */
#define PSRAM_DIDR_VENDOR_ID_OFFSET 0
#define PSRAM_DIDR_VENDOR_ID_SIZE 5
#define PSRAM_DIDR_CELLULAR_RAM_GENERATION_OFFSET 5
#define PSRAM_DIDR_CELLULAR_RAM_GENERATION_SIZE 3
#define PSRAM_DIDR_DEVICE_DENSITY_OFFSET 8
#define PSRAM_DIDR_DEVICE_DENSITY_SIZE 3
#define PSRAM_DIDR_DEVICE_VERSION_OFFSET 11
#define PSRAM_DIDR_DEVICE_VERSION_SIZE 4
#define PSRAM_DIDR_ROW_LENGTH_OFFSET 15
#define PSRAM_DIDR_ROW_LENGTH_SIZE 1

/** bit field defines for psram_s#bcr_write_req */
#define PSRAM_BCR_WRITE_REQ_BCR_WRITE_REQ_OFFSET 0
#define PSRAM_BCR_WRITE_REQ_BCR_WRITE_REQ_SIZE 1

/** bit field defines for psram_s#bcr_read_req */
#define PSRAM_BCR_READ_REQ_BCR_READ_REQ_OFFSET 0
#define PSRAM_BCR_READ_REQ_BCR_READ_REQ_SIZE 1

/** bit field defines for psram_s#rcr_write_req */
#define PSRAM_RCR_WRITE_REQ_RCR_WRITE_REQ_OFFSET 0
#define PSRAM_RCR_WRITE_REQ_RCR_WRITE_REQ_SIZE 1

/** bit field defines for psram_s#rcr_read_req */
#define PSRAM_RCR_READ_REQ_RCR_READ_REQ_OFFSET 0
#define PSRAM_RCR_READ_REQ_RCR_READ_REQ_SIZE 1

/** bit field defines for psram_s#didr_read_req */
#define PSRAM_DIDR_READ_REQ_DIDR_READ_REQ_OFFSET 0
#define PSRAM_DIDR_READ_REQ_DIDR_READ_REQ_SIZE 1

/** bit field defines for psram_s#phy_tx_dll_configuration */
#define PSRAM_PHY_TX_DLL_CONFIGURATION_PHY_TX_DLL_CONFIG_SLAVE_CLK_DELAY_OFFSET 0
#define PSRAM_PHY_TX_DLL_CONFIGURATION_PHY_TX_DLL_CONFIG_SLAVE_CLK_DELAY_SIZE 7
#define PSRAM_PHY_TX_DLL_CONFIGURATION_PHY_TX_DLL_CONFIG_SLAVE_DQS_DELAY_OFFSET 8
#define PSRAM_PHY_TX_DLL_CONFIGURATION_PHY_TX_DLL_CONFIG_SLAVE_DQS_DELAY_SIZE 7
#define PSRAM_PHY_TX_DLL_CONFIGURATION_PHY_TX_DLL_CONFIG_TRACKING_OFFSET 27
#define PSRAM_PHY_TX_DLL_CONFIGURATION_PHY_TX_DLL_CONFIG_TRACKING_SIZE 1
#define PSRAM_PHY_TX_DLL_CONFIGURATION_PHY_TX_DLL_CONFIG_SLAVE_CLK_BYPASS_OFFSET 28
#define PSRAM_PHY_TX_DLL_CONFIGURATION_PHY_TX_DLL_CONFIG_SLAVE_CLK_BYPASS_SIZE 1
#define PSRAM_PHY_TX_DLL_CONFIGURATION_PHY_TX_DLL_CONFIG_SLAVE_DQS_BYPASS_OFFSET 29
#define PSRAM_PHY_TX_DLL_CONFIGURATION_PHY_TX_DLL_CONFIG_SLAVE_DQS_BYPASS_SIZE 1
#define PSRAM_PHY_TX_DLL_CONFIGURATION_PHY_TX_DLL_CONFIG_RESYNC_OFFSET 31
#define PSRAM_PHY_TX_DLL_CONFIGURATION_PHY_TX_DLL_CONFIG_RESYNC_SIZE 1

/** bit field defines for psram_s#phy_rx_dll_configuration */
#define PSRAM_PHY_RX_DLL_CONFIGURATION_PHY_RX_DLL_CONFIG_SLAVE_UDQS_DELAY_OFFSET 0
#define PSRAM_PHY_RX_DLL_CONFIGURATION_PHY_RX_DLL_CONFIG_SLAVE_UDQS_DELAY_SIZE 7
#define PSRAM_PHY_RX_DLL_CONFIGURATION_PHY_RX_DLL_CONFIG_SLAVE_LDQS_DELAY_OFFSET 8
#define PSRAM_PHY_RX_DLL_CONFIGURATION_PHY_RX_DLL_CONFIG_SLAVE_LDQS_DELAY_SIZE 7
#define PSRAM_PHY_RX_DLL_CONFIGURATION_PHY_RX_RESAMPLING_WITH_HOLD_OFFSET 26
#define PSRAM_PHY_RX_DLL_CONFIGURATION_PHY_RX_RESAMPLING_WITH_HOLD_SIZE 1
#define PSRAM_PHY_RX_DLL_CONFIGURATION_PHY_RX_DLL_CONFIG_TRACKING_OFFSET 27
#define PSRAM_PHY_RX_DLL_CONFIGURATION_PHY_RX_DLL_CONFIG_TRACKING_SIZE 1
#define PSRAM_PHY_RX_DLL_CONFIGURATION_PHY_RX_DLL_CONFIG_SLAVE_LDQS_BYPASS_OFFSET 28
#define PSRAM_PHY_RX_DLL_CONFIGURATION_PHY_RX_DLL_CONFIG_SLAVE_LDQS_BYPASS_SIZE 1
#define PSRAM_PHY_RX_DLL_CONFIGURATION_PHY_RX_DLL_CONFIG_SLAVE_ULDQS_BYPASS_OFFSET 29
#define PSRAM_PHY_RX_DLL_CONFIGURATION_PHY_RX_DLL_CONFIG_SLAVE_ULDQS_BYPASS_SIZE 1
#define PSRAM_PHY_RX_DLL_CONFIGURATION_PHY_RX_DLL_CONFIG_RESYNC_OFFSET 31
#define PSRAM_PHY_RX_DLL_CONFIGURATION_PHY_RX_DLL_CONFIG_RESYNC_SIZE 1

/** bit field defines for psram_s#phy_dll_master_control */
#define PSRAM_PHY_DLL_MASTER_CONTROL_PHY_DLL_MASTER_INITIAL_DELAY_OFFSET 0
#define PSRAM_PHY_DLL_MASTER_CONTROL_PHY_DLL_MASTER_INITIAL_DELAY_SIZE 7
#define PSRAM_PHY_DLL_MASTER_CONTROL_PHY_DLL_MASTER_NB_INDICATIONS_OFFSET 16
#define PSRAM_PHY_DLL_MASTER_CONTROL_PHY_DLL_MASTER_NB_INDICATIONS_SIZE 3
#define PSRAM_PHY_DLL_MASTER_CONTROL_PHY_DLL_MASTER_PHASE_DETECT_SELECTOR_OFFSET 20
#define PSRAM_PHY_DLL_MASTER_CONTROL_PHY_DLL_MASTER_PHASE_DETECT_SELECTOR_SIZE 3
#define PSRAM_PHY_DLL_MASTER_CONTROL_PHY_DLL_MASTER_BYPASS_MODE_OFFSET 23
#define PSRAM_PHY_DLL_MASTER_CONTROL_PHY_DLL_MASTER_BYPASS_MODE_SIZE 1
#define PSRAM_PHY_DLL_MASTER_CONTROL_PHY_DLL_MASTER_LOCK_MODE_OFFSET 24
#define PSRAM_PHY_DLL_MASTER_CONTROL_PHY_DLL_MASTER_LOCK_MODE_SIZE 1
#define PSRAM_PHY_DLL_MASTER_CONTROL_PHY_DLL_MASTER_TRACKING_HOLDOFF_OFFSET 25
#define PSRAM_PHY_DLL_MASTER_CONTROL_PHY_DLL_MASTER_TRACKING_HOLDOFF_SIZE 1
#define PSRAM_PHY_DLL_MASTER_CONTROL_PHY_DLL_MASTER_RESET_OFFSET 26
#define PSRAM_PHY_DLL_MASTER_CONTROL_PHY_DLL_MASTER_RESET_SIZE 1
#define PSRAM_PHY_DLL_MASTER_CONTROL_PHY_DLL_MASTER_RESYNC_OFFSET 31
#define PSRAM_PHY_DLL_MASTER_CONTROL_PHY_DLL_MASTER_RESYNC_SIZE 1

/** bit field defines for psram_s#phy_tx_dll_obs_reg_slave */
#define PSRAM_PHY_TX_DLL_OBS_REG_SLAVE_PHY_TX_DLL_OBSERVABLE_TX_CLK_DECODER_OUTPUT_OFFSET 0
#define PSRAM_PHY_TX_DLL_OBS_REG_SLAVE_PHY_TX_DLL_OBSERVABLE_TX_CLK_DECODER_OUTPUT_SIZE 7
#define PSRAM_PHY_TX_DLL_OBS_REG_SLAVE_PHY_TX_DLL_OBSERVABLE_DQS_DECODER_OUTPUT_OFFSET 8
#define PSRAM_PHY_TX_DLL_OBS_REG_SLAVE_PHY_TX_DLL_OBSERVABLE_DQS_DECODER_OUTPUT_SIZE 7
#define PSRAM_PHY_TX_DLL_OBS_REG_SLAVE_PHY_TX_DLL_OBSERVABLE_TX_CLK_ADD_HALF_CLOCK_OFFSET 24
#define PSRAM_PHY_TX_DLL_OBS_REG_SLAVE_PHY_TX_DLL_OBSERVABLE_TX_CLK_ADD_HALF_CLOCK_SIZE 1
#define PSRAM_PHY_TX_DLL_OBS_REG_SLAVE_PHY_TX_DLL_OBSERVABLE_DQS_ADD_HALF_CLOCK_OFFSET 25
#define PSRAM_PHY_TX_DLL_OBS_REG_SLAVE_PHY_TX_DLL_OBSERVABLE_DQS_ADD_HALF_CLOCK_SIZE 1

/** bit field defines for psram_s#phy_dll_obs_reg_master */
#define PSRAM_PHY_DLL_OBS_REG_MASTER_PHY_DLL_OBSERVABLE_DLL_LOCK_OFFSET 0
#define PSRAM_PHY_DLL_OBS_REG_MASTER_PHY_DLL_OBSERVABLE_DLL_LOCK_SIZE 1
#define PSRAM_PHY_DLL_OBS_REG_MASTER_PHY_DLL_OBSERVABLE_LOCK_MODE_OFFSET 1
#define PSRAM_PHY_DLL_OBS_REG_MASTER_PHY_DLL_OBSERVABLE_LOCK_MODE_SIZE 2
#define PSRAM_PHY_DLL_OBS_REG_MASTER_PHY_DLL_OBSERVABLE_UNLOCK_COUNTER_OFFSET 3
#define PSRAM_PHY_DLL_OBS_REG_MASTER_PHY_DLL_OBSERVABLE_UNLOCK_COUNTER_SIZE 5
#define PSRAM_PHY_DLL_OBS_REG_MASTER_PHY_DLL_OBSERVABLE_LOCK_VALUE_OFFSET 8
#define PSRAM_PHY_DLL_OBS_REG_MASTER_PHY_DLL_OBSERVABLE_LOCK_VALUE_SIZE 7
#define PSRAM_PHY_DLL_OBS_REG_MASTER_PHY_DLL_OBSERVABLE_LOOPBACK_LOCK_OFFSET 15
#define PSRAM_PHY_DLL_OBS_REG_MASTER_PHY_DLL_OBSERVABLE_LOOPBACK_LOCK_SIZE 1
#define PSRAM_PHY_DLL_OBS_REG_MASTER_PHY_DLL_OBSERVABLE_DLL_LOCK_DEC_OFFSET 16
#define PSRAM_PHY_DLL_OBS_REG_MASTER_PHY_DLL_OBSERVABLE_DLL_LOCK_DEC_SIZE 8
#define PSRAM_PHY_DLL_OBS_REG_MASTER_PHY_DLL_OBSERVABLE_DLL_LOCK_INC_OFFSET 24
#define PSRAM_PHY_DLL_OBS_REG_MASTER_PHY_DLL_OBSERVABLE_DLL_LOCK_INC_SIZE 8

/** bit field defines for psram_s#phy_rx_dll_obs_reg_slave */
#define PSRAM_PHY_RX_DLL_OBS_REG_SLAVE_PHY_RX_DLL_OBSERVABLE_LDQS_DECODER_OUTPUT_OFFSET 0
#define PSRAM_PHY_RX_DLL_OBS_REG_SLAVE_PHY_RX_DLL_OBSERVABLE_LDQS_DECODER_OUTPUT_SIZE 7
#define PSRAM_PHY_RX_DLL_OBS_REG_SLAVE_PHY_RX_DLL_OBSERVABLE_UDQS_DECODER_OUTPUT_OFFSET 8
#define PSRAM_PHY_RX_DLL_OBS_REG_SLAVE_PHY_RX_DLL_OBSERVABLE_UDQS_DECODER_OUTPUT_SIZE 7
#define PSRAM_PHY_RX_DLL_OBS_REG_SLAVE_PHY_RX_DLL_OBSERVABLE_LDQS_ADD_HALF_CLOCK_OFFSET 24
#define PSRAM_PHY_RX_DLL_OBS_REG_SLAVE_PHY_RX_DLL_OBSERVABLE_LDQS_ADD_HALF_CLOCK_SIZE 1
#define PSRAM_PHY_RX_DLL_OBS_REG_SLAVE_PHY_RX_DLL_OBSERVABLE_UDQS_ADD_HALF_CLOCK_OFFSET 25
#define PSRAM_PHY_RX_DLL_OBS_REG_SLAVE_PHY_RX_DLL_OBSERVABLE_UDQS_ADD_HALF_CLOCK_SIZE 1

/** bit field defines for psram_s#phy_read_data_capture */
#define PSRAM_PHY_READ_DATA_CAPTURE_PHY_READ_DATA_CLK_DQS_OFFSET 0
#define PSRAM_PHY_READ_DATA_CAPTURE_PHY_READ_DATA_CLK_DQS_SIZE 1
#define PSRAM_PHY_READ_DATA_CAPTURE_PHY_READ_DATA_MEM_CLK_RETURN_OFFSET 1
#define PSRAM_PHY_READ_DATA_CAPTURE_PHY_READ_DATA_MEM_CLK_RETURN_SIZE 1
#define PSRAM_PHY_READ_DATA_CAPTURE_PHY_READ_DATA_MEM_CLK_INVERT_OFFSET 2
#define PSRAM_PHY_READ_DATA_CAPTURE_PHY_READ_DATA_MEM_CLK_INVERT_SIZE 1

/** bit field defines for psram_s#async_mode_latency */
#define PSRAM_ASYNC_MODE_LATENCY_ASYNC_MODE_WRITE_LATENCY_OFFSET 0
#define PSRAM_ASYNC_MODE_LATENCY_ASYNC_MODE_WRITE_LATENCY_SIZE 5
#define PSRAM_ASYNC_MODE_LATENCY_ASYNC_MODE_READ_LATENCY_OFFSET 8
#define PSRAM_ASYNC_MODE_LATENCY_ASYNC_MODE_READ_LATENCY_SIZE 5

/** bit field defines for psram_s#dpd_exit_counter */
#define PSRAM_DPD_EXIT_COUNTER_DPD_EXIT_COUNTER_OFFSET 0
#define PSRAM_DPD_EXIT_COUNTER_DPD_EXIT_COUNTER_SIZE 16

/** bit field defines for psram_s#dpd_exit */
#define PSRAM_DPD_EXIT_DPD_EXIT_REQ_OFFSET 0
#define PSRAM_DPD_EXIT_DPD_EXIT_REQ_SIZE 1
#define PSRAM_DPD_EXIT_DPD_EXIT_ACK_OFFSET 1
#define PSRAM_DPD_EXIT_DPD_EXIT_ACK_SIZE 1

/** bit field defines for psram_s#psram_controller_phy_status */
#define PSRAM_PSRAM_CONTROLLER_PHY_STATUS_PSRAM_CONTROLLER_PHY_BUSY_OFFSET 0
#define PSRAM_PSRAM_CONTROLLER_PHY_STATUS_PSRAM_CONTROLLER_PHY_BUSY_SIZE 1

/** bit field defines for psram_s#psram_controller_phy_ignore */
#define PSRAM_PSRAM_CONTROLLER_PHY_IGNORE_PSRAM_CONTROLLER_PHY_IGNORE_COMMAND_OFFSET 0
#define PSRAM_PSRAM_CONTROLLER_PHY_IGNORE_PSRAM_CONTROLLER_PHY_IGNORE_COMMAND_SIZE 1

/** bit field defines for psram_s#psram_controller_phy_cfg */
#define PSRAM_PSRAM_CONTROLLER_PHY_CFG_PSRAM_CONTROLLER_PHY_DDR_MAX_SPEED_OFFSET 0
#define PSRAM_PSRAM_CONTROLLER_PHY_CFG_PSRAM_CONTROLLER_PHY_DDR_MAX_SPEED_SIZE 1
#define PSRAM_PSRAM_CONTROLLER_PHY_CFG_PSRAM_CONTROLLER_PHY_TX_CG_DISABLE_OFFSET 1
#define PSRAM_PSRAM_CONTROLLER_PHY_CFG_PSRAM_CONTROLLER_PHY_TX_CG_DISABLE_SIZE 1
#define PSRAM_PSRAM_CONTROLLER_PHY_CFG_PSRAM_CONTROLLER_PHY_RX_CG_DISABLE_OFFSET 2
#define PSRAM_PSRAM_CONTROLLER_PHY_CFG_PSRAM_CONTROLLER_PHY_RX_CG_DISABLE_SIZE 1
#define PSRAM_PSRAM_CONTROLLER_PHY_CFG_PSRAM_CONTROLLER_PHY_DQS_SWITCH_ENABLE_OFFSET 3
#define PSRAM_PSRAM_CONTROLLER_PHY_CFG_PSRAM_CONTROLLER_PHY_DQS_SWITCH_ENABLE_SIZE 1
#define PSRAM_PSRAM_CONTROLLER_PHY_CFG_PSRAM_CONTROLLER_PHY_BCR_DDR_INDEX_OFFSET 4
#define PSRAM_PSRAM_CONTROLLER_PHY_CFG_PSRAM_CONTROLLER_PHY_BCR_DDR_INDEX_SIZE 4
#define PSRAM_PSRAM_CONTROLLER_PHY_CFG_PSRAM_CONTROLLER_PHY_RX_WAIT_FEEDBACK_OFFSET 8
#define PSRAM_PSRAM_CONTROLLER_PHY_CFG_PSRAM_CONTROLLER_PHY_RX_WAIT_FEEDBACK_SIZE 1
#define PSRAM_PSRAM_CONTROLLER_PHY_CFG_PSRAM_CONTROLLER_PHY_RX_TIMEOUT_OFFSET 9
#define PSRAM_PSRAM_CONTROLLER_PHY_CFG_PSRAM_CONTROLLER_PHY_RX_TIMEOUT_SIZE 5
#define PSRAM_PSRAM_CONTROLLER_PHY_CFG_PSRAM_CONTROLLER_PHY_RX_TIMEOUT_ENABLE_OFFSET 14
#define PSRAM_PSRAM_CONTROLLER_PHY_CFG_PSRAM_CONTROLLER_PHY_RX_TIMEOUT_ENABLE_SIZE 1

/** bit field defines for psram_s#sync_mode_latency */
#define PSRAM_SYNC_MODE_LATENCY_SYNC_MODE_WRITE_LATENCY_OFFSET 0
#define PSRAM_SYNC_MODE_LATENCY_SYNC_MODE_WRITE_LATENCY_SIZE 4
#define PSRAM_SYNC_MODE_LATENCY_SYNC_MODE_READ_LATENCY_OFFSET 4
#define PSRAM_SYNC_MODE_LATENCY_SYNC_MODE_READ_LATENCY_SIZE 4
#define PSRAM_SYNC_MODE_LATENCY_INITIAL_LATENCY_WAIT_TYPE_OFFSET 31
#define PSRAM_SYNC_MODE_LATENCY_INITIAL_LATENCY_WAIT_TYPE_SIZE 1

/** bit field defines for psram_s#dft_loopback_control_lb */
#define PSRAM_DFT_LOOPBACK_CONTROL_LB_LOOPBACK_CONTROL_LB_OFFSET 0
#define PSRAM_DFT_LOOPBACK_CONTROL_LB_LOOPBACK_CONTROL_LB_SIZE 2
#define PSRAM_DFT_LOOPBACK_CONTROL_LB_LOOPBACK_INTERNAL_LB_OFFSET 2
#define PSRAM_DFT_LOOPBACK_CONTROL_LB_LOOPBACK_INTERNAL_LB_SIZE 1
#define PSRAM_DFT_LOOPBACK_CONTROL_LB_LOOPBACK_ENABLE_LB_OFFSET 3
#define PSRAM_DFT_LOOPBACK_CONTROL_LB_LOOPBACK_ENABLE_LB_SIZE 1
#define PSRAM_DFT_LOOPBACK_CONTROL_LB_LOOPBACK_DATA_FAIL_MUX_SEL_LB_OFFSET 4
#define PSRAM_DFT_LOOPBACK_CONTROL_LB_LOOPBACK_DATA_FAIL_MUX_SEL_LB_SIZE 1
#define PSRAM_DFT_LOOPBACK_CONTROL_LB_LOOPBACK_CHECK_TIMING_UB_OFFSET 5
#define PSRAM_DFT_LOOPBACK_CONTROL_LB_LOOPBACK_CHECK_TIMING_UB_SIZE 3

/** bit field defines for psram_s#dft_loopback_control_ub */
#define PSRAM_DFT_LOOPBACK_CONTROL_UB_LOOPBACK_CONTROL_UB_OFFSET 0
#define PSRAM_DFT_LOOPBACK_CONTROL_UB_LOOPBACK_CONTROL_UB_SIZE 2
#define PSRAM_DFT_LOOPBACK_CONTROL_UB_LOOPBACK_INTERNAL_UB_OFFSET 2
#define PSRAM_DFT_LOOPBACK_CONTROL_UB_LOOPBACK_INTERNAL_UB_SIZE 1
#define PSRAM_DFT_LOOPBACK_CONTROL_UB_LOOPBACK_ENABLE_UB_OFFSET 3
#define PSRAM_DFT_LOOPBACK_CONTROL_UB_LOOPBACK_ENABLE_UB_SIZE 1
#define PSRAM_DFT_LOOPBACK_CONTROL_UB_LOOPBACK_DATA_FAIL_MUX_SEL_UB_OFFSET 4
#define PSRAM_DFT_LOOPBACK_CONTROL_UB_LOOPBACK_DATA_FAIL_MUX_SEL_UB_SIZE 1
#define PSRAM_DFT_LOOPBACK_CONTROL_UB_LOOPBACK_CHECK_TIMING_UB_OFFSET 5
#define PSRAM_DFT_LOOPBACK_CONTROL_UB_LOOPBACK_CHECK_TIMING_UB_SIZE 3

/** bit field defines for psram_s#dft_loopback_obs_reg */
#define PSRAM_DFT_LOOPBACK_OBS_REG_DFT_LOOPBACK_DATA_OFFSET 0
#define PSRAM_DFT_LOOPBACK_OBS_REG_DFT_LOOPBACK_DATA_SIZE 16
#define PSRAM_DFT_LOOPBACK_OBS_REG_DFT_LOOPBACK_START_OFFSET 16
#define PSRAM_DFT_LOOPBACK_OBS_REG_DFT_LOOPBACK_START_SIZE 1
#define PSRAM_DFT_LOOPBACK_OBS_REG_DFT_LOOPBACK_ERROR_OFFSET 17
#define PSRAM_DFT_LOOPBACK_OBS_REG_DFT_LOOPBACK_ERROR_SIZE 1

/** bit field defines for psram_s#dft_mem_ctrl */
#define PSRAM_DFT_MEM_CTRL_PSRAM_MEM_REQ_OFFSET 0
#define PSRAM_DFT_MEM_CTRL_PSRAM_MEM_REQ_SIZE 1
#define PSRAM_DFT_MEM_CTRL_PSRAM_MEM_ACK_OFFSET 1
#define PSRAM_DFT_MEM_CTRL_PSRAM_MEM_ACK_SIZE 1

/** bit field defines for psram_s#dft_mem_command */
#define PSRAM_DFT_MEM_COMMAND_PSRAM_MEM_ADDRESS_OFFSET 0
#define PSRAM_DFT_MEM_COMMAND_PSRAM_MEM_ADDRESS_SIZE 28
#define PSRAM_DFT_MEM_COMMAND_PSRAM_MEM_WRITE_OFFSET 28
#define PSRAM_DFT_MEM_COMMAND_PSRAM_MEM_WRITE_SIZE 1
#define PSRAM_DFT_MEM_COMMAND_PSRAM_MEM_AXI_ACCESS_OFFSET 29
#define PSRAM_DFT_MEM_COMMAND_PSRAM_MEM_AXI_ACCESS_SIZE 1
#define PSRAM_DFT_MEM_COMMAND_PSRAM_MEM_IGNORE_OFFSET 30
#define PSRAM_DFT_MEM_COMMAND_PSRAM_MEM_IGNORE_SIZE 1
#define PSRAM_DFT_MEM_COMMAND_PSRAM_MEM_TEST_FUNCTIONAL_OFFSET 31
#define PSRAM_DFT_MEM_COMMAND_PSRAM_MEM_TEST_FUNCTIONAL_SIZE 1

/** bit field defines for psram_s#dft_mem_write_data_pos */
#define PSRAM_DFT_MEM_WRITE_DATA_POS_PSRAM_MEM_WRITE_DATA_POS_OFFSET 0
#define PSRAM_DFT_MEM_WRITE_DATA_POS_PSRAM_MEM_WRITE_DATA_POS_SIZE 16
#define PSRAM_DFT_MEM_WRITE_DATA_POS_PSRAM_MEM_LB_POS_OFFSET 16
#define PSRAM_DFT_MEM_WRITE_DATA_POS_PSRAM_MEM_LB_POS_SIZE 1
#define PSRAM_DFT_MEM_WRITE_DATA_POS_PSRAM_MEM_UB_POS_OFFSET 17
#define PSRAM_DFT_MEM_WRITE_DATA_POS_PSRAM_MEM_UB_POS_SIZE 1

/** bit field defines for psram_s#dft_mem_write_data_neg */
#define PSRAM_DFT_MEM_WRITE_DATA_NEG_PSRAM_MEM_WRITE_DATA_NEG_OFFSET 0
#define PSRAM_DFT_MEM_WRITE_DATA_NEG_PSRAM_MEM_WRITE_DATA_NEG_SIZE 16
#define PSRAM_DFT_MEM_WRITE_DATA_NEG_PSRAM_MEM_LB_NEG_OFFSET 16
#define PSRAM_DFT_MEM_WRITE_DATA_NEG_PSRAM_MEM_LB_NEG_SIZE 1
#define PSRAM_DFT_MEM_WRITE_DATA_NEG_PSRAM_MEM_UB_NEG_OFFSET 17
#define PSRAM_DFT_MEM_WRITE_DATA_NEG_PSRAM_MEM_UB_NEG_SIZE 1

/** bit field defines for psram_s#dft_mem_read_data_pos */
#define PSRAM_DFT_MEM_READ_DATA_POS_PSRAM_MEM_READ_DATA_POS_OFFSET 0
#define PSRAM_DFT_MEM_READ_DATA_POS_PSRAM_MEM_READ_DATA_POS_SIZE 16
#define PSRAM_DFT_MEM_READ_DATA_POS_PSRAM_MEM_FAIL_POS_OFFSET 16
#define PSRAM_DFT_MEM_READ_DATA_POS_PSRAM_MEM_FAIL_POS_SIZE 1

/** bit field defines for psram_s#dft_mem_read_data_neg */
#define PSRAM_DFT_MEM_READ_DATA_NEG_PSRAM_MEM_READ_DATA_NEG_OFFSET 0
#define PSRAM_DFT_MEM_READ_DATA_NEG_PSRAM_MEM_READ_DATA_NEG_SIZE 16
#define PSRAM_DFT_MEM_READ_DATA_NEG_PSRAM_MEM_FAIL_NEG_OFFSET 16
#define PSRAM_DFT_MEM_READ_DATA_NEG_PSRAM_MEM_FAIL_NEG_SIZE 1

/** bit field defines for psram_s#dft_mem_read_data_cfg_regs */
#define PSRAM_DFT_MEM_READ_DATA_CFG_REGS_PSRAM_MEM_READ_DATA_CFG_REGS_OFFSET 0
#define PSRAM_DFT_MEM_READ_DATA_CFG_REGS_PSRAM_MEM_READ_DATA_CFG_REGS_SIZE 16

/* EOF psram.h */
#endif
