#ifndef INCLUDED_RX_APB_MMAP_RXBB
#define INCLUDED_RX_APB_MMAP_RXBB
/*
 * Copyright (C) u-blox 
 * All rights reserved. 
 * This source file is the sole property of u-blox. Reproduction or utilization 
 * of this source in whole or part is forbidden without the written consent of 
 * u-blox.
 *
 */

#include <stdint.h>

/** rx_apb_mmap_rxbb HAL Spreadsheet version number */
#define RX_APB_MMAP_RXBB_HAL_VERSION 102

/** This is the digital receiver path control register description
*/
struct rx_apb_mmap_rxbb_s {
   /** Control bits for main analog supply at address offset 0x000, read-write */
   uint32_t ana_ldo;
   /** Control bits for iqmux analog supply at address offset 0x004, read-write */
   uint32_t iqmux_ldo;
   /** Control bits for adc analog supply at address offset 0x008, read-write */
   uint32_t adc_ldo;
   /** Enable bits for RxBB at address offset 0x00C, read-write */
   uint32_t enables;
   /** Control bits for bandgap reference at address offset 0x010, read-write */
   uint32_t bandgap;
   /** Control bits for IQmux reference current at address offset 0x014, read-write */
   uint32_t iref_iqmux;
   /** Control bits for filter reference current at address offset 0x018, read-write */
   uint32_t iref_tra;
   /** Flags for the voltage detector on the RxBB input at address offset 0x01C, read-only */
   uint32_t vdetect;
   /** Control bits for I Channel Voltage Detector at address offset 0x020, read-write */
   uint32_t vdetect_i;
   /** Control bits for Q Channel Voltage Detector at address offset 0x024, read-write */
   uint32_t vdetect_q;
   /** Control bits for the DCOC at address offset 0x028, read-write */
   uint32_t dcoc;
   /** Control bits 1 for low pass transimpedance filter at address offset 0x02C, read-write */
   uint32_t tra_1;
   /** Control bits 2 for low pass transimpedance filter at address offset 0x030, read-write */
   uint32_t tra_2;
   /** Control bits for IQmux at address offset 0x034, read-write */
   uint32_t iqmux;
   /** Enables for IQmux at address offset 0x038, read-write */
   uint32_t iqmux_en;
   /** Master enables for Rx anatest at address offset 0x03C, read-write */
   uint32_t atst_rx;
   /** Sublevel enables for RxBB anatest at address offset 0x040, read-write */
   uint32_t atst;
   /** Toplevel enables for RxBB anatest at address offset 0x044, read-write */
   uint32_t atst_toplevel_rxbb;
   /** Toplevel enables for RxRF (LNA and Mixer) anatest at address offset 0x048, read-write */
   uint32_t atst_toplevel_rxrf1;
   /** toplevel enables for tca and ldo anatest at address offset 0x04C, read-write */
   uint32_t atst_toplevel_rxrf2;
   /** Spare Bits at address offset 0x050, read-write */
   uint32_t rxbb_spare;
   /** Control bits for Clock MUX at address offset 0x054, read-write */
   uint32_t adc_clkmux;
   /** Control bits to select RX clocks for TX at address offset 0x058, read-write */
   uint32_t rxtx_clkmux;
   /** Debug register for testing the loading of data from the shadow to config registers. at address offset 0x05C, read-write */
   uint32_t dbg_rxbb;
};

/** bit field defines for rx_apb_mmap_rxbb_s#ana_ldo */
#define RX_APB_MMAP_RXBB_ANA_LDO_BYPASS_OFFSET 0
#define RX_APB_MMAP_RXBB_ANA_LDO_BYPASS_SIZE 1
#define RX_APB_MMAP_RXBB_ANA_LDO_ENABLE_OFFSET 1
#define RX_APB_MMAP_RXBB_ANA_LDO_ENABLE_SIZE 1
#define RX_APB_MMAP_RXBB_ANA_LDO_FAST_LOCK_OFFSET 2
#define RX_APB_MMAP_RXBB_ANA_LDO_FAST_LOCK_SIZE 1
#define RX_APB_MMAP_RXBB_ANA_LDO_VOUT_CTRL_OFFSET 3
#define RX_APB_MMAP_RXBB_ANA_LDO_VOUT_CTRL_SIZE 4

/** bit field defines for rx_apb_mmap_rxbb_s#iqmux_ldo */
#define RX_APB_MMAP_RXBB_IQMUX_LDO_BYPASS_OFFSET 0
#define RX_APB_MMAP_RXBB_IQMUX_LDO_BYPASS_SIZE 1
#define RX_APB_MMAP_RXBB_IQMUX_LDO_ENABLE_OFFSET 1
#define RX_APB_MMAP_RXBB_IQMUX_LDO_ENABLE_SIZE 1
#define RX_APB_MMAP_RXBB_IQMUX_LDO_FAST_LOCK_OFFSET 2
#define RX_APB_MMAP_RXBB_IQMUX_LDO_FAST_LOCK_SIZE 1
#define RX_APB_MMAP_RXBB_IQMUX_LDO_VOUT_CTRL_OFFSET 3
#define RX_APB_MMAP_RXBB_IQMUX_LDO_VOUT_CTRL_SIZE 4

/** bit field defines for rx_apb_mmap_rxbb_s#adc_ldo */
#define RX_APB_MMAP_RXBB_ADC_LDO_BYPASS_OFFSET 0
#define RX_APB_MMAP_RXBB_ADC_LDO_BYPASS_SIZE 1
#define RX_APB_MMAP_RXBB_ADC_LDO_ENABLE_OFFSET 1
#define RX_APB_MMAP_RXBB_ADC_LDO_ENABLE_SIZE 1
#define RX_APB_MMAP_RXBB_ADC_LDO_FAST_LOCK_OFFSET 2
#define RX_APB_MMAP_RXBB_ADC_LDO_FAST_LOCK_SIZE 1
#define RX_APB_MMAP_RXBB_ADC_LDO_VOUT_CTRL_OFFSET 3
#define RX_APB_MMAP_RXBB_ADC_LDO_VOUT_CTRL_SIZE 4

/** bit field defines for rx_apb_mmap_rxbb_s#enables */
#define RX_APB_MMAP_RXBB_ENABLES_ADC_I_EN_OFFSET 0
#define RX_APB_MMAP_RXBB_ENABLES_ADC_I_EN_SIZE 1
#define RX_APB_MMAP_RXBB_ENABLES_ADC_Q_EN_OFFSET 1
#define RX_APB_MMAP_RXBB_ENABLES_ADC_Q_EN_SIZE 1
#define RX_APB_MMAP_RXBB_ENABLES_DCOC_I_EN_OFFSET 2
#define RX_APB_MMAP_RXBB_ENABLES_DCOC_I_EN_SIZE 1
#define RX_APB_MMAP_RXBB_ENABLES_DCOC_Q_EN_OFFSET 3
#define RX_APB_MMAP_RXBB_ENABLES_DCOC_Q_EN_SIZE 1
#define RX_APB_MMAP_RXBB_ENABLES_IQMUX_I_EN_OFFSET 4
#define RX_APB_MMAP_RXBB_ENABLES_IQMUX_I_EN_SIZE 1
#define RX_APB_MMAP_RXBB_ENABLES_IQMUX_Q_EN_OFFSET 5
#define RX_APB_MMAP_RXBB_ENABLES_IQMUX_Q_EN_SIZE 1
#define RX_APB_MMAP_RXBB_ENABLES_TRA_EN_OFFSET 6
#define RX_APB_MMAP_RXBB_ENABLES_TRA_EN_SIZE 1
#define RX_APB_MMAP_RXBB_ENABLES_IREF_IQMUX_EN_OFFSET 7
#define RX_APB_MMAP_RXBB_ENABLES_IREF_IQMUX_EN_SIZE 1
#define RX_APB_MMAP_RXBB_ENABLES_IREF_TRA_EN_OFFSET 8
#define RX_APB_MMAP_RXBB_ENABLES_IREF_TRA_EN_SIZE 1
#define RX_APB_MMAP_RXBB_ENABLES_BANDGAP_EN_OFFSET 9
#define RX_APB_MMAP_RXBB_ENABLES_BANDGAP_EN_SIZE 1
#define RX_APB_MMAP_RXBB_ENABLES_BANDGAP_BUF_EN_OFFSET 10
#define RX_APB_MMAP_RXBB_ENABLES_BANDGAP_BUF_EN_SIZE 1
#define RX_APB_MMAP_RXBB_ENABLES_VDETECT_EN_OFFSET 11
#define RX_APB_MMAP_RXBB_ENABLES_VDETECT_EN_SIZE 1

/** bit field defines for rx_apb_mmap_rxbb_s#bandgap */
#define RX_APB_MMAP_RXBB_BANDGAP_VOUT_CTRL_OFFSET 0
#define RX_APB_MMAP_RXBB_BANDGAP_VOUT_CTRL_SIZE 4
#define RX_APB_MMAP_RXBB_BANDGAP_INPUT_SEL_OFFSET 4
#define RX_APB_MMAP_RXBB_BANDGAP_INPUT_SEL_SIZE 1
/**  */
#define RX_APB_MMAP_RXBB_BANDGAP_INPUT_SEL_BANDGAP_VALUE 0
/**  */
#define RX_APB_MMAP_RXBB_BANDGAP_INPUT_SEL_V_DIV_VALUE 1

/** bit field defines for rx_apb_mmap_rxbb_s#iref_iqmux */
#define RX_APB_MMAP_RXBB_IREF_IQMUX_ITRIM_OFFSET 0
#define RX_APB_MMAP_RXBB_IREF_IQMUX_ITRIM_SIZE 2
/**  */
#define RX_APB_MMAP_RXBB_IREF_IQMUX_ITRIM_MAX_VALUE 0
/**  */
#define RX_APB_MMAP_RXBB_IREF_IQMUX_ITRIM_MIN_VALUE 3
/**  */
#define RX_APB_MMAP_RXBB_IREF_IQMUX_ITRIM_NOM_VALUE 1
#define RX_APB_MMAP_RXBB_IREF_IQMUX_ITRIM_2X_OFFSET 2
#define RX_APB_MMAP_RXBB_IREF_IQMUX_ITRIM_2X_SIZE 1

/** bit field defines for rx_apb_mmap_rxbb_s#iref_tra */
#define RX_APB_MMAP_RXBB_IREF_TRA_ITRIM_OFFSET 0
#define RX_APB_MMAP_RXBB_IREF_TRA_ITRIM_SIZE 2
/**  */
#define RX_APB_MMAP_RXBB_IREF_TRA_ITRIM_MAX_VALUE 0
/**  */
#define RX_APB_MMAP_RXBB_IREF_TRA_ITRIM_MIN_VALUE 3
/**  */
#define RX_APB_MMAP_RXBB_IREF_TRA_ITRIM_NOM_VALUE 1
#define RX_APB_MMAP_RXBB_IREF_TRA_ITRIM_2X_OFFSET 2
#define RX_APB_MMAP_RXBB_IREF_TRA_ITRIM_2X_SIZE 1

/** bit field defines for rx_apb_mmap_rxbb_s#vdetect */
#define RX_APB_MMAP_RXBB_VDETECT_I_MAXFLAGP_OFFSET 0
#define RX_APB_MMAP_RXBB_VDETECT_I_MAXFLAGP_SIZE 1
#define RX_APB_MMAP_RXBB_VDETECT_I_MAXFLAGN_OFFSET 1
#define RX_APB_MMAP_RXBB_VDETECT_I_MAXFLAGN_SIZE 1
#define RX_APB_MMAP_RXBB_VDETECT_I_MINFLAGP_OFFSET 2
#define RX_APB_MMAP_RXBB_VDETECT_I_MINFLAGP_SIZE 1
#define RX_APB_MMAP_RXBB_VDETECT_I_MINFLAGN_OFFSET 3
#define RX_APB_MMAP_RXBB_VDETECT_I_MINFLAGN_SIZE 1
#define RX_APB_MMAP_RXBB_VDETECT_Q_MAXFLAGP_OFFSET 4
#define RX_APB_MMAP_RXBB_VDETECT_Q_MAXFLAGP_SIZE 1
#define RX_APB_MMAP_RXBB_VDETECT_Q_MAXFLAGN_OFFSET 5
#define RX_APB_MMAP_RXBB_VDETECT_Q_MAXFLAGN_SIZE 1
#define RX_APB_MMAP_RXBB_VDETECT_Q_MINFLAGP_OFFSET 6
#define RX_APB_MMAP_RXBB_VDETECT_Q_MINFLAGP_SIZE 1
#define RX_APB_MMAP_RXBB_VDETECT_Q_MINFLAGN_OFFSET 7
#define RX_APB_MMAP_RXBB_VDETECT_Q_MINFLAGN_SIZE 1

/** bit field defines for rx_apb_mmap_rxbb_s#vdetect_i */
#define RX_APB_MMAP_RXBB_VDETECT_I_MAX_RESET_OFFSET 0
#define RX_APB_MMAP_RXBB_VDETECT_I_MAX_RESET_SIZE 1
#define RX_APB_MMAP_RXBB_VDETECT_I_MIN_RESET_OFFSET 1
#define RX_APB_MMAP_RXBB_VDETECT_I_MIN_RESET_SIZE 1
#define RX_APB_MMAP_RXBB_VDETECT_I_VMAX_CTRL_OFFSET 2
#define RX_APB_MMAP_RXBB_VDETECT_I_VMAX_CTRL_SIZE 3
#define RX_APB_MMAP_RXBB_VDETECT_I_VMIN_CTRL_OFFSET 5
#define RX_APB_MMAP_RXBB_VDETECT_I_VMIN_CTRL_SIZE 3

/** bit field defines for rx_apb_mmap_rxbb_s#vdetect_q */
#define RX_APB_MMAP_RXBB_VDETECT_Q_MAX_RESET_OFFSET 0
#define RX_APB_MMAP_RXBB_VDETECT_Q_MAX_RESET_SIZE 1
#define RX_APB_MMAP_RXBB_VDETECT_Q_MIN_RESET_OFFSET 1
#define RX_APB_MMAP_RXBB_VDETECT_Q_MIN_RESET_SIZE 1
#define RX_APB_MMAP_RXBB_VDETECT_Q_VMAX_CTRL_OFFSET 2
#define RX_APB_MMAP_RXBB_VDETECT_Q_VMAX_CTRL_SIZE 3
#define RX_APB_MMAP_RXBB_VDETECT_Q_VMIN_CTRL_OFFSET 5
#define RX_APB_MMAP_RXBB_VDETECT_Q_VMIN_CTRL_SIZE 3

/** bit field defines for rx_apb_mmap_rxbb_s#dcoc */
#define RX_APB_MMAP_RXBB_DCOC_I_IOUT_OFFSET 0
#define RX_APB_MMAP_RXBB_DCOC_I_IOUT_SIZE 7
#define RX_APB_MMAP_RXBB_DCOC_Q_IOUT_OFFSET 7
#define RX_APB_MMAP_RXBB_DCOC_Q_IOUT_SIZE 7
#define RX_APB_MMAP_RXBB_DCOC_I_LSBSEL_OFFSET 14
#define RX_APB_MMAP_RXBB_DCOC_I_LSBSEL_SIZE 2
/**  */
#define RX_APB_MMAP_RXBB_DCOC_I_LSBSEL_1_VALUE 1
/**  */
#define RX_APB_MMAP_RXBB_DCOC_I_LSBSEL_2_VALUE 2
/**  */
#define RX_APB_MMAP_RXBB_DCOC_I_LSBSEL_4_VALUE 3
/**  */
#define RX_APB_MMAP_RXBB_DCOC_I_LSBSEL_5_VALUE 0
#define RX_APB_MMAP_RXBB_DCOC_Q_LSBSEL_OFFSET 16
#define RX_APB_MMAP_RXBB_DCOC_Q_LSBSEL_SIZE 2
/**  */
#define RX_APB_MMAP_RXBB_DCOC_Q_LSBSEL_1_VALUE 1
/**  */
#define RX_APB_MMAP_RXBB_DCOC_Q_LSBSEL_2_VALUE 2
/**  */
#define RX_APB_MMAP_RXBB_DCOC_Q_LSBSEL_4_VALUE 3
/**  */
#define RX_APB_MMAP_RXBB_DCOC_Q_LSBSEL_5_VALUE 0

/** bit field defines for rx_apb_mmap_rxbb_s#tra_1 */
#define RX_APB_MMAP_RXBB_TRA_1_C1_OFFSET 0
#define RX_APB_MMAP_RXBB_TRA_1_C1_SIZE 10
#define RX_APB_MMAP_RXBB_TRA_1_C2_OFFSET 10
#define RX_APB_MMAP_RXBB_TRA_1_C2_SIZE 10
#define RX_APB_MMAP_RXBB_TRA_1_CC1_OFFSET 20
#define RX_APB_MMAP_RXBB_TRA_1_CC1_SIZE 6
#define RX_APB_MMAP_RXBB_TRA_1_CC2_OFFSET 26
#define RX_APB_MMAP_RXBB_TRA_1_CC2_SIZE 6

/** bit field defines for rx_apb_mmap_rxbb_s#tra_2 */
#define RX_APB_MMAP_RXBB_TRA_2_OTA_STAGE1_ITRIM_OFFSET 0
#define RX_APB_MMAP_RXBB_TRA_2_OTA_STAGE1_ITRIM_SIZE 4
#define RX_APB_MMAP_RXBB_TRA_2_OTA_STAGE3_ITRIM_OFFSET 4
#define RX_APB_MMAP_RXBB_TRA_2_OTA_STAGE3_ITRIM_SIZE 5
#define RX_APB_MMAP_RXBB_TRA_2_R2_OFFSET 9
#define RX_APB_MMAP_RXBB_TRA_2_R2_SIZE 8
/**  */
#define RX_APB_MMAP_RXBB_TRA_2_R2_1000_VALUE 0
/**  */
#define RX_APB_MMAP_RXBB_TRA_2_R2_11312_VALUE 127
/**  */
#define RX_APB_MMAP_RXBB_TRA_2_R2_1414_VALUE 1
/**  */
#define RX_APB_MMAP_RXBB_TRA_2_R2_16000_VALUE 255
/**  */
#define RX_APB_MMAP_RXBB_TRA_2_R2_2000_VALUE 3
/**  */
#define RX_APB_MMAP_RXBB_TRA_2_R2_2828_VALUE 7
/**  */
#define RX_APB_MMAP_RXBB_TRA_2_R2_4000_VALUE 15
/**  */
#define RX_APB_MMAP_RXBB_TRA_2_R2_5656_VALUE 31
/**  */
#define RX_APB_MMAP_RXBB_TRA_2_R2_8000_VALUE 63
#define RX_APB_MMAP_RXBB_TRA_2_RCC1_OFFSET 17
#define RX_APB_MMAP_RXBB_TRA_2_RCC1_SIZE 4
/**  */
#define RX_APB_MMAP_RXBB_TRA_2_RCC1_120K_VALUE 3
/**  */
#define RX_APB_MMAP_RXBB_TRA_2_RCC1_240K_VALUE 1
/**  */
#define RX_APB_MMAP_RXBB_TRA_2_RCC1_30K_VALUE 15
/**  */
#define RX_APB_MMAP_RXBB_TRA_2_RCC1_480K_VALUE 0
/**  */
#define RX_APB_MMAP_RXBB_TRA_2_RCC1_60K_VALUE 7
#define RX_APB_MMAP_RXBB_TRA_2_RCC2_OFFSET 21
#define RX_APB_MMAP_RXBB_TRA_2_RCC2_SIZE 2
/**  */
#define RX_APB_MMAP_RXBB_TRA_2_RCC2_0_VALUE 1
/**  */
#define RX_APB_MMAP_RXBB_TRA_2_RCC2_500_VALUE 2
/**  */
#define RX_APB_MMAP_RXBB_TRA_2_RCC2_750_VALUE 0
#define RX_APB_MMAP_RXBB_TRA_2_CC3_OFFSET 23
#define RX_APB_MMAP_RXBB_TRA_2_CC3_SIZE 1
#define RX_APB_MMAP_RXBB_TRA_2_CCCMFB_OFFSET 24
#define RX_APB_MMAP_RXBB_TRA_2_CCCMFB_SIZE 1

/** bit field defines for rx_apb_mmap_rxbb_s#iqmux */
#define RX_APB_MMAP_RXBB_IQMUX_COMP_CC1_OFFSET 0
#define RX_APB_MMAP_RXBB_IQMUX_COMP_CC1_SIZE 3
#define RX_APB_MMAP_RXBB_IQMUX_COMP_RCC1_OFFSET 3
#define RX_APB_MMAP_RXBB_IQMUX_COMP_RCC1_SIZE 1
/**  */
#define RX_APB_MMAP_RXBB_IQMUX_COMP_RCC1_1K_VALUE 1
/**  */
#define RX_APB_MMAP_RXBB_IQMUX_COMP_RCC1_2K_VALUE 0
#define RX_APB_MMAP_RXBB_IQMUX_STAGE1_ITRIM_OFFSET 4
#define RX_APB_MMAP_RXBB_IQMUX_STAGE1_ITRIM_SIZE 3
#define RX_APB_MMAP_RXBB_IQMUX_STAGE2_ITRIM_OFFSET 7
#define RX_APB_MMAP_RXBB_IQMUX_STAGE2_ITRIM_SIZE 3

/** bit field defines for rx_apb_mmap_rxbb_s#iqmux_en */
#define RX_APB_MMAP_RXBB_IQMUX_EN_BUFFER_OFFSET 0
#define RX_APB_MMAP_RXBB_IQMUX_EN_BUFFER_SIZE 1
#define RX_APB_MMAP_RXBB_IQMUX_EN_BYPASS_OFFSET 1
#define RX_APB_MMAP_RXBB_IQMUX_EN_BYPASS_SIZE 1
#define RX_APB_MMAP_RXBB_IQMUX_EN_INPUTDRIVER_TF_OFFSET 2
#define RX_APB_MMAP_RXBB_IQMUX_EN_INPUTDRIVER_TF_SIZE 1
#define RX_APB_MMAP_RXBB_IQMUX_EN_INPUTDRIVER_FILTERINPUT_OFFSET 3
#define RX_APB_MMAP_RXBB_IQMUX_EN_INPUTDRIVER_FILTERINPUT_SIZE 1
#define RX_APB_MMAP_RXBB_IQMUX_EN_INPUTDRIVER_FILTEROUTPUT_OFFSET 4
#define RX_APB_MMAP_RXBB_IQMUX_EN_INPUTDRIVER_FILTEROUTPUT_SIZE 1
#define RX_APB_MMAP_RXBB_IQMUX_EN_INPUTDRIVER_PAD_OFFSET 5
#define RX_APB_MMAP_RXBB_IQMUX_EN_INPUTDRIVER_PAD_SIZE 1
#define RX_APB_MMAP_RXBB_IQMUX_EN_OUTPUTDRIVER_ADC_OFFSET 6
#define RX_APB_MMAP_RXBB_IQMUX_EN_OUTPUTDRIVER_ADC_SIZE 1
#define RX_APB_MMAP_RXBB_IQMUX_EN_OUTPUTDRIVER_PAD_OFFSET 7
#define RX_APB_MMAP_RXBB_IQMUX_EN_OUTPUTDRIVER_PAD_SIZE 1
#define RX_APB_MMAP_RXBB_IQMUX_EN_ADC_DIRECTINPUT_OFFSET 8
#define RX_APB_MMAP_RXBB_IQMUX_EN_ADC_DIRECTINPUT_SIZE 1
#define RX_APB_MMAP_RXBB_IQMUX_EN_OUTPUTDRIVER_PAD_GAIN8K_OFFSET 9
#define RX_APB_MMAP_RXBB_IQMUX_EN_OUTPUTDRIVER_PAD_GAIN8K_SIZE 1
#define RX_APB_MMAP_RXBB_IQMUX_EN_OUTPUTDRIVER_PAD_GAIN16K_OFFSET 10
#define RX_APB_MMAP_RXBB_IQMUX_EN_OUTPUTDRIVER_PAD_GAIN16K_SIZE 1

/** bit field defines for rx_apb_mmap_rxbb_s#atst_rx */
#define RX_APB_MMAP_RXBB_ATST_RX_MASTER_EN_OFFSET 0
#define RX_APB_MMAP_RXBB_ATST_RX_MASTER_EN_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_RX_MASTER_PULLDOWN_OFFSET 1
#define RX_APB_MMAP_RXBB_ATST_RX_MASTER_PULLDOWN_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_RX_AUXADC_EN_OFFSET 2
#define RX_APB_MMAP_RXBB_ATST_RX_AUXADC_EN_SIZE 1

/** bit field defines for rx_apb_mmap_rxbb_s#atst */
#define RX_APB_MMAP_RXBB_ATST_ANA_LDO_EN_A_OFFSET 0
#define RX_APB_MMAP_RXBB_ATST_ANA_LDO_EN_A_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_IQMUX_LDO_EN_A_OFFSET 1
#define RX_APB_MMAP_RXBB_ATST_IQMUX_LDO_EN_A_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_ADC_LDO_EN_A_OFFSET 2
#define RX_APB_MMAP_RXBB_ATST_ADC_LDO_EN_A_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_DCOC_I_EN_A_OFFSET 3
#define RX_APB_MMAP_RXBB_ATST_DCOC_I_EN_A_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_DCOC_I_EN_B_OFFSET 4
#define RX_APB_MMAP_RXBB_ATST_DCOC_I_EN_B_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_DCOC_Q_EN_A_OFFSET 5
#define RX_APB_MMAP_RXBB_ATST_DCOC_Q_EN_A_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_DCOC_Q_EN_B_OFFSET 6
#define RX_APB_MMAP_RXBB_ATST_DCOC_Q_EN_B_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TRA_I_EN_A_OFFSET 7
#define RX_APB_MMAP_RXBB_ATST_TRA_I_EN_A_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TRA_I_EN_B_OFFSET 8
#define RX_APB_MMAP_RXBB_ATST_TRA_I_EN_B_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TRA_Q_EN_A_OFFSET 9
#define RX_APB_MMAP_RXBB_ATST_TRA_Q_EN_A_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TRA_Q_EN_B_OFFSET 10
#define RX_APB_MMAP_RXBB_ATST_TRA_Q_EN_B_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_IQMUX_I_EN_A_OFFSET 11
#define RX_APB_MMAP_RXBB_ATST_IQMUX_I_EN_A_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_IQMUX_I_EN_B_OFFSET 12
#define RX_APB_MMAP_RXBB_ATST_IQMUX_I_EN_B_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_IQMUX_Q_EN_A_OFFSET 13
#define RX_APB_MMAP_RXBB_ATST_IQMUX_Q_EN_A_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_IQMUX_Q_EN_B_OFFSET 14
#define RX_APB_MMAP_RXBB_ATST_IQMUX_Q_EN_B_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_ADC_I_EN_A_OFFSET 15
#define RX_APB_MMAP_RXBB_ATST_ADC_I_EN_A_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_ADC_I_EN_B_OFFSET 16
#define RX_APB_MMAP_RXBB_ATST_ADC_I_EN_B_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_ADC_Q_EN_A_OFFSET 17
#define RX_APB_MMAP_RXBB_ATST_ADC_Q_EN_A_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_ADC_Q_EN_B_OFFSET 18
#define RX_APB_MMAP_RXBB_ATST_ADC_Q_EN_B_SIZE 1

/** bit field defines for rx_apb_mmap_rxbb_s#atst_toplevel_rxbb */
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_ANA_LDO_EN_A_OFFSET 0
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_ANA_LDO_EN_A_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_IQMUX_LDO_EN_A_OFFSET 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_IQMUX_LDO_EN_A_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_ADC_LDO_EN_A_OFFSET 2
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_ADC_LDO_EN_A_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_DCOC_I_EN_A_OFFSET 3
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_DCOC_I_EN_A_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_DCOC_I_EN_B_OFFSET 4
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_DCOC_I_EN_B_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_DCOC_Q_EN_A_OFFSET 5
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_DCOC_Q_EN_A_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_DCOC_Q_EN_B_OFFSET 6
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_DCOC_Q_EN_B_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_TRA_I_EN_A_OFFSET 7
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_TRA_I_EN_A_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_TRA_I_EN_B_OFFSET 8
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_TRA_I_EN_B_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_TRA_Q_EN_A_OFFSET 9
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_TRA_Q_EN_A_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_TRA_Q_EN_B_OFFSET 10
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_TRA_Q_EN_B_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_IQMUX_I_EN_A_OFFSET 11
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_IQMUX_I_EN_A_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_IQMUX_I_EN_B_OFFSET 12
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_IQMUX_I_EN_B_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_IQMUX_Q_EN_A_OFFSET 13
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_IQMUX_Q_EN_A_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_IQMUX_Q_EN_B_OFFSET 14
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_IQMUX_Q_EN_B_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_ADC_I_EN_A_OFFSET 15
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_ADC_I_EN_A_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_ADC_I_EN_B_OFFSET 16
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_ADC_I_EN_B_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_ADC_Q_EN_A_OFFSET 17
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_ADC_Q_EN_A_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_ADC_Q_EN_B_OFFSET 18
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB_ADC_Q_EN_B_SIZE 1

/** bit field defines for rx_apb_mmap_rxbb_s#atst_toplevel_rxrf1 */
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_LNA_EN_A_OFFSET 0
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_LNA_EN_A_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_LNA_EN_B_OFFSET 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_LNA_EN_B_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_LNA_EN_C_OFFSET 2
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_LNA_EN_C_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_LNA_EN_D_OFFSET 3
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_LNA_EN_D_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_LNA_EN_E_OFFSET 4
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_LNA_EN_E_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_LNA_EN_F_OFFSET 5
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_LNA_EN_F_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_LNA_EN_G_OFFSET 6
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_LNA_EN_G_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_LNA_EN_H_OFFSET 7
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_LNA_EN_H_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_LNA_EN_I_OFFSET 8
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_LNA_EN_I_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_MIX_EN_A_OFFSET 9
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_MIX_EN_A_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_MIX_EN_B_OFFSET 10
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_MIX_EN_B_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_MIX_EN_C_OFFSET 11
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_MIX_EN_C_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_MIX_EN_D_OFFSET 12
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_MIX_EN_D_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_MIX_EN_E_OFFSET 13
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_MIX_EN_E_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_MIX_EN_F_OFFSET 14
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_MIX_EN_F_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_MIX_EN_G_OFFSET 15
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_MIX_EN_G_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_MIX_EN_H_OFFSET 16
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_MIX_EN_H_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_MIX_EN_I_OFFSET 17
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_MIX_EN_I_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_MIX_EN_J_OFFSET 18
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1_MIX_EN_J_SIZE 1

/** bit field defines for rx_apb_mmap_rxbb_s#atst_toplevel_rxrf2 */
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_A_OFFSET 0
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_A_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_B_OFFSET 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_B_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_C_OFFSET 2
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_C_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_D_OFFSET 3
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_D_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_E_OFFSET 4
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_E_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_F_OFFSET 5
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_F_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_G_OFFSET 6
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_G_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_H_OFFSET 7
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_H_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_I_OFFSET 8
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_I_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_J_OFFSET 9
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_J_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_K_OFFSET 10
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_K_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_L_OFFSET 11
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_L_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_M_OFFSET 12
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_M_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_N_OFFSET 13
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_N_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_O_OFFSET 14
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_O_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_P_OFFSET 15
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_TCA_EN_P_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_LDO_EN_A_OFFSET 16
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_LDO_EN_A_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_LDO_EN_B_OFFSET 17
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_LDO_EN_B_SIZE 1
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_LDO_EN_C_OFFSET 18
#define RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2_LDO_EN_C_SIZE 1

/** bit field defines for rx_apb_mmap_rxbb_s#rxbb_spare */
#define RX_APB_MMAP_RXBB_RXBB_SPARE_MAIN_OFFSET 0
#define RX_APB_MMAP_RXBB_RXBB_SPARE_MAIN_SIZE 8
#define RX_APB_MMAP_RXBB_RXBB_SPARE_I_OFFSET 8
#define RX_APB_MMAP_RXBB_RXBB_SPARE_I_SIZE 8
#define RX_APB_MMAP_RXBB_RXBB_SPARE_Q_OFFSET 16
#define RX_APB_MMAP_RXBB_RXBB_SPARE_Q_SIZE 8

/** bit field defines for rx_apb_mmap_rxbb_s#adc_clkmux */
#define RX_APB_MMAP_RXBB_ADC_CLKMUX_CLKIN_SEL_OFFSET 0
#define RX_APB_MMAP_RXBB_ADC_CLKMUX_CLKIN_SEL_SIZE 2
/**  */
#define RX_APB_MMAP_RXBB_ADC_CLKMUX_CLKIN_SEL_LO_VALUE 2
/**  */
#define RX_APB_MMAP_RXBB_ADC_CLKMUX_CLKIN_SEL_NO_VALUE 0
/**  */
#define RX_APB_MMAP_RXBB_ADC_CLKMUX_CLKIN_SEL_REF_VALUE 1
#define RX_APB_MMAP_RXBB_ADC_CLKMUX_ADC_CLK_SEL_OFFSET 2
#define RX_APB_MMAP_RXBB_ADC_CLKMUX_ADC_CLK_SEL_SIZE 2
/**  */
#define RX_APB_MMAP_RXBB_ADC_CLKMUX_ADC_CLK_SEL_DIV2_VALUE 3
/**  */
#define RX_APB_MMAP_RXBB_ADC_CLKMUX_ADC_CLK_SEL_NO_VALUE 0
/**  */
#define RX_APB_MMAP_RXBB_ADC_CLKMUX_ADC_CLK_SEL_UNDIV_VALUE 2
#define RX_APB_MMAP_RXBB_ADC_CLKMUX_DIG_CLK_SEL_OFFSET 4
#define RX_APB_MMAP_RXBB_ADC_CLKMUX_DIG_CLK_SEL_SIZE 2
/**  */
#define RX_APB_MMAP_RXBB_ADC_CLKMUX_DIG_CLK_SEL_DIV2_VALUE 3
/**  */
#define RX_APB_MMAP_RXBB_ADC_CLKMUX_DIG_CLK_SEL_NO_VALUE 0
/**  */
#define RX_APB_MMAP_RXBB_ADC_CLKMUX_DIG_CLK_SEL_UNDIV_VALUE 2
#define RX_APB_MMAP_RXBB_ADC_CLKMUX_TX_CLK_SEL_OFFSET 6
#define RX_APB_MMAP_RXBB_ADC_CLKMUX_TX_CLK_SEL_SIZE 2
/**  */
#define RX_APB_MMAP_RXBB_ADC_CLKMUX_TX_CLK_SEL_DIV2_VALUE 3
/**  */
#define RX_APB_MMAP_RXBB_ADC_CLKMUX_TX_CLK_SEL_NO_VALUE 0
/**  */
#define RX_APB_MMAP_RXBB_ADC_CLKMUX_TX_CLK_SEL_UNDIV_VALUE 2
#define RX_APB_MMAP_RXBB_ADC_CLKMUX_ADC_DFE_CLK_INVERT_OFFSET 8
#define RX_APB_MMAP_RXBB_ADC_CLKMUX_ADC_DFE_CLK_INVERT_SIZE 1

/** bit field defines for rx_apb_mmap_rxbb_s#rxtx_clkmux */
#define RX_APB_MMAP_RXBB_RXTX_CLKMUX_CLK_SEL_OFFSET 0
#define RX_APB_MMAP_RXBB_RXTX_CLKMUX_CLK_SEL_SIZE 3
/**  */
#define RX_APB_MMAP_RXBB_RXTX_CLKMUX_CLK_SEL_NORXCLK_VALUE 0
/**  */
#define RX_APB_MMAP_RXBB_RXTX_CLKMUX_CLK_SEL_RX1CLK_VALUE 1
/**  */
#define RX_APB_MMAP_RXBB_RXTX_CLKMUX_CLK_SEL_RX2CLK_VALUE 2
/**  */
#define RX_APB_MMAP_RXBB_RXTX_CLKMUX_CLK_SEL_RXCA1CLK_VALUE 3
/**  */
#define RX_APB_MMAP_RXBB_RXTX_CLKMUX_CLK_SEL_RXCA2CLK_VALUE 4

/** bit field defines for rx_apb_mmap_rxbb_s#dbg_rxbb */
#define RX_APB_MMAP_RXBB_DBG_RXBB_MEMMAP_VERSION_SHDW_OFFSET 0
#define RX_APB_MMAP_RXBB_DBG_RXBB_MEMMAP_VERSION_SHDW_SIZE 16
#define RX_APB_MMAP_RXBB_DBG_RXBB_MEMMAP_VERSION_CFG_OFFSET 16
#define RX_APB_MMAP_RXBB_DBG_RXBB_MEMMAP_VERSION_CFG_SIZE 16

/* EOF rx_apb_mmap_rxbb.h */
#endif
