; 
; Copyright (C) u-blox
; All rights reserved.
; This source file is the sole property of u-blox. Reproduction or utilization
; of this source in whole or part is forbidden without the written consent of
; u-blox.
; 
; FILE: rx_apb_mmap_rxbb.hs

RX_APB_MMAP_RXBB_HAL_VERSION EQU 102
RX_APB_MMAP_RXBB_ANA_LDO EQU 0x000
RX_APB_MMAP_RXBB_IQMUX_LDO EQU 0x004
RX_APB_MMAP_RXBB_ADC_LDO EQU 0x008
RX_APB_MMAP_RXBB_ENABLES EQU 0x00C
RX_APB_MMAP_RXBB_BANDGAP EQU 0x010
RX_APB_MMAP_RXBB_IREF_IQMUX EQU 0x014
RX_APB_MMAP_RXBB_IREF_TRA EQU 0x018
RX_APB_MMAP_RXBB_VDETECT EQU 0x01C
RX_APB_MMAP_RXBB_VDETECT_I EQU 0x020
RX_APB_MMAP_RXBB_VDETECT_Q EQU 0x024
RX_APB_MMAP_RXBB_DCOC EQU 0x028
RX_APB_MMAP_RXBB_TRA_1 EQU 0x02C
RX_APB_MMAP_RXBB_TRA_2 EQU 0x030
RX_APB_MMAP_RXBB_IQMUX EQU 0x034
RX_APB_MMAP_RXBB_IQMUX_EN EQU 0x038
RX_APB_MMAP_RXBB_ATST_RX EQU 0x03C
RX_APB_MMAP_RXBB_ATST EQU 0x040
RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXBB EQU 0x044
RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF1 EQU 0x048
RX_APB_MMAP_RXBB_ATST_TOPLEVEL_RXRF2 EQU 0x04C
RX_APB_MMAP_RXBB_RXBB_SPARE EQU 0x050
RX_APB_MMAP_RXBB_ADC_CLKMUX EQU 0x054
RX_APB_MMAP_RXBB_RXTX_CLKMUX EQU 0x058
RX_APB_MMAP_RXBB_DBG_RXBB EQU 0x05C
; EOF: rx_apb_mmap_rxbb.hs
   END
