; 
; Copyright (C) u-blox
; All rights reserved.
; This source file is the sole property of u-blox. Reproduction or utilization
; of this source in whole or part is forbidden without the written consent of
; u-blox.
; 
; FILE: rx_apb_mmap_rxrf.hs

RX_APB_MMAP_RXRF_HAL_VERSION EQU 102
RX_APB_MMAP_RXRF_LO_LDO EQU 0x000
RX_APB_MMAP_RXRF_RF_LDO EQU 0x004
RX_APB_MMAP_RXRF_TCA_LDO EQU 0x008
RX_APB_MMAP_RXRF_RXRF_ENABLES EQU 0x00C
RX_APB_MMAP_RXRF_LNA_GAIN EQU 0x010
RX_APB_MMAP_RXRF_LNA_IBIAS EQU 0x014
RX_APB_MMAP_RXRF_LNA_VBIAS EQU 0x018
RX_APB_MMAP_RXRF_TCA_I EQU 0x01C
RX_APB_MMAP_RXRF_TCA_Q EQU 0x020
RX_APB_MMAP_RXRF_TF EQU 0x024
RX_APB_MMAP_RXRF_LOCM_I EQU 0x028
RX_APB_MMAP_RXRF_LOCM_Q EQU 0x02C
RX_APB_MMAP_RXRF_DAC_RFPLOP_I EQU 0x030
RX_APB_MMAP_RXRF_DAC_RFPLON_I EQU 0x034
RX_APB_MMAP_RXRF_DAC_RFNLOP_I EQU 0x038
RX_APB_MMAP_RXRF_DAC_RFNLON_I EQU 0x03C
RX_APB_MMAP_RXRF_DAC_RFPLOP_Q EQU 0x040
RX_APB_MMAP_RXRF_DAC_RFPLON_Q EQU 0x044
RX_APB_MMAP_RXRF_DAC_RFNLOP_Q EQU 0x048
RX_APB_MMAP_RXRF_DAC_RFNLON_Q EQU 0x04C
RX_APB_MMAP_RXRF_LO_ROUTE EQU 0x050
RX_APB_MMAP_RXRF_CLKGEN EQU 0x054
RX_APB_MMAP_RXRF_ATST1 EQU 0x058
RX_APB_MMAP_RXRF_ATST2 EQU 0x05C
RX_APB_MMAP_RXRF_RXRF_SPARE EQU 0x060
RX_APB_MMAP_RXRF_DBG_RXRF EQU 0x064
; EOF: rx_apb_mmap_rxrf.hs
   END
