; 
; Copyright (C) u-blox
; All rights reserved.
; This source file is the sole property of u-blox. Reproduction or utilization
; of this source in whole or part is forbidden without the written consent of
; u-blox.
; 
; FILE: smurf_if_1ch.hs

SMURF_IF_1CH_CTRL EQU 0x000
SMURF_IF_1CH_FLTCLEAR EQU 0x300
SMURF_IF_1CH_FLTSTATUS EQU 0x304
SMURF_IF_1CH_FLTRAWSTATUS EQU 0x308
SMURF_IF_1CH_FLTMASKCLR EQU 0x30C
SMURF_IF_1CH_FLTMASKSET EQU 0x310
SMURF_IF_1CH_FLTMASKSTATUS EQU 0x314
SMURF_IF_1CH_PERIPHERALID4 EQU 0xFD0
SMURF_IF_1CH_PERIPHERALID5 EQU 0xFD4
SMURF_IF_1CH_PERIPHERALID6 EQU 0xFD8
SMURF_IF_1CH_PERIPHERALID7 EQU 0xFDC
SMURF_IF_1CH_PERIPHERALID0 EQU 0xFE0
SMURF_IF_1CH_PERIPHERALID1 EQU 0xFE4
SMURF_IF_1CH_PERIPHERALID2 EQU 0xFE8
SMURF_IF_1CH_PERIPHERALID3 EQU 0xFEC
SMURF_IF_1CH_COMPONENTID0 EQU 0xFF0
SMURF_IF_1CH_COMPONENTID1 EQU 0xFF4
SMURF_IF_1CH_COMPONENTID2 EQU 0xFF8
SMURF_IF_1CH_COMPONENTID3 EQU 0xFFC
; EOF: smurf_if_1ch.hs
   END
