; 
; Copyright (C) u-blox
; All rights reserved.
; This source file is the sole property of u-blox. Reproduction or utilization
; of this source in whole or part is forbidden without the written consent of
; u-blox.
; 
; FILE: stm_stim.hs

STM_STIM_NR_PORTS EQU 65536
STM_STIM_WIDTH EQU 256
STM_STIM_PORTS_G_DMTS EQU 0x000
STM_STIM_PORTS_G_DM EQU 0x008
STM_STIM_PORTS_G_DTS EQU 0x010
STM_STIM_PORTS_G_D EQU 0x018
STM_STIM_PORTS_G_FLAGTS EQU 0x060
STM_STIM_PORTS_G_FLAG EQU 0x068
STM_STIM_PORTS_G_TRIGTS EQU 0x070
STM_STIM_PORTS_G_TRIG EQU 0x078
STM_STIM_PORTS_I_DMTS EQU 0x080
STM_STIM_PORTS_I_DM EQU 0x088
STM_STIM_PORTS_I_DTS EQU 0x090
STM_STIM_PORTS_I_D EQU 0x098
STM_STIM_PORTS_I_FLAGTS EQU 0x0E0
STM_STIM_PORTS_I_FLAG EQU 0x0E8
STM_STIM_PORTS_I_TRIGTS EQU 0x0F0
STM_STIM_PORTS_I_TRIG EQU 0x0F8
STM_STIM_PORTS_FILL EQU 0x0FC
; EOF: stm_stim.hs
   END
