; 
; Copyright (C) u-blox
; All rights reserved.
; This source file is the sole property of u-blox. Reproduction or utilization
; of this source in whole or part is forbidden without the written consent of
; u-blox.
; 
; FILE: stm_filter.hs

STM_FILTER_FILTER_CTRL EQU 0x000
STM_FILTER_FILTER_CTRL_FIELDS EQU 16
STM_FILTER_PERIPHERALID4 EQU 0xFD0
STM_FILTER_PERIPHERALID5 EQU 0xFD4
STM_FILTER_PERIPHERALID6 EQU 0xFD8
STM_FILTER_PERIPHERALID7 EQU 0xFDC
STM_FILTER_PERIPHERALID0 EQU 0xFE0
STM_FILTER_PERIPHERALID1 EQU 0xFE4
STM_FILTER_PERIPHERALID2 EQU 0xFE8
STM_FILTER_PERIPHERALID3 EQU 0xFEC
STM_FILTER_COMPONENTID0 EQU 0xFF0
STM_FILTER_COMPONENTID1 EQU 0xFF4
STM_FILTER_COMPONENTID2 EQU 0xFF8
STM_FILTER_COMPONENTID3 EQU 0xFFC
; EOF: stm_filter.hs
   END
