; 
; Copyright (C) u-blox
; All rights reserved.
; This source file is the sole property of u-blox. Reproduction or utilization
; of this source in whole or part is forbidden without the written consent of
; u-blox.
; 
; FILE: tpiu.hs

TPIU_SPORTSIZE EQU 0x000
TPIU_CPORTSIZE EQU 0x004
TPIU_TRIGMODE EQU 0x100
TPIU_TRIGCNT EQU 0x104
TPIU_TRIGMLT EQU 0x108
TPIU_STESTPAT EQU 0x200
TPIU_CTESTPAT EQU 0x204
TPIU_TESTPATRPT EQU 0x208
TPIU_FFSTAT EQU 0x300
TPIU_FFCTRL EQU 0x304
TPIU_FFSYNC EQU 0x308
TPIU_EXTCTLIN EQU 0x400
TPIU_EXTCTLOUT EQU 0x404
TPIU_ITTRFLINACK EQU 0xEE4
TPIU_ITTRFLIN EQU 0xEE8
TPIU_ITATBDATA0 EQU 0xEEC
TPIU_ITATBCTR2 EQU 0xEF0
TPIU_ITATBCTR1 EQU 0xEF4
TPIU_ITATBCTR0 EQU 0xEF8
TPIU_ITMCTRL EQU 0xF00
TPIU_CLAIMSET EQU 0xFA0
TPIU_CLAIMCLR EQU 0xFA4
TPIU_LOCKACCESS EQU 0xFB0
TPIU_LOCKSTATUS EQU 0xFB4
TPIU_AUTHSTATUS EQU 0xFB8
TPIU_DEVID EQU 0xFC8
TPIU_DEVTYPE EQU 0xFCC
TPIU_PERIPHERALID4 EQU 0xFD0
TPIU_PERIPHERALID0 EQU 0xFE0
TPIU_PERIPHERALID1 EQU 0xFE4
TPIU_PERIPHERALID2 EQU 0xFE8
TPIU_PERIPHERALID3 EQU 0xFEC
TPIU_COMPONENTID0 EQU 0xFF0
TPIU_COMPONENTID1 EQU 0xFF4
TPIU_COMPONENTID2 EQU 0xFF8
TPIU_COMPONENTID3 EQU 0xFFC
; EOF: tpiu.hs
   END
