; 
; Copyright (C) u-blox
; All rights reserved.
; This source file is the sole property of u-blox. Reproduction or utilization
; of this source in whole or part is forbidden without the written consent of
; u-blox.
; 
; FILE: tx_apb_mmap_txrf.hs

TX_APB_MMAP_TXRF_HAL_VERSION EQU 101
TX_APB_MMAP_TXRF_LO_LDO EQU 0x000
TX_APB_MMAP_TXRF_RF_LDO EQU 0x004
TX_APB_MMAP_TXRF_CAL_LDO EQU 0x008
TX_APB_MMAP_TXRF_TXRF_ENABLES EQU 0x00C
TX_APB_MMAP_TXRF_DA_GAIN EQU 0x010
TX_APB_MMAP_TXRF_BALUN_TUNE EQU 0x014
TX_APB_MMAP_TXRF_LOCM_I EQU 0x018
TX_APB_MMAP_TXRF_LOCM_Q EQU 0x01C
TX_APB_MMAP_TXRF_DAC_RFPLOP_I EQU 0x020
TX_APB_MMAP_TXRF_DAC_RFPLON_I EQU 0x024
TX_APB_MMAP_TXRF_DAC_RFNLOP_I EQU 0x028
TX_APB_MMAP_TXRF_DAC_RFNLON_I EQU 0x02C
TX_APB_MMAP_TXRF_DAC_RFPLOP_Q EQU 0x030
TX_APB_MMAP_TXRF_DAC_RFPLON_Q EQU 0x034
TX_APB_MMAP_TXRF_DAC_RFNLOP_Q EQU 0x038
TX_APB_MMAP_TXRF_DAC_RFNLON_Q EQU 0x03C
TX_APB_MMAP_TXRF_LO_ROUTE EQU 0x040
TX_APB_MMAP_TXRF_CLKGEN EQU 0x044
TX_APB_MMAP_TXRF_ATST_RF EQU 0x048
TX_APB_MMAP_TXRF_TXRF_SPARE EQU 0x04C
TX_APB_MMAP_TXRF_DBG_TXRF EQU 0x050
; EOF: tx_apb_mmap_txrf.hs
   END
