; 
; Copyright (C) u-blox
; All rights reserved.
; This source file is the sole property of u-blox. Reproduction or utilization
; of this source in whole or part is forbidden without the written consent of
; u-blox.
; 
; FILE: vcu_cr.hs

VSP_NRDE EQU 1
VCU_CR_NRVSP EQU 0x010
VCU_CR_NRVDMA EQU 0x014
VCU_CR_DMEMSIZE EQU 0x020
VCU_CR_DMEMBANKS EQU 0x024
VCU_CR_MEMDISSTAT EQU 0x048
VCU_CR_ITCM_LS_CTRL EQU 0x060
VCU_CR_ITCM_LS_CTRL_FIELDS EQU VSP_NRDE
VCU_CR_DTCM_LS_CTRL EQU 0x070
VCU_CR_DTCM_LS_CTRL_FIELDS EQU VSP_NRDE
VCU_CR_DMEM0TO1_LS_CTRL_THRESH EQU 0x080
VCU_CR_DMEM2TO3_LS_CTRL_THRESH EQU 0x088
VCU_CR_PERIPHERALID4 EQU 0xFD0
VCU_CR_PERIPHERALID5 EQU 0xFD4
VCU_CR_PERIPHERALID6 EQU 0xFD8
VCU_CR_PERIPHERALID7 EQU 0xFDC
VCU_CR_PERIPHERALID0 EQU 0xFE0
VCU_CR_PERIPHERALID1 EQU 0xFE4
VCU_CR_PERIPHERALID2 EQU 0xFE8
VCU_CR_PERIPHERALID3 EQU 0xFEC
VCU_CR_COMPONENTID0 EQU 0xFF0
VCU_CR_COMPONENTID1 EQU 0xFF4
VCU_CR_COMPONENTID2 EQU 0xFF8
VCU_CR_COMPONENTID3 EQU 0xFFC
; EOF: vcu_cr.hs
   END
