/*
 * Copyright (c) 2013-2018, ARM Limited, All Rights Reserved
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef __MBEDTLS_CONFIG_READER_H__
#define __MBEDTLS_CONFIG_READER_H__

#if MBED_CONF_MBEDTLS_MBED_CLOUD_CLIENT
    //#define MBED_CONF_MBEDTLS_ECDHE_ECDSA_WITH_AES_128_CCM_8 - not currently supported. Not sure why it should be
    #undef MBED_CONF_MBEDTLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    #define MBED_CONF_MBEDTLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 1
    #undef MBED_CONF_MBEDTLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    #define MBED_CONF_MBEDTLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 1
#endif

#if MBED_CONF_MBEDTLS_MBED_MINI_CLOUD_CLIENT
    #undef MBED_CONF_MBEDTLS_PSK_WITH_AES_CCM
    #define MBED_CONF_MBEDTLS_PSK_WITH_AES_CCM 1
    #undef MBED_CONF_MBEDTLS_PSK_WITH_AES_128_CBC_SHA256
    #define MBED_CONF_MBEDTLS_PSK_WITH_AES_128_CBC_SHA256 1
#endif

#if MBED_CONF_MBEDTLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    #define MBEDTLS_CONFIG_ECDHE
    #define MBEDTLS_CONFIG_ECDSA
    #define MBEDTLS_CONFIG_ECDHE_ECDSA_KEY_EXCHANGE
    #define MBEDTLS_CONFIG_AES
    #define MBEDTLS_CONFIG_GCM
    #define MBEDTLS_CONFIG_SHA256
#endif

#if MBED_CONF_MBEDTLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    #define MBEDTLS_CONFIG_ECDHE
    #define MBEDTLS_CONFIG_ECDSA
    #define MBEDTLS_CONFIG_ECDHE_ECDSA_KEY_EXCHANGE
    #define MBEDTLS_CONFIG_AES
    #define MBEDTLS_CONFIG_CBC
    #define MBEDTLS_CONFIG_SHA256
#endif

#if MBED_CONF_MBEDTLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384

    #define MBEDTLS_CONFIG_ECDHE
    #define MBEDTLS_CONFIG_ECDSA
    #define MBEDTLS_CONFIG_ECDHE_ECDSA_KEY_EXCHANGE
    #define MBEDTLS_CONFIG_AES
    #define MBEDTLS_CONFIG_CBC
    #define MBEDTLS_CONFIG_SHA512
#endif

#if MBED_CONF_MBEDTLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    #define MBEDTLS_CONFIG_ECDHE
    #define MBEDTLS_CONFIG_ECDSA
    #define MBEDTLS_CONFIG_ECDHE_ECDSA_KEY_EXCHANGE
    #define MBEDTLS_CONFIG_AES
    #define MBEDTLS_CONFIG_GCM
    #define MBEDTLS_CONFIG_SHA512
#endif


#if MBED_CONF_MBEDTLS_ECDHE_ECDSA_WITH_AES_CCM
    #define MBEDTLS_CONFIG_ECDHE
    #define MBEDTLS_CONFIG_ECDSA
    #define MBEDTLS_CONFIG_ECDHE_ECDSA_KEY_EXCHANGE
    #define MBEDTLS_CONFIG_AES
    #define MBEDTLS_CONFIG_CCM
#endif

#if MBED_CONF_MBEDTLS_PSK_WITH_AES_CCM
    #define MBEDTLS_CONFIG_PSK
    #define MBEDTLS_CONFIG_AES
    #define MBEDTLS_CONFIG_CCM
#endif

#if MBED_CONF_MBEDTLS_PSK_WITH_AES_128_CBC_SHA256
    #define MBEDTLS_CONFIG_PSK
    #define MBEDTLS_CONFIG_AES
    #define MBEDTLS_CONFIG_CBC
    #define MBEDTLS_CONFIG_SHA256
#endif

#if MBED_CONF_MBEDTLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256
    #define MBEDTLS_CONFIG_ECDH
    #define MBEDTLS_CONFIG_ECDSA
    #define MBEDTLS_CONFIG_ECDH_ECDSA_KEY_EXCHANGE
    #define MBEDTLS_CONFIG_AES
    #define MBEDTLS_CONFIG_CBC
    #define MBEDTLS_CONFIG_SHA256
#endif

#if MBED_CONF_MBEDTLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256
    #define MBEDTLS_CONFIG_ECDH
    #define MBEDTLS_CONFIG_ECDSA
    #define MBEDTLS_CONFIG_ECDH_ECDSA_KEY_EXCHANGE
    #define MBEDTLS_CONFIG_AES
    #define MBEDTLS_CONFIG_GCM
    #define MBEDTLS_CONFIG_SHA256
#endif

#if MBED_CONF_MBEDTLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384
    #define MBEDTLS_CONFIG_ECDH
    #define MBEDTLS_CONFIG_ECDSA
    #define MBEDTLS_CONFIG_ECDH_ECDSA_KEY_EXCHANGE
    #define MBEDTLS_CONFIG_AES
    #define MBEDTLS_CONFIG_CBC
    #define MBEDTLS_CONFIG_SHA512
#endif

#if (MBED_CONF_MBEDTLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384)
    #define MBEDTLS_CONFIG_ECDH
    #define MBEDTLS_CONFIG_ECDSA
    #define MBEDTLS_CONFIG_ECDH_ECDSA_KEY_EXCHANGE
    #define MBEDTLS_CONFIG_AES
    #define MBEDTLS_CONFIG_GCM
    #define MBEDTLS_CONFIG_SHA512
#endif

#if MBED_CONF_MBEDTLS_PSK_WITH_AES_128_GCM_SHA256
    #define MBEDTLS_CONFIG_PSK
    #define MBEDTLS_CONFIG_AES
    #define MBEDTLS_CONFIG_GCM
    #define MBEDTLS_CONFIG_SHA256
#endif

#if MBED_CONF_MBEDTLS_PSK_WITH_AES_256_GCM_SHA384
    #define MBEDTLS_CONFIG_PSK
    #define MBEDTLS_CONFIG_AES
    #define MBEDTLS_CONFIG_GCM
    #define MBEDTLS_CONFIG_SHA512
#endif

#if (MBED_CONF_MBEDTLS_PSK_WITH_AES_256_CBC_SHA384)
    #define MBEDTLS_CONFIG_PSK
    #define MBEDTLS_CONFIG_AES
    #define MBEDTLS_CONFIG_CBC
    #define MBEDTLS_CONFIG_SHA512
#endif

#if (MBED_CONF_MBEDTLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256)
    #define MBEDTLS_CONFIG_ECDHE
    #define MBEDTLS_CONFIG_RSA
    #define MBEDTLS_CONFIG_ECDHE_RSA_KEY_EXCHANGE
    #define MBEDTLS_CONFIG_AES
    #define MBEDTLS_CONFIG_CBC
    #define MBEDTLS_CONFIG_SHA256
#endif

#if (MBED_CONF_MBEDTLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256)
    #define MBEDTLS_CONFIG_ECDHE
    #define MBEDTLS_CONFIG_RSA
    #define MBEDTLS_CONFIG_ECDHE_RSA_KEY_EXCHANGE
    #define MBEDTLS_CONFIG_AES
    #define MBEDTLS_CONFIG_GCM
    #define MBEDTLS_CONFIG_SHA256
#endif

#if (MBED_CONF_MBEDTLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384)
    #define MBEDTLS_CONFIG_ECDHE
    #define MBEDTLS_CONFIG_RSA
    #define MBEDTLS_CONFIG_ECDHE_RSA_KEY_EXCHANGE
    #define MBEDTLS_CONFIG_AES
    #define MBEDTLS_CONFIG_CBC
    #define MBEDTLS_CONFIG_SHA512
#endif

#if (MBED_CONF_MBEDTLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384)
    #define MBEDTLS_CONFIG_ECDHE
    #define MBEDTLS_CONFIG_RSA
    #define MBEDTLS_CONFIG_ECDHE_RSA_KEY_EXCHANGE
    #define MBEDTLS_CONFIG_AES
    #define MBEDTLS_CONFIG_GCM
    #define MBEDTLS_CONFIG_SHA512
#endif

#if (MBED_CONF_MBEDTLS_RSA_WITH_AES_256_GCM_SHA384)
    #define MBEDTLS_CONFIG_RSA
    #define MBEDTLS_CONFIG_RSA_KEY_EXCHANGE
    #define MBEDTLS_CONFIG_AES
    #define MBEDTLS_CONFIG_GCM
    #define MBEDTLS_CONFIG_SHA512
#endif

#if (MBED_CONF_MBEDTLS_RSA_WITH_AES_128_GCM_SHA256)
    #define MBEDTLS_CONFIG_RSA
    #define MBEDTLS_CONFIG_RSA_KEY_EXCHANGE
    #define MBEDTLS_CONFIG_AES
    #define MBEDTLS_CONFIG_GCM
    #define MBEDTLS_CONFIG_SHA256
#endif

#if (MBED_CONF_MBEDTLS_RSA_WITH_AES_128_CBC_SHA256 || MBED_CONF_MBEDTLS_RSA_WITH_AES_256_CBC_SHA256)
    #define MBEDTLS_CONFIG_RSA
    #define MBEDTLS_CONFIG_RSA_KEY_EXCHANGE
    #define MBEDTLS_CONFIG_AES
    #define MBEDTLS_CONFIG_CBC
    #define MBEDTLS_CONFIG_SHA256
#endif

#if (MBED_CONF_MBEDTLS_ECDH_RSA_WITH_AES_128_CBC_SHA256)

    #define MBEDTLS_CONFIG_ECDH
    #define MBEDTLS_CONFIG_RSA
    #define MBEDTLS_CONFIG_ECDH_RSA_KEY_EXCHANGE
    #define MBEDTLS_CONFIG_AES
    #define MBEDTLS_CONFIG_CBC
    #define MBEDTLS_CONFIG_SHA256
#endif

#if (MBED_CONF_MBEDTLS_ECDH_RSA_WITH_AES_128_GCM_SHA256)
    #define MBEDTLS_CONFIG_ECDH
    #define MBEDTLS_CONFIG_RSA
    #define MBEDTLS_CONFIG_ECDH_RSA_KEY_EXCHANGE
    #define MBEDTLS_CONFIG_AES
    #define MBEDTLS_CONFIG_GCM
    #define MBEDTLS_CONFIG_SHA256
#endif

#if (MBED_CONF_MBEDTLS_ECDH_RSA_WITH_AES_256_CBC_SHA384)
    #define MBEDTLS_CONFIG_ECDH
    #define MBEDTLS_CONFIG_RSA
    #define MBEDTLS_CONFIG_ECDH_RSA_KEY_EXCHANGE
    #define MBEDTLS_CONFIG_AES
    #define MBEDTLS_CONFIG_CBC
    #define MBEDTLS_CONFIG_SHA512
#endif

#if (MBED_CONF_MBEDTLS_ECDH_RSA_WITH_AES_256_GCM_SHA384)
    #define MBEDTLS_CONFIG_ECDH
    #define MBEDTLS_CONFIG_RSA
    #define MBEDTLS_CONFIG_ECDH_RSA_KEY_EXCHANGE
    #define MBEDTLS_CONFIG_AES
    #define MBEDTLS_CONFIG_GCM
    #define MBEDTLS_CONFIG_SHA512
#endif

#ifdef MBEDTLS_CONFIG_AES
    #define MBEDTLS_AES_ROM_TABLES
    #define MBEDTLS_AES_C
    #define MBEDTLS_CIPHER_C
#endif

#ifdef MBEDTLS_CONFIG_ECDHE
    #define MBEDTLS_X509_USE_C
    #define MBEDTLS_PEM_PARSE_C
    #define MBEDTLS_BASE64_C
    #define MBEDTLS_ASN1_PARSE_C
    #define MBEDTLS_PK_PARSE_C
    #define MBEDTLS_PK_C
    #define MBEDTLS_ECDH_C
    #define MBEDTLS_ECP_C
    #define MBEDTLS_BIGNUM_C
    #define MBEDTLS_ECP_DP_SECP256R1_ENABLED
    #define MBEDTLS_ECP_DP_SECP384R1_ENABLED
    #define MBEDTLS_ECP_DP_CURVE25519_ENABLED
    #define MBEDTLS_ECP_NIST_OPTIM
#endif

#ifdef MBEDTLS_CONFIG_ECDSA
    #define MBEDTLS_ECDSA_C
    #define MBEDTLS_ECP_C
    #define MBEDTLS_X509_USE_C
    #define MBEDTLS_PEM_PARSE_C
    #define MBEDTLS_BASE64_C
    #define MBEDTLS_ASN1_PARSE_C
    #define MBEDTLS_BIGNUM_C
    #define MBEDTLS_OID_C
    #define MBEDTLS_PK_PARSE_C
    #define MBEDTLS_PK_C
    #define MBEDTLS_ASN1_WRITE_C
    #define MBEDTLS_ECP_DP_SECP256R1_ENABLED
    #define MBEDTLS_ECP_DP_SECP384R1_ENABLED
    #define MBEDTLS_ECP_DP_CURVE25519_ENABLED
    #define MBEDTLS_ECP_NIST_OPTIM
    #define MBEDTLS_ECDSA_DETERMINISTIC
#endif

#ifdef MBEDTLS_CONFIG_ECDHE_ECDSA_KEY_EXCHANGE
    #define MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED
    #define MBEDTLS_ECDH_C
    #define MBEDTLS_ECDSA_C
    #define MBEDTLS_X509_CRT_PARSE_C
    #define MBEDTLS_SSL_SERVER_NAME_INDICATION
    #define MBEDTLS_X509_USE_C
    #define MBEDTLS_PEM_PARSE_C
    #define MBEDTLS_BASE64_C
    #define MBEDTLS_ASN1_PARSE_C
    #define MBEDTLS_BIGNUM_C
    #define MBEDTLS_OID_C
    #define MBEDTLS_PK_PARSE_C
    #define MBEDTLS_PK_C
    #define MBEDTLS_ECP_DP_SECP256R1_ENABLED
    #define MBEDTLS_ECP_DP_SECP384R1_ENABLED
    #define MBEDTLS_ECP_DP_CURVE25519_ENABLED
    #define MBEDTLS_ECP_NIST_OPTIM
#endif

#ifdef MBEDTLS_CONFIG_GCM
    #define MBEDTLS_GCM_C
#endif

#ifdef MBEDTLS_CONFIG_SHA256
    #define MBEDTLS_SHA256_C
    #define MBEDTLS_MD_C
#endif

#ifdef MBEDTLS_CONFIG_SHA512
    #define MBEDTLS_SHA512_C
    #define MBEDTLS_MD_C
#endif

#ifdef MBEDTLS_CONFIG_CBC
    #define MBEDTLS_CIPHER_MODE_CBC
    #define MBEDTLS_CIPHER_PADDING_PKCS7
#endif
#ifdef MBEDTLS_CONFIG_CCM
    #define MBEDTLS_CCM_C
#endif

#ifdef MBEDTLS_CONFIG_PSK
    #define MBEDTLS_KEY_EXCHANGE_PSK_ENABLED
#endif

#ifdef MBEDTLS_CONFIG_ECDH
    #define MBEDTLS_X509_USE_C
    #define MBEDTLS_PEM_PARSE_C
    #define MBEDTLS_BASE64_C
    #define MBEDTLS_ASN1_PARSE_C
    #define MBEDTLS_PK_PARSE_C
    #define MBEDTLS_PK_C
    #define MBEDTLS_ECDH_C
    #define MBEDTLS_ECP_C
    #define MBEDTLS_BIGNUM_C
    #define MBEDTLS_ECP_DP_SECP256R1_ENABLED
    #define MBEDTLS_ECP_DP_SECP384R1_ENABLED
    #define MBEDTLS_ECP_DP_CURVE25519_ENABLED
    #define MBEDTLS_ECP_NIST_OPTIM
#endif

#ifdef MBEDTLS_CONFIG_ECDH_ECDSA_KEY_EXCHANGE
    #define MBEDTLS_KEY_EXCHANGE_ECDH_ECDSA_ENABLED
    #define MBEDTLS_X509_CRT_PARSE_C
    #define MBEDTLS_SSL_SERVER_NAME_INDICATION
    #define MBEDTLS_X509_USE_C
    #define MBEDTLS_PEM_PARSE_C
    #define MBEDTLS_BASE64_C
#endif

#ifdef MBEDTLS_CONFIG_RSA
    #define MBEDTLS_RSA_C
    #define MBEDTLS_BIGNUM_C
    #define MBEDTLS_OID_C
#endif

#ifdef MBEDTLS_CONFIG_ECDHE_RSA_KEY_EXCHANGE
    #define MBEDTLS_KEY_EXCHANGE_ECDHE_RSA_ENABLED
    #define MBEDTLS_ECDH_C
    #define MBEDTLS_RSA_C
    #define MBEDTLS_PKCS1_V15
    #define MBEDTLS_PKCS1_V21
    #define MBEDTLS_X509_CRT_PARSE_C
    #define MBEDTLS_SSL_SERVER_NAME_INDICATION
    #define MBEDTLS_X509_USE_C
    #define MBEDTLS_PEM_PARSE_C
    #define MBEDTLS_BASE64_C
#endif

#ifdef MBEDTLS_CONFIG_RSA_KEY_EXCHANGE
    #define MBEDTLS_KEY_EXCHANGE_RSA_ENABLED
    #define MBEDTLS_RSA_C
    
    #define MBEDTLS_PKCS1_V15
    #define MBEDTLS_X509_CRT_PARSE_C
    #define MBEDTLS_SSL_SERVER_NAME_INDICATION
    #define MBEDTLS_X509_USE_C
    #define MBEDTLS_PEM_PARSE_C
    #define MBEDTLS_BASE64_C
    #define MBEDTLS_BIGNUM_C
    #define MBEDTLS_OID_C
    #define MBEDTLS_ASN1_PARSE_C
    #define MBEDTLS_PK_PARSE_C
    #define MBEDTLS_PK_C
#endif

#ifdef MBEDTLS_CONFIG_ECDH_RSA_KEY_EXCHANGE
    #define MBEDTLS_KEY_EXCHANGE_ECDH_RSA_ENABLED
    #define MBEDTLS_PKCS1_V15
    #define MBEDTLS_ECDH_C
    #define MBEDTLS_X509_CRT_PARSE_C
    #define MBEDTLS_SSL_SERVER_NAME_INDICATION
#endif

#include "check_config.h"

#endif // __MBEDTLS_CONFIG_READER_H__