/* us ticker */
#define US_TICKER_TIMER			TIMER1
#define US_TICKER_TIMER_CLOCK	cmuClock_TIMER1
#define US_TICKER_TIMER_IRQ		TIMER1_IRQn

/* PWM */
#define PWM_TIMER TIMER0
#define PWM_TIMER_CLOCK cmuClock_TIMER0
#define PWM_ROUTE TIMER_ROUTE_LOCATION_LOC3
